# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base/user/user.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'base/user/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base import common_pb2 as base_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62\x61se/user/user.proto\x12\tbase.user\x1a\x11\x62\x61se/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x03\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x19\n\x0cphone_number\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x12\n\nfirst_name\x18\x04 \x01(\t\x12\x11\n\tlast_name\x18\x05 \x01(\t\x12\x12\n\nbirth_date\x18\x06 \x01(\t\x12\x15\n\rpassword_hash\x18\x07 \x01(\x0c\x12\'\n\rprofile_image\x18\x08 \x01(\x0b\x32\x0b.base.ImageH\x01\x88\x01\x01\x12\r\n\x05roles\x18\t \x03(\t\x12\x1c\n\x14is_document_verified\x18\n \x01(\x08\x12\x19\n\x11is_email_verified\x18\x0b \x01(\x08\x12\x14\n\x0cis_suspended\x18\x0c \x01(\x08\x12.\n\ncreated_at\x18\r \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0f\n\r_phone_numberB\x10\n\x0e_profile_image\"\xe5\x01\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nimage_type\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\x05\x65rror\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x1a\n\x05image\x18\x06 \x01(\x0b\x32\x0b.base.Image\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\n\x06_error\"+\n\x06\x44\x65\x66\x65\x63t\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\tB!Z\x1f\x63\x61rsharing/protos/gen/base/userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base.user.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037carsharing/protos/gen/base/user'
  _globals['_USER']._serialized_start=88
  _globals['_USER']._serialized_end=496
  _globals['_DOCUMENT']._serialized_start=499
  _globals['_DOCUMENT']._serialized_end=728
  _globals['_DEFECT']._serialized_start=730
  _globals['_DEFECT']._serialized_end=773
# @@protoc_insertion_point(module_scope)
