// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/booking-service/internal/model"
	validation "carsharing/booking-service/internal/validation"
	mock "github.com/stretchr/testify/mock"
)

// MockBookingService is an autogenerated mock type for the BookingService type
type MockBookingService struct {
	mock.Mock
}

type MockBookingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingService) EXPECT() *MockBookingService_Expecter {
	return &MockBookingService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, id, reason
func (_m *MockBookingService) Cancel(ctx context.Context, id string, reason *string) error {
	ret := _m.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) error); ok {
		r0 = rf(ctx, id, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookingService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockBookingService_Cancel_Call struct {
	*mock.Call
}

func (_e *MockBookingService_Expecter) Cancel(ctx interface{}, id interface{}, reason interface{}) *MockBookingService_Cancel_Call {
	return &MockBookingService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id, reason)}
}

func (_c *MockBookingService_Cancel_Call) Run(run func(ctx context.Context, id string, reason *string)) *MockBookingService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string))
	})
	return _c
}

func (_c *MockBookingService_Cancel_Call) Return(_a0 error) *MockBookingService_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookingService_Cancel_Call) RunAndReturn(run func(context.Context, string, *string) error) *MockBookingService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockBookingService) Create(ctx context.Context, data validation.BookingCreate) (string, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.BookingCreate) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.BookingCreate) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.BookingCreate) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingService_Create_Call struct {
	*mock.Call
}

func (_e *MockBookingService_Expecter) Create(ctx interface{}, data interface{}) *MockBookingService_Create_Call {
	return &MockBookingService_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockBookingService_Create_Call) Run(run func(ctx context.Context, data validation.BookingCreate)) *MockBookingService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.BookingCreate))
	})
	return _c
}

func (_c *MockBookingService_Create_Call) Return(_a0 string, _a1 error) *MockBookingService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingService_Create_Call) RunAndReturn(run func(context.Context, validation.BookingCreate) (string, error)) *MockBookingService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockBookingService) GetByID(ctx context.Context, id string) (model.Booking, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Booking, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Booking); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBookingService_GetByID_Call struct {
	*mock.Call
}

func (_e *MockBookingService_Expecter) GetByID(ctx interface{}, id interface{}) *MockBookingService_GetByID_Call {
	return &MockBookingService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBookingService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockBookingService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBookingService_GetByID_Call) Return(_a0 model.Booking, _a1 error) *MockBookingService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingService_GetByID_Call) RunAndReturn(run func(context.Context, string) (model.Booking, error)) *MockBookingService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusHistory provides a mock function with given fields: ctx, filter
func (_m *MockBookingService) GetStatusHistory(ctx context.Context, filter validation.BookingStatusHistoryFilter) ([]model.BookingStatusReading, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusHistory")
	}

	var r0 []model.BookingStatusReading
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.BookingStatusHistoryFilter) ([]model.BookingStatusReading, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.BookingStatusHistoryFilter) []model.BookingStatusReading); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BookingStatusReading)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.BookingStatusHistoryFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingService_GetStatusHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusHistory'
type MockBookingService_GetStatusHistory_Call struct {
	*mock.Call
}

func (_e *MockBookingService_Expecter) GetStatusHistory(ctx interface{}, filter interface{}) *MockBookingService_GetStatusHistory_Call {
	return &MockBookingService_GetStatusHistory_Call{Call: _e.mock.On("GetStatusHistory", ctx, filter)}
}

func (_c *MockBookingService_GetStatusHistory_Call) Run(run func(ctx context.Context, filter validation.BookingStatusHistoryFilter)) *MockBookingService_GetStatusHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.BookingStatusHistoryFilter))
	})
	return _c
}

func (_c *MockBookingService_GetStatusHistory_Call) Return(_a0 []model.BookingStatusReading, _a1 error) *MockBookingService_GetStatusHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingService_GetStatusHistory_Call) RunAndReturn(run func(context.Context, validation.BookingStatusHistoryFilter) ([]model.BookingStatusReading, error)) *MockBookingService_GetStatusHistory_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockBookingService) List(ctx context.Context, filter validation.BookingListFilter) ([]model.Booking, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.BookingListFilter) ([]model.Booking, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.BookingListFilter) []model.Booking); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.BookingListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBookingService_List_Call struct {
	*mock.Call
}

func (_e *MockBookingService_Expecter) List(ctx interface{}, filter interface{}) *MockBookingService_List_Call {
	return &MockBookingService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockBookingService_List_Call) Run(run func(ctx context.Context, filter validation.BookingListFilter)) *MockBookingService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.BookingListFilter))
	})
	return _c
}

func (_c *MockBookingService_List_Call) Return(_a0 []model.Booking, _a1 error) *MockBookingService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingService_List_Call) RunAndReturn(run func(context.Context, validation.BookingListFilter) ([]model.Booking, error)) *MockBookingService_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, data
func (_m *MockBookingService) UpdateStatus(ctx context.Context, id string, data validation.BookingStatusUpdate) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, validation.BookingStatusUpdate) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookingService_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockBookingService_UpdateStatus_Call struct {
	*mock.Call
}

func (_e *MockBookingService_Expecter) UpdateStatus(ctx interface{}, id interface{}, data interface{}) *MockBookingService_UpdateStatus_Call {
	return &MockBookingService_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, data)}
}

func (_c *MockBookingService_UpdateStatus_Call) Run(run func(ctx context.Context, id string, data validation.BookingStatusUpdate)) *MockBookingService_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(validation.BookingStatusUpdate))
	})
	return _c
}

func (_c *MockBookingService_UpdateStatus_Call) Return(_a0 error) *MockBookingService_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookingService_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, validation.BookingStatusUpdate) error) *MockBookingService_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingService creates a new instance of MockBookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingService {
	mock := &MockBookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
