// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/sorawaslocked/car-rental-booking-service/internal/model"
)

// MockPricingRuleService is an autogenerated mock type for the PricingRuleService type
type MockPricingRuleService struct {
	mock.Mock
}

type MockPricingRuleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPricingRuleService) EXPECT() *MockPricingRuleService_Expecter {
	return &MockPricingRuleService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockPricingRuleService) Create(ctx context.Context, data model.PricingRuleCreate) (string, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PricingRuleCreate) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PricingRuleCreate) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PricingRuleCreate) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPricingRuleService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPricingRuleService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data model.PricingRuleCreate
func (_e *MockPricingRuleService_Expecter) Create(ctx interface{}, data interface{}) *MockPricingRuleService_Create_Call {
	return &MockPricingRuleService_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockPricingRuleService_Create_Call) Run(run func(ctx context.Context, data model.PricingRuleCreate)) *MockPricingRuleService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PricingRuleCreate))
	})
	return _c
}

func (_c *MockPricingRuleService_Create_Call) Return(_a0 string, _a1 error) *MockPricingRuleService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPricingRuleService_Create_Call) RunAndReturn(run func(context.Context, model.PricingRuleCreate) (string, error)) *MockPricingRuleService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPricingRuleService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPricingRuleService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPricingRuleService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPricingRuleService_Expecter) Delete(ctx interface{}, id interface{}) *MockPricingRuleService_Delete_Call {
	return &MockPricingRuleService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPricingRuleService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockPricingRuleService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPricingRuleService_Delete_Call) Return(_a0 error) *MockPricingRuleService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPricingRuleService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockPricingRuleService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockPricingRuleService) GetByID(ctx context.Context, id string) (model.PricingRule, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.PricingRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.PricingRule, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.PricingRule); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.PricingRule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPricingRuleService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPricingRuleService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPricingRuleService_Expecter) GetByID(ctx interface{}, id interface{}) *MockPricingRuleService_GetByID_Call {
	return &MockPricingRuleService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPricingRuleService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockPricingRuleService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPricingRuleService_GetByID_Call) Return(_a0 model.PricingRule, _a1 error) *MockPricingRuleService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPricingRuleService_GetByID_Call) RunAndReturn(run func(context.Context, string) (model.PricingRule, error)) *MockPricingRuleService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockPricingRuleService) List(ctx context.Context, filter model.PricingRuleListFilter) ([]model.PricingRule, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.PricingRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PricingRuleListFilter) ([]model.PricingRule, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PricingRuleListFilter) []model.PricingRule); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PricingRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PricingRuleListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPricingRuleService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPricingRuleService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.PricingRuleListFilter
func (_e *MockPricingRuleService_Expecter) List(ctx interface{}, filter interface{}) *MockPricingRuleService_List_Call {
	return &MockPricingRuleService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockPricingRuleService_List_Call) Run(run func(ctx context.Context, filter model.PricingRuleListFilter)) *MockPricingRuleService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PricingRuleListFilter))
	})
	return _c
}

func (_c *MockPricingRuleService_List_Call) Return(_a0 []model.PricingRule, _a1 error) *MockPricingRuleService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPricingRuleService_List_Call) RunAndReturn(run func(context.Context, model.PricingRuleListFilter) ([]model.PricingRule, error)) *MockPricingRuleService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *MockPricingRuleService) Update(ctx context.Context, id string, data model.PricingRuleUpdate) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.PricingRuleUpdate) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPricingRuleService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPricingRuleService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data model.PricingRuleUpdate
func (_e *MockPricingRuleService_Expecter) Update(ctx interface{}, id interface{}, data interface{}) *MockPricingRuleService_Update_Call {
	return &MockPricingRuleService_Update_Call{Call: _e.mock.On("Update", ctx, id, data)}
}

func (_c *MockPricingRuleService_Update_Call) Run(run func(ctx context.Context, id string, data model.PricingRuleUpdate)) *MockPricingRuleService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.PricingRuleUpdate))
	})
	return _c
}

func (_c *MockPricingRuleService_Update_Call) Return(_a0 error) *MockPricingRuleService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPricingRuleService_Update_Call) RunAndReturn(run func(context.Context, string, model.PricingRuleUpdate) error) *MockPricingRuleService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPricingRuleService creates a new instance of MockPricingRuleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPricingRuleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPricingRuleService {
	mock := &MockPricingRuleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
