// Code generated by mockery. DO NOT EDIT.

package svcmocks

import (
	context "context"

	model "github.com/sorawaslocked/car-rental-trip-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishTripCancelled provides a mock function with given fields: ctx, trip
func (_m *MockEventPublisher) PublishTripCancelled(ctx context.Context, trip model.Trip) error {
	ret := _m.Called(ctx, trip)

	if len(ret) == 0 {
		panic("no return value specified for PublishTripCancelled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Trip) error); ok {
		r0 = rf(ctx, trip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishTripCancelled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTripCancelled'
type MockEventPublisher_PublishTripCancelled_Call struct {
	*mock.Call
}

// PublishTripCancelled is a helper method to define mock.On call
//   - ctx context.Context
//   - trip model.Trip
func (_e *MockEventPublisher_Expecter) PublishTripCancelled(ctx interface{}, trip interface{}) *MockEventPublisher_PublishTripCancelled_Call {
	return &MockEventPublisher_PublishTripCancelled_Call{Call: _e.mock.On("PublishTripCancelled", ctx, trip)}
}

func (_c *MockEventPublisher_PublishTripCancelled_Call) Run(run func(ctx context.Context, trip model.Trip)) *MockEventPublisher_PublishTripCancelled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Trip))
	})
	return _c
}

func (_c *MockEventPublisher_PublishTripCancelled_Call) Return(_a0 error) *MockEventPublisher_PublishTripCancelled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishTripCancelled_Call) RunAndReturn(run func(context.Context, model.Trip) error) *MockEventPublisher_PublishTripCancelled_Call {
	_c.Call.Return(run)
	return _c
}

// PublishTripEnded provides a mock function with given fields: ctx, trip
func (_m *MockEventPublisher) PublishTripEnded(ctx context.Context, trip model.Trip) error {
	ret := _m.Called(ctx, trip)

	if len(ret) == 0 {
		panic("no return value specified for PublishTripEnded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Trip) error); ok {
		r0 = rf(ctx, trip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishTripEnded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTripEnded'
type MockEventPublisher_PublishTripEnded_Call struct {
	*mock.Call
}

// PublishTripEnded is a helper method to define mock.On call
//   - ctx context.Context
//   - trip model.Trip
func (_e *MockEventPublisher_Expecter) PublishTripEnded(ctx interface{}, trip interface{}) *MockEventPublisher_PublishTripEnded_Call {
	return &MockEventPublisher_PublishTripEnded_Call{Call: _e.mock.On("PublishTripEnded", ctx, trip)}
}

func (_c *MockEventPublisher_PublishTripEnded_Call) Run(run func(ctx context.Context, trip model.Trip)) *MockEventPublisher_PublishTripEnded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Trip))
	})
	return _c
}

func (_c *MockEventPublisher_PublishTripEnded_Call) Return(_a0 error) *MockEventPublisher_PublishTripEnded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishTripEnded_Call) RunAndReturn(run func(context.Context, model.Trip) error) *MockEventPublisher_PublishTripEnded_Call {
	_c.Call.Return(run)
	return _c
}

// PublishTripStarted provides a mock function with given fields: ctx, trip
func (_m *MockEventPublisher) PublishTripStarted(ctx context.Context, trip model.Trip) error {
	ret := _m.Called(ctx, trip)

	if len(ret) == 0 {
		panic("no return value specified for PublishTripStarted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Trip) error); ok {
		r0 = rf(ctx, trip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishTripStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTripStarted'
type MockEventPublisher_PublishTripStarted_Call struct {
	*mock.Call
}

// PublishTripStarted is a helper method to define mock.On call
//   - ctx context.Context
//   - trip model.Trip
func (_e *MockEventPublisher_Expecter) PublishTripStarted(ctx interface{}, trip interface{}) *MockEventPublisher_PublishTripStarted_Call {
	return &MockEventPublisher_PublishTripStarted_Call{Call: _e.mock.On("PublishTripStarted", ctx, trip)}
}

func (_c *MockEventPublisher_PublishTripStarted_Call) Run(run func(ctx context.Context, trip model.Trip)) *MockEventPublisher_PublishTripStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Trip))
	})
	return _c
}

func (_c *MockEventPublisher_PublishTripStarted_Call) Return(_a0 error) *MockEventPublisher_PublishTripStarted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishTripStarted_Call) RunAndReturn(run func(context.Context, model.Trip) error) *MockEventPublisher_PublishTripStarted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
