// Code generated by mockery. DO NOT EDIT.

package svcmocks

import (
	context "context"

	model "github.com/sorawaslocked/car-rental-trip-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockBookingClient is an autogenerated mock type for the BookingClient type
type MockBookingClient struct {
	mock.Mock
}

type MockBookingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingClient) EXPECT() *MockBookingClient_Expecter {
	return &MockBookingClient_Expecter{mock: &_m.Mock}
}

// GetBooking provides a mock function with given fields: ctx, id
func (_m *MockBookingClient) GetBooking(ctx context.Context, id string) (model.Booking, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBooking")
	}

	var r0 model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Booking, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Booking); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingClient_GetBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooking'
type MockBookingClient_GetBooking_Call struct {
	*mock.Call
}

// GetBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookingClient_Expecter) GetBooking(ctx interface{}, id interface{}) *MockBookingClient_GetBooking_Call {
	return &MockBookingClient_GetBooking_Call{Call: _e.mock.On("GetBooking", ctx, id)}
}

func (_c *MockBookingClient_GetBooking_Call) Run(run func(ctx context.Context, id string)) *MockBookingClient_GetBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBookingClient_GetBooking_Call) Return(_a0 model.Booking, _a1 error) *MockBookingClient_GetBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingClient_GetBooking_Call) RunAndReturn(run func(context.Context, string) (model.Booking, error)) *MockBookingClient_GetBooking_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingClient creates a new instance of MockBookingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingClient {
	mock := &MockBookingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
