// Code generated by mockery. DO NOT EDIT.

package svcmocks

import (
	context "context"

	model "carsharing/trip-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTripStatusReadingRepository is an autogenerated mock type for the TripStatusReadingRepository type
type MockTripStatusReadingRepository struct {
	mock.Mock
}

type MockTripStatusReadingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripStatusReadingRepository) EXPECT() *MockTripStatusReadingRepository_Expecter {
	return &MockTripStatusReadingRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, reading
func (_m *MockTripStatusReadingRepository) Create(ctx context.Context, reading model.TripStatusReadingCreate) (model.TripStatusReading, error) {
	ret := _m.Called(ctx, reading)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.TripStatusReading
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TripStatusReadingCreate) (model.TripStatusReading, error)); ok {
		return rf(ctx, reading)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TripStatusReadingCreate) model.TripStatusReading); ok {
		r0 = rf(ctx, reading)
	} else {
		r0 = ret.Get(0).(model.TripStatusReading)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TripStatusReadingCreate) error); ok {
		r1 = rf(ctx, reading)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripStatusReadingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTripStatusReadingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - reading model.TripStatusReadingCreate
func (_e *MockTripStatusReadingRepository_Expecter) Create(ctx interface{}, reading interface{}) *MockTripStatusReadingRepository_Create_Call {
	return &MockTripStatusReadingRepository_Create_Call{Call: _e.mock.On("Create", ctx, reading)}
}

func (_c *MockTripStatusReadingRepository_Create_Call) Run(run func(ctx context.Context, reading model.TripStatusReadingCreate)) *MockTripStatusReadingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TripStatusReadingCreate))
	})
	return _c
}

func (_c *MockTripStatusReadingRepository_Create_Call) Return(_a0 model.TripStatusReading, _a1 error) *MockTripStatusReadingRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripStatusReadingRepository_Create_Call) RunAndReturn(run func(context.Context, model.TripStatusReadingCreate) (model.TripStatusReading, error)) *MockTripStatusReadingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockTripStatusReadingRepository) List(ctx context.Context, filter model.TripStatusReadingFilter) ([]model.TripStatusReading, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.TripStatusReading
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TripStatusReadingFilter) ([]model.TripStatusReading, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TripStatusReadingFilter) []model.TripStatusReading); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TripStatusReading)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TripStatusReadingFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripStatusReadingRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTripStatusReadingRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.TripStatusReadingFilter
func (_e *MockTripStatusReadingRepository_Expecter) List(ctx interface{}, filter interface{}) *MockTripStatusReadingRepository_List_Call {
	return &MockTripStatusReadingRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockTripStatusReadingRepository_List_Call) Run(run func(ctx context.Context, filter model.TripStatusReadingFilter)) *MockTripStatusReadingRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TripStatusReadingFilter))
	})
	return _c
}

func (_c *MockTripStatusReadingRepository_List_Call) Return(_a0 []model.TripStatusReading, _a1 error) *MockTripStatusReadingRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripStatusReadingRepository_List_Call) RunAndReturn(run func(context.Context, model.TripStatusReadingFilter) ([]model.TripStatusReading, error)) *MockTripStatusReadingRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripStatusReadingRepository creates a new instance of MockTripStatusReadingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripStatusReadingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripStatusReadingRepository {
	mock := &MockTripStatusReadingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
