// Code generated by mockery. DO NOT EDIT.

package svcmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockZonePricingClient is an autogenerated mock type for the ZonePricingClient type
type MockZonePricingClient struct {
	mock.Mock
}

type MockZonePricingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockZonePricingClient) EXPECT() *MockZonePricingClient_Expecter {
	return &MockZonePricingClient_Expecter{mock: &_m.Mock}
}

// GetZonePricing provides a mock function with given fields: ctx, lat, lng
func (_m *MockZonePricingClient) GetZonePricing(ctx context.Context, lat float64, lng float64) (int32, error) {
	ret := _m.Called(ctx, lat, lng)

	if len(ret) == 0 {
		panic("no return value specified for GetZonePricing")
	}

	var r0 int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (int32, error)); ok {
		return rf(ctx, lat, lng)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) int32); ok {
		r0 = rf(ctx, lat, lng)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lat, lng)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZonePricingClient_GetZonePricing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZonePricing'
type MockZonePricingClient_GetZonePricing_Call struct {
	*mock.Call
}

// GetZonePricing is a helper method to define mock.On call
//   - ctx context.Context
//   - lat float64
//   - lng float64
func (_e *MockZonePricingClient_Expecter) GetZonePricing(ctx interface{}, lat interface{}, lng interface{}) *MockZonePricingClient_GetZonePricing_Call {
	return &MockZonePricingClient_GetZonePricing_Call{Call: _e.mock.On("GetZonePricing", ctx, lat, lng)}
}

func (_c *MockZonePricingClient_GetZonePricing_Call) Run(run func(ctx context.Context, lat float64, lng float64)) *MockZonePricingClient_GetZonePricing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockZonePricingClient_GetZonePricing_Call) Return(_a0 int32, _a1 error) *MockZonePricingClient_GetZonePricing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZonePricingClient_GetZonePricing_Call) RunAndReturn(run func(context.Context, float64, float64) (int32, error)) *MockZonePricingClient_GetZonePricing_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockZonePricingClient creates a new instance of MockZonePricingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockZonePricingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockZonePricingClient {
	mock := &MockZonePricingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
