// Code generated by mockery. DO NOT EDIT.

package svcmocks

import (
	context "context"

	model "carsharing/trip-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTelematicsClient is an autogenerated mock type for the TelematicsClient type
type MockTelematicsClient struct {
	mock.Mock
}

type MockTelematicsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelematicsClient) EXPECT() *MockTelematicsClient_Expecter {
	return &MockTelematicsClient_Expecter{mock: &_m.Mock}
}

// GetLatestTelemetry provides a mock function with given fields: ctx, carID
func (_m *MockTelematicsClient) GetLatestTelemetry(ctx context.Context, carID string) (model.CarTelemetry, error) {
	ret := _m.Called(ctx, carID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestTelemetry")
	}

	var r0 model.CarTelemetry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CarTelemetry, error)); ok {
		return rf(ctx, carID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CarTelemetry); ok {
		r0 = rf(ctx, carID)
	} else {
		r0 = ret.Get(0).(model.CarTelemetry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, carID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTelematicsClient_GetLatestTelemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestTelemetry'
type MockTelematicsClient_GetLatestTelemetry_Call struct {
	*mock.Call
}

// GetLatestTelemetry is a helper method to define mock.On call
//   - ctx context.Context
//   - carID string
func (_e *MockTelematicsClient_Expecter) GetLatestTelemetry(ctx interface{}, carID interface{}) *MockTelematicsClient_GetLatestTelemetry_Call {
	return &MockTelematicsClient_GetLatestTelemetry_Call{Call: _e.mock.On("GetLatestTelemetry", ctx, carID)}
}

func (_c *MockTelematicsClient_GetLatestTelemetry_Call) Run(run func(ctx context.Context, carID string)) *MockTelematicsClient_GetLatestTelemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTelematicsClient_GetLatestTelemetry_Call) Return(_a0 model.CarTelemetry, _a1 error) *MockTelematicsClient_GetLatestTelemetry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTelematicsClient_GetLatestTelemetry_Call) RunAndReturn(run func(context.Context, string) (model.CarTelemetry, error)) *MockTelematicsClient_GetLatestTelemetry_Call {
	_c.Call.Return(run)
	return _c
}

// StreamTelemetry provides a mock function with given fields: ctx, carID, fn
func (_m *MockTelematicsClient) StreamTelemetry(ctx context.Context, carID string, fn func(model.CarTelemetry) error) error {
	ret := _m.Called(ctx, carID, fn)

	if len(ret) == 0 {
		panic("no return value specified for StreamTelemetry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(model.CarTelemetry) error) error); ok {
		r0 = rf(ctx, carID, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTelematicsClient_StreamTelemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamTelemetry'
type MockTelematicsClient_StreamTelemetry_Call struct {
	*mock.Call
}

// StreamTelemetry is a helper method to define mock.On call
//   - ctx context.Context
//   - carID string
//   - fn func(model.CarTelemetry) error
func (_e *MockTelematicsClient_Expecter) StreamTelemetry(ctx interface{}, carID interface{}, fn interface{}) *MockTelematicsClient_StreamTelemetry_Call {
	return &MockTelematicsClient_StreamTelemetry_Call{Call: _e.mock.On("StreamTelemetry", ctx, carID, fn)}
}

func (_c *MockTelematicsClient_StreamTelemetry_Call) Run(run func(ctx context.Context, carID string, fn func(model.CarTelemetry) error)) *MockTelematicsClient_StreamTelemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(model.CarTelemetry) error))
	})
	return _c
}

func (_c *MockTelematicsClient_StreamTelemetry_Call) Return(_a0 error) *MockTelematicsClient_StreamTelemetry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTelematicsClient_StreamTelemetry_Call) RunAndReturn(run func(context.Context, string, func(model.CarTelemetry) error) error) *MockTelematicsClient_StreamTelemetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTelematicsClient creates a new instance of MockTelematicsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelematicsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelematicsClient {
	mock := &MockTelematicsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
