// Code generated by mockery. DO NOT EDIT.

package svcmocks

import (
	context "context"

	model "carsharing/trip-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTripRepository is an autogenerated mock type for the TripRepository type
type MockTripRepository struct {
	mock.Mock
}

type MockTripRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripRepository) EXPECT() *MockTripRepository_Expecter {
	return &MockTripRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, trip
func (_m *MockTripRepository) Create(ctx context.Context, trip model.TripCreate) (model.Trip, error) {
	ret := _m.Called(ctx, trip)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TripCreate) (model.Trip, error)); ok {
		return rf(ctx, trip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TripCreate) model.Trip); ok {
		r0 = rf(ctx, trip)
	} else {
		r0 = ret.Get(0).(model.Trip)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TripCreate) error); ok {
		r1 = rf(ctx, trip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTripRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - trip model.TripCreate
func (_e *MockTripRepository_Expecter) Create(ctx interface{}, trip interface{}) *MockTripRepository_Create_Call {
	return &MockTripRepository_Create_Call{Call: _e.mock.On("Create", ctx, trip)}
}

func (_c *MockTripRepository_Create_Call) Run(run func(ctx context.Context, trip model.TripCreate)) *MockTripRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TripCreate))
	})
	return _c
}

func (_c *MockTripRepository_Create_Call) Return(_a0 model.Trip, _a1 error) *MockTripRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripRepository_Create_Call) RunAndReturn(run func(context.Context, model.TripCreate) (model.Trip, error)) *MockTripRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTripRepository) GetByID(ctx context.Context, id string) (model.Trip, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Trip, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Trip); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Trip)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTripRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTripRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTripRepository_GetByID_Call {
	return &MockTripRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTripRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockTripRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripRepository_GetByID_Call) Return(_a0 model.Trip, _a1 error) *MockTripRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (model.Trip, error)) *MockTripRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockTripRepository) List(ctx context.Context, filter model.TripFilter) ([]model.Trip, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TripFilter) ([]model.Trip, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TripFilter) []model.Trip); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TripFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTripRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.TripFilter
func (_e *MockTripRepository_Expecter) List(ctx interface{}, filter interface{}) *MockTripRepository_List_Call {
	return &MockTripRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockTripRepository_List_Call) Run(run func(ctx context.Context, filter model.TripFilter)) *MockTripRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TripFilter))
	})
	return _c
}

func (_c *MockTripRepository_List_Call) Return(_a0 []model.Trip, _a1 error) *MockTripRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripRepository_List_Call) RunAndReturn(run func(context.Context, model.TripFilter) ([]model.Trip, error)) *MockTripRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *MockTripRepository) Update(ctx context.Context, id string, update model.TripUpdate) (model.Trip, error) {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.TripUpdate) (model.Trip, error)); ok {
		return rf(ctx, id, update)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.TripUpdate) model.Trip); ok {
		r0 = rf(ctx, id, update)
	} else {
		r0 = ret.Get(0).(model.Trip)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.TripUpdate) error); ok {
		r1 = rf(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTripRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update model.TripUpdate
func (_e *MockTripRepository_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *MockTripRepository_Update_Call {
	return &MockTripRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockTripRepository_Update_Call) Run(run func(ctx context.Context, id string, update model.TripUpdate)) *MockTripRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.TripUpdate))
	})
	return _c
}

func (_c *MockTripRepository_Update_Call) Return(_a0 model.Trip, _a1 error) *MockTripRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripRepository_Update_Call) RunAndReturn(run func(context.Context, string, model.TripUpdate) (model.Trip, error)) *MockTripRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripRepository creates a new instance of MockTripRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripRepository {
	mock := &MockTripRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
