// Code generated by mockery. DO NOT EDIT.

package svcmocks

import (
	context "context"

	model "github.com/sorawaslocked/car-rental-trip-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTripSummaryRepository is an autogenerated mock type for the TripSummaryRepository type
type MockTripSummaryRepository struct {
	mock.Mock
}

type MockTripSummaryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripSummaryRepository) EXPECT() *MockTripSummaryRepository_Expecter {
	return &MockTripSummaryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, summary
func (_m *MockTripSummaryRepository) Create(ctx context.Context, summary model.TripSummaryCreate) (model.TripSummary, error) {
	ret := _m.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.TripSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TripSummaryCreate) (model.TripSummary, error)); ok {
		return rf(ctx, summary)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TripSummaryCreate) model.TripSummary); ok {
		r0 = rf(ctx, summary)
	} else {
		r0 = ret.Get(0).(model.TripSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TripSummaryCreate) error); ok {
		r1 = rf(ctx, summary)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripSummaryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTripSummaryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - summary model.TripSummaryCreate
func (_e *MockTripSummaryRepository_Expecter) Create(ctx interface{}, summary interface{}) *MockTripSummaryRepository_Create_Call {
	return &MockTripSummaryRepository_Create_Call{Call: _e.mock.On("Create", ctx, summary)}
}

func (_c *MockTripSummaryRepository_Create_Call) Run(run func(ctx context.Context, summary model.TripSummaryCreate)) *MockTripSummaryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TripSummaryCreate))
	})
	return _c
}

func (_c *MockTripSummaryRepository_Create_Call) Return(_a0 model.TripSummary, _a1 error) *MockTripSummaryRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripSummaryRepository_Create_Call) RunAndReturn(run func(context.Context, model.TripSummaryCreate) (model.TripSummary, error)) *MockTripSummaryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTripID provides a mock function with given fields: ctx, tripID
func (_m *MockTripSummaryRepository) GetByTripID(ctx context.Context, tripID string) (model.TripSummary, error) {
	ret := _m.Called(ctx, tripID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTripID")
	}

	var r0 model.TripSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.TripSummary, error)); ok {
		return rf(ctx, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.TripSummary); ok {
		r0 = rf(ctx, tripID)
	} else {
		r0 = ret.Get(0).(model.TripSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripSummaryRepository_GetByTripID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTripID'
type MockTripSummaryRepository_GetByTripID_Call struct {
	*mock.Call
}

// GetByTripID is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
func (_e *MockTripSummaryRepository_Expecter) GetByTripID(ctx interface{}, tripID interface{}) *MockTripSummaryRepository_GetByTripID_Call {
	return &MockTripSummaryRepository_GetByTripID_Call{Call: _e.mock.On("GetByTripID", ctx, tripID)}
}

func (_c *MockTripSummaryRepository_GetByTripID_Call) Run(run func(ctx context.Context, tripID string)) *MockTripSummaryRepository_GetByTripID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripSummaryRepository_GetByTripID_Call) Return(_a0 model.TripSummary, _a1 error) *MockTripSummaryRepository_GetByTripID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripSummaryRepository_GetByTripID_Call) RunAndReturn(run func(context.Context, string) (model.TripSummary, error)) *MockTripSummaryRepository_GetByTripID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripSummaryRepository creates a new instance of MockTripSummaryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripSummaryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripSummaryRepository {
	mock := &MockTripSummaryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
