env: "dev"

http_server:
  host: "0.0.0.0"
  port: 4000
  cookie:
    secure: true
  cors:
    allow_origins:
      - "http://localhost:5173"
      - "http://localhost:5175"
    allow_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "OPTIONS"
    allow_headers:
      - "Origin"
      - "Content-Type"
      - "Accept"
      - "Authorization"
      - "X-Device-Id"
    expose_headers:
      - "Content-Length"
    allow_credentials: true
    max_age: 12h

grpc_server:
  user_service:
    host: "user-service"
    port: 9999
  car_service:
    host: "car-service"
    port: 9998
  booking_service:
    host: "booking-service"
    port: 9997
  trip_service:
    host: "trip-service"
    port: 9996

nats:
  urls:
    - "nats://nats:4222"
  name: "api-gateway"
  username: ""
  password: ""

redis:
  host: "redis"
  port: 6379
  username: ""
  password: ""
