// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "carsharing/user-service/internal/model"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CheckActivationCode provides a mock function with given fields: ctx, code
func (_m *MockUserService) CheckActivationCode(ctx context.Context, code string) error {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for CheckActivationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_CheckActivationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckActivationCode'
type MockUserService_CheckActivationCode_Call struct {
	*mock.Call
}

// CheckActivationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockUserService_Expecter) CheckActivationCode(ctx interface{}, code interface{}) *MockUserService_CheckActivationCode_Call {
	return &MockUserService_CheckActivationCode_Call{Call: _e.mock.On("CheckActivationCode", ctx, code)}
}

func (_c *MockUserService_CheckActivationCode_Call) Run(run func(ctx context.Context, code string)) *MockUserService_CheckActivationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_CheckActivationCode_Call) Return(_a0 error) *MockUserService_CheckActivationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_CheckActivationCode_Call) RunAndReturn(run func(context.Context, string) error) *MockUserService_CheckActivationCode_Call {
	_c.Call.Return(run)
	return _c
}

// CheckDocument provides a mock function with given fields: ctx, docID, status, docError
func (_m *MockUserService) CheckDocument(ctx context.Context, docID string, status model.DocumentStatus, docError *string) error {
	ret := _m.Called(ctx, docID, status, docError)

	if len(ret) == 0 {
		panic("no return value specified for CheckDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.DocumentStatus, *string) error); ok {
		r0 = rf(ctx, docID, status, docError)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_CheckDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckDocument'
type MockUserService_CheckDocument_Call struct {
	*mock.Call
}

// CheckDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
//   - status model.DocumentStatus
//   - docError *string
func (_e *MockUserService_Expecter) CheckDocument(ctx interface{}, docID interface{}, status interface{}, docError interface{}) *MockUserService_CheckDocument_Call {
	return &MockUserService_CheckDocument_Call{Call: _e.mock.On("CheckDocument", ctx, docID, status, docError)}
}

func (_c *MockUserService_CheckDocument_Call) Run(run func(ctx context.Context, docID string, status model.DocumentStatus, docError *string)) *MockUserService_CheckDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.DocumentStatus), args[3].(*string))
	})
	return _c
}

func (_c *MockUserService_CheckDocument_Call) Return(_a0 error) *MockUserService_CheckDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_CheckDocument_Call) RunAndReturn(run func(context.Context, string, model.DocumentStatus, *string) error) *MockUserService_CheckDocument_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, data
func (_m *MockUserService) Create(ctx context.Context, data model.UserCreate) (string, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UserCreate) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.UserCreate) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.UserCreate) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data model.UserCreate
func (_e *MockUserService_Expecter) Create(ctx interface{}, data interface{}) *MockUserService_Create_Call {
	return &MockUserService_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *MockUserService_Create_Call) Run(run func(ctx context.Context, data model.UserCreate)) *MockUserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UserCreate))
	})
	return _c
}

func (_c *MockUserService_Create_Call) Return(_a0 string, _a1 error) *MockUserService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Create_Call) RunAndReturn(run func(context.Context, model.UserCreate) (string, error)) *MockUserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDocument provides a mock function with given fields: ctx, objectKey, imageType
func (_m *MockUserService) CreateDocument(ctx context.Context, objectKey string, imageType model.ImageType) (string, error) {
	ret := _m.Called(ctx, objectKey, imageType)

	if len(ret) == 0 {
		panic("no return value specified for CreateDocument")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ImageType) (string, error)); ok {
		return rf(ctx, objectKey, imageType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ImageType) string); ok {
		r0 = rf(ctx, objectKey, imageType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, model.ImageType) error); ok {
		r1 = rf(ctx, objectKey, imageType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_CreateDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDocument'
type MockUserService_CreateDocument_Call struct {
	*mock.Call
}

// CreateDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
//   - imageType model.ImageType
func (_e *MockUserService_Expecter) CreateDocument(ctx interface{}, objectKey interface{}, imageType interface{}) *MockUserService_CreateDocument_Call {
	return &MockUserService_CreateDocument_Call{Call: _e.mock.On("CreateDocument", ctx, objectKey, imageType)}
}

func (_c *MockUserService_CreateDocument_Call) Run(run func(ctx context.Context, objectKey string, imageType model.ImageType)) *MockUserService_CreateDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.ImageType))
	})
	return _c
}

func (_c *MockUserService_CreateDocument_Call) Return(_a0 string, _a1 error) *MockUserService_CreateDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_CreateDocument_Call) RunAndReturn(run func(context.Context, string, model.ImageType) (string, error)) *MockUserService_CreateDocument_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserService_Expecter) Delete(ctx interface{}, id interface{}) *MockUserService_Delete_Call {
	return &MockUserService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockUserService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_Delete_Call) Return(_a0 error) *MockUserService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockUserService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockUserService) Get(ctx context.Context, id string) (model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserService_Expecter) Get(ctx interface{}, id interface{}) *MockUserService_Get_Call {
	return &MockUserService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUserService_Get_Call) Run(run func(ctx context.Context, id string)) *MockUserService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_Get_Call) Return(_a0 model.User, _a1 error) *MockUserService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Get_Call) RunAndReturn(run func(context.Context, string) (model.User, error)) *MockUserService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentImageUploadData provides a mock function with given fields: ctx, imageType
func (_m *MockUserService) GetDocumentImageUploadData(ctx context.Context, imageType string) (model.ImageUploadData, error) {
	ret := _m.Called(ctx, imageType)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentImageUploadData")
	}

	var r0 model.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.ImageUploadData, error)); ok {
		return rf(ctx, imageType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.ImageUploadData); ok {
		r0 = rf(ctx, imageType)
	} else {
		r0 = ret.Get(0).(model.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, imageType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetDocumentImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentImageUploadData'
type MockUserService_GetDocumentImageUploadData_Call struct {
	*mock.Call
}

// GetDocumentImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
//   - imageType string
func (_e *MockUserService_Expecter) GetDocumentImageUploadData(ctx interface{}, imageType interface{}) *MockUserService_GetDocumentImageUploadData_Call {
	return &MockUserService_GetDocumentImageUploadData_Call{Call: _e.mock.On("GetDocumentImageUploadData", ctx, imageType)}
}

func (_c *MockUserService_GetDocumentImageUploadData_Call) Run(run func(ctx context.Context, imageType string)) *MockUserService_GetDocumentImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetDocumentImageUploadData_Call) Return(_a0 model.ImageUploadData, _a1 error) *MockUserService_GetDocumentImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetDocumentImageUploadData_Call) RunAndReturn(run func(context.Context, string) (model.ImageUploadData, error)) *MockUserService_GetDocumentImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// GetProcessedDocumentsForUser provides a mock function with given fields: ctx, userID
func (_m *MockUserService) GetProcessedDocumentsForUser(ctx context.Context, userID string) ([]model.Document, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProcessedDocumentsForUser")
	}

	var r0 []model.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Document, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Document); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetProcessedDocumentsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProcessedDocumentsForUser'
type MockUserService_GetProcessedDocumentsForUser_Call struct {
	*mock.Call
}

// GetProcessedDocumentsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserService_Expecter) GetProcessedDocumentsForUser(ctx interface{}, userID interface{}) *MockUserService_GetProcessedDocumentsForUser_Call {
	return &MockUserService_GetProcessedDocumentsForUser_Call{Call: _e.mock.On("GetProcessedDocumentsForUser", ctx, userID)}
}

func (_c *MockUserService_GetProcessedDocumentsForUser_Call) Run(run func(ctx context.Context, userID string)) *MockUserService_GetProcessedDocumentsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetProcessedDocumentsForUser_Call) Return(_a0 []model.Document, _a1 error) *MockUserService_GetProcessedDocumentsForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetProcessedDocumentsForUser_Call) RunAndReturn(run func(context.Context, string) ([]model.Document, error)) *MockUserService_GetProcessedDocumentsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserProfileImageUploadData provides a mock function with given fields: ctx
func (_m *MockUserService) GetUserProfileImageUploadData(ctx context.Context) (model.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfileImageUploadData")
	}

	var r0 model.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetUserProfileImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfileImageUploadData'
type MockUserService_GetUserProfileImageUploadData_Call struct {
	*mock.Call
}

// GetUserProfileImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserService_Expecter) GetUserProfileImageUploadData(ctx interface{}) *MockUserService_GetUserProfileImageUploadData_Call {
	return &MockUserService_GetUserProfileImageUploadData_Call{Call: _e.mock.On("GetUserProfileImageUploadData", ctx)}
}

func (_c *MockUserService_GetUserProfileImageUploadData_Call) Run(run func(ctx context.Context)) *MockUserService_GetUserProfileImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserService_GetUserProfileImageUploadData_Call) Return(_a0 model.ImageUploadData, _a1 error) *MockUserService_GetUserProfileImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetUserProfileImageUploadData_Call) RunAndReturn(run func(context.Context) (model.ImageUploadData, error)) *MockUserService_GetUserProfileImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockUserService) List(ctx context.Context, filter model.UserFilter) ([]model.User, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UserFilter) ([]model.User, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.UserFilter) []model.User); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.UserFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.UserFilter
func (_e *MockUserService_Expecter) List(ctx interface{}, filter interface{}) *MockUserService_List_Call {
	return &MockUserService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockUserService_List_Call) Run(run func(ctx context.Context, filter model.UserFilter)) *MockUserService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UserFilter))
	})
	return _c
}

func (_c *MockUserService_List_Call) Return(_a0 []model.User, _a1 error) *MockUserService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_List_Call) RunAndReturn(run func(context.Context, model.UserFilter) ([]model.User, error)) *MockUserService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, data
func (_m *MockUserService) Register(ctx context.Context, data model.UserCreate) (string, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UserCreate) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.UserCreate) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.UserCreate) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - data model.UserCreate
func (_e *MockUserService_Expecter) Register(ctx interface{}, data interface{}) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", ctx, data)}
}

func (_c *MockUserService_Register_Call) Run(run func(ctx context.Context, data model.UserCreate)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UserCreate))
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(_a0 string, _a1 error) *MockUserService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(context.Context, model.UserCreate) (string, error)) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SendActivationCode provides a mock function with given fields: ctx
func (_m *MockUserService) SendActivationCode(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SendActivationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_SendActivationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendActivationCode'
type MockUserService_SendActivationCode_Call struct {
	*mock.Call
}

// SendActivationCode is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserService_Expecter) SendActivationCode(ctx interface{}) *MockUserService_SendActivationCode_Call {
	return &MockUserService_SendActivationCode_Call{Call: _e.mock.On("SendActivationCode", ctx)}
}

func (_c *MockUserService_SendActivationCode_Call) Run(run func(ctx context.Context)) *MockUserService_SendActivationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserService_SendActivationCode_Call) Return(_a0 error) *MockUserService_SendActivationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_SendActivationCode_Call) RunAndReturn(run func(context.Context) error) *MockUserService_SendActivationCode_Call {
	_c.Call.Return(run)
	return _c
}

// SignIn provides a mock function with given fields: ctx, creds
func (_m *MockUserService) SignIn(ctx context.Context, creds model.Credentials) (string, error) {
	ret := _m.Called(ctx, creds)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Credentials) (string, error)); ok {
		return rf(ctx, creds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Credentials) string); ok {
		r0 = rf(ctx, creds)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Credentials) error); ok {
		r1 = rf(ctx, creds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type MockUserService_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - ctx context.Context
//   - creds model.Credentials
func (_e *MockUserService_Expecter) SignIn(ctx interface{}, creds interface{}) *MockUserService_SignIn_Call {
	return &MockUserService_SignIn_Call{Call: _e.mock.On("SignIn", ctx, creds)}
}

func (_c *MockUserService_SignIn_Call) Run(run func(ctx context.Context, creds model.Credentials)) *MockUserService_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Credentials))
	})
	return _c
}

func (_c *MockUserService_SignIn_Call) Return(_a0 string, _a1 error) *MockUserService_SignIn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_SignIn_Call) RunAndReturn(run func(context.Context, model.Credentials) (string, error)) *MockUserService_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, data
func (_m *MockUserService) Update(ctx context.Context, id string, data model.UserUpdate) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UserUpdate) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data model.UserUpdate
func (_e *MockUserService_Expecter) Update(ctx interface{}, id interface{}, data interface{}) *MockUserService_Update_Call {
	return &MockUserService_Update_Call{Call: _e.mock.On("Update", ctx, id, data)}
}

func (_c *MockUserService_Update_Call) Run(run func(ctx context.Context, id string, data model.UserUpdate)) *MockUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.UserUpdate))
	})
	return _c
}

func (_c *MockUserService_Update_Call) Return(_a0 error) *MockUserService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserService_Update_Call) RunAndReturn(run func(context.Context, string, model.UserUpdate) error) *MockUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
