// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/car-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCarInsuranceRepository is an autogenerated mock type for the CarInsuranceRepository type
type MockCarInsuranceRepository struct {
	mock.Mock
}

type MockCarInsuranceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarInsuranceRepository) EXPECT() *MockCarInsuranceRepository_Expecter {
	return &MockCarInsuranceRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCarInsuranceRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarInsuranceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCarInsuranceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarInsuranceRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCarInsuranceRepository_Delete_Call {
	return &MockCarInsuranceRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCarInsuranceRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCarInsuranceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarInsuranceRepository_Delete_Call) Return(_a0 error) *MockCarInsuranceRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarInsuranceRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCarInsuranceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockCarInsuranceRepository) Find(ctx context.Context, filter model.CarInsuranceFilter) ([]model.CarInsurance, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.CarInsurance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarInsuranceFilter) ([]model.CarInsurance, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarInsuranceFilter) []model.CarInsurance); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarInsurance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarInsuranceFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarInsuranceRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCarInsuranceRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.CarInsuranceFilter
func (_e *MockCarInsuranceRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockCarInsuranceRepository_Find_Call {
	return &MockCarInsuranceRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockCarInsuranceRepository_Find_Call) Run(run func(ctx context.Context, filter model.CarInsuranceFilter)) *MockCarInsuranceRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarInsuranceFilter))
	})
	return _c
}

func (_c *MockCarInsuranceRepository_Find_Call) Return(_a0 []model.CarInsurance, _a1 error) *MockCarInsuranceRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarInsuranceRepository_Find_Call) RunAndReturn(run func(context.Context, model.CarInsuranceFilter) ([]model.CarInsurance, error)) *MockCarInsuranceRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCarInsuranceRepository) FindByID(ctx context.Context, id string) (model.CarInsurance, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.CarInsurance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CarInsurance, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CarInsurance); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.CarInsurance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarInsuranceRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCarInsuranceRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarInsuranceRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCarInsuranceRepository_FindByID_Call {
	return &MockCarInsuranceRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCarInsuranceRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockCarInsuranceRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarInsuranceRepository_FindByID_Call) Return(_a0 model.CarInsurance, _a1 error) *MockCarInsuranceRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarInsuranceRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (model.CarInsurance, error)) *MockCarInsuranceRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, insurance
func (_m *MockCarInsuranceRepository) Insert(ctx context.Context, insurance model.CarInsurance) (string, error) {
	ret := _m.Called(ctx, insurance)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarInsurance) (string, error)); ok {
		return rf(ctx, insurance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarInsurance) string); ok {
		r0 = rf(ctx, insurance)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarInsurance) error); ok {
		r1 = rf(ctx, insurance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarInsuranceRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCarInsuranceRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - insurance model.CarInsurance
func (_e *MockCarInsuranceRepository_Expecter) Insert(ctx interface{}, insurance interface{}) *MockCarInsuranceRepository_Insert_Call {
	return &MockCarInsuranceRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, insurance)}
}

func (_c *MockCarInsuranceRepository_Insert_Call) Run(run func(ctx context.Context, insurance model.CarInsurance)) *MockCarInsuranceRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarInsurance))
	})
	return _c
}

func (_c *MockCarInsuranceRepository_Insert_Call) Return(_a0 string, _a1 error) *MockCarInsuranceRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarInsuranceRepository_Insert_Call) RunAndReturn(run func(context.Context, model.CarInsurance) (string, error)) *MockCarInsuranceRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *MockCarInsuranceRepository) Update(ctx context.Context, id string, update model.CarInsuranceUpdate) error {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarInsuranceUpdate) error); ok {
		r0 = rf(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarInsuranceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarInsuranceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update model.CarInsuranceUpdate
func (_e *MockCarInsuranceRepository_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *MockCarInsuranceRepository_Update_Call {
	return &MockCarInsuranceRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockCarInsuranceRepository_Update_Call) Run(run func(ctx context.Context, id string, update model.CarInsuranceUpdate)) *MockCarInsuranceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarInsuranceUpdate))
	})
	return _c
}

func (_c *MockCarInsuranceRepository_Update_Call) Return(_a0 error) *MockCarInsuranceRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarInsuranceRepository_Update_Call) RunAndReturn(run func(context.Context, string, model.CarInsuranceUpdate) error) *MockCarInsuranceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarInsuranceRepository creates a new instance of MockCarInsuranceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarInsuranceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarInsuranceRepository {
	mock := &MockCarInsuranceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
