// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sorawaslocked/car-rental-car-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCarModelRepository is an autogenerated mock type for the CarModelRepository type
type MockCarModelRepository struct {
	mock.Mock
}

type MockCarModelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarModelRepository) EXPECT() *MockCarModelRepository_Expecter {
	return &MockCarModelRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCarModelRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarModelRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCarModelRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarModelRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCarModelRepository_Delete_Call {
	return &MockCarModelRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCarModelRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCarModelRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarModelRepository_Delete_Call) Return(_a0 error) *MockCarModelRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarModelRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCarModelRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockCarModelRepository) Find(ctx context.Context, filter model.CarModelFilter) ([]model.CarModel, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.CarModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarModelFilter) ([]model.CarModel, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarModelFilter) []model.CarModel); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarModelFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarModelRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCarModelRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.CarModelFilter
func (_e *MockCarModelRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockCarModelRepository_Find_Call {
	return &MockCarModelRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockCarModelRepository_Find_Call) Run(run func(ctx context.Context, filter model.CarModelFilter)) *MockCarModelRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarModelFilter))
	})
	return _c
}

func (_c *MockCarModelRepository_Find_Call) Return(_a0 []model.CarModel, _a1 error) *MockCarModelRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarModelRepository_Find_Call) RunAndReturn(run func(context.Context, model.CarModelFilter) ([]model.CarModel, error)) *MockCarModelRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCarModelRepository) FindByID(ctx context.Context, id string) (model.CarModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.CarModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CarModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CarModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.CarModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarModelRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCarModelRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarModelRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCarModelRepository_FindByID_Call {
	return &MockCarModelRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCarModelRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockCarModelRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarModelRepository_FindByID_Call) Return(_a0 model.CarModel, _a1 error) *MockCarModelRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarModelRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (model.CarModel, error)) *MockCarModelRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, carModel
func (_m *MockCarModelRepository) Insert(ctx context.Context, carModel model.CarModel) (string, error) {
	ret := _m.Called(ctx, carModel)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarModel) (string, error)); ok {
		return rf(ctx, carModel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarModel) string); ok {
		r0 = rf(ctx, carModel)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarModel) error); ok {
		r1 = rf(ctx, carModel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarModelRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCarModelRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - carModel model.CarModel
func (_e *MockCarModelRepository_Expecter) Insert(ctx interface{}, carModel interface{}) *MockCarModelRepository_Insert_Call {
	return &MockCarModelRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, carModel)}
}

func (_c *MockCarModelRepository_Insert_Call) Run(run func(ctx context.Context, carModel model.CarModel)) *MockCarModelRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarModel))
	})
	return _c
}

func (_c *MockCarModelRepository_Insert_Call) Return(_a0 string, _a1 error) *MockCarModelRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarModelRepository_Insert_Call) RunAndReturn(run func(context.Context, model.CarModel) (string, error)) *MockCarModelRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *MockCarModelRepository) Update(ctx context.Context, id string, update model.CarModelUpdate) error {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarModelUpdate) error); ok {
		r0 = rf(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarModelRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarModelRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update model.CarModelUpdate
func (_e *MockCarModelRepository_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *MockCarModelRepository_Update_Call {
	return &MockCarModelRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockCarModelRepository_Update_Call) Run(run func(ctx context.Context, id string, update model.CarModelUpdate)) *MockCarModelRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarModelUpdate))
	})
	return _c
}

func (_c *MockCarModelRepository_Update_Call) Return(_a0 error) *MockCarModelRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarModelRepository_Update_Call) RunAndReturn(run func(context.Context, string, model.CarModelUpdate) error) *MockCarModelRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarModelRepository creates a new instance of MockCarModelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarModelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarModelRepository {
	mock := &MockCarModelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
