// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/car-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockObjectStorage is an autogenerated mock type for the ObjectStorage type
type MockObjectStorage struct {
	mock.Mock
}

type MockObjectStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStorage) EXPECT() *MockObjectStorage_Expecter {
	return &MockObjectStorage_Expecter{mock: &_m.Mock}
}

// GetCarImageUploadData provides a mock function with given fields: ctx
func (_m *MockObjectStorage) GetCarImageUploadData(ctx context.Context) (model.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCarImageUploadData")
	}

	var r0 model.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStorage_GetCarImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCarImageUploadData'
type MockObjectStorage_GetCarImageUploadData_Call struct {
	*mock.Call
}

// GetCarImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockObjectStorage_Expecter) GetCarImageUploadData(ctx interface{}) *MockObjectStorage_GetCarImageUploadData_Call {
	return &MockObjectStorage_GetCarImageUploadData_Call{Call: _e.mock.On("GetCarImageUploadData", ctx)}
}

func (_c *MockObjectStorage_GetCarImageUploadData_Call) Run(run func(ctx context.Context)) *MockObjectStorage_GetCarImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockObjectStorage_GetCarImageUploadData_Call) Return(_a0 model.ImageUploadData, _a1 error) *MockObjectStorage_GetCarImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStorage_GetCarImageUploadData_Call) RunAndReturn(run func(context.Context) (model.ImageUploadData, error)) *MockObjectStorage_GetCarImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// GetCarModelImageUploadData provides a mock function with given fields: ctx
func (_m *MockObjectStorage) GetCarModelImageUploadData(ctx context.Context) (model.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCarModelImageUploadData")
	}

	var r0 model.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStorage_GetCarModelImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCarModelImageUploadData'
type MockObjectStorage_GetCarModelImageUploadData_Call struct {
	*mock.Call
}

// GetCarModelImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockObjectStorage_Expecter) GetCarModelImageUploadData(ctx interface{}) *MockObjectStorage_GetCarModelImageUploadData_Call {
	return &MockObjectStorage_GetCarModelImageUploadData_Call{Call: _e.mock.On("GetCarModelImageUploadData", ctx)}
}

func (_c *MockObjectStorage_GetCarModelImageUploadData_Call) Run(run func(ctx context.Context)) *MockObjectStorage_GetCarModelImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockObjectStorage_GetCarModelImageUploadData_Call) Return(_a0 model.ImageUploadData, _a1 error) *MockObjectStorage_GetCarModelImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStorage_GetCarModelImageUploadData_Call) RunAndReturn(run func(context.Context) (model.ImageUploadData, error)) *MockObjectStorage_GetCarModelImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// GetInsuranceImageUploadData provides a mock function with given fields: ctx
func (_m *MockObjectStorage) GetInsuranceImageUploadData(ctx context.Context) (model.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetInsuranceImageUploadData")
	}

	var r0 model.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStorage_GetInsuranceImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInsuranceImageUploadData'
type MockObjectStorage_GetInsuranceImageUploadData_Call struct {
	*mock.Call
}

// GetInsuranceImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockObjectStorage_Expecter) GetInsuranceImageUploadData(ctx interface{}) *MockObjectStorage_GetInsuranceImageUploadData_Call {
	return &MockObjectStorage_GetInsuranceImageUploadData_Call{Call: _e.mock.On("GetInsuranceImageUploadData", ctx)}
}

func (_c *MockObjectStorage_GetInsuranceImageUploadData_Call) Run(run func(ctx context.Context)) *MockObjectStorage_GetInsuranceImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockObjectStorage_GetInsuranceImageUploadData_Call) Return(_a0 model.ImageUploadData, _a1 error) *MockObjectStorage_GetInsuranceImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStorage_GetInsuranceImageUploadData_Call) RunAndReturn(run func(context.Context) (model.ImageUploadData, error)) *MockObjectStorage_GetInsuranceImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaintenanceReceiptImageUploadData provides a mock function with given fields: ctx
func (_m *MockObjectStorage) GetMaintenanceReceiptImageUploadData(ctx context.Context) (model.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMaintenanceReceiptImageUploadData")
	}

	var r0 model.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStorage_GetMaintenanceReceiptImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaintenanceReceiptImageUploadData'
type MockObjectStorage_GetMaintenanceReceiptImageUploadData_Call struct {
	*mock.Call
}

// GetMaintenanceReceiptImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockObjectStorage_Expecter) GetMaintenanceReceiptImageUploadData(ctx interface{}) *MockObjectStorage_GetMaintenanceReceiptImageUploadData_Call {
	return &MockObjectStorage_GetMaintenanceReceiptImageUploadData_Call{Call: _e.mock.On("GetMaintenanceReceiptImageUploadData", ctx)}
}

func (_c *MockObjectStorage_GetMaintenanceReceiptImageUploadData_Call) Run(run func(ctx context.Context)) *MockObjectStorage_GetMaintenanceReceiptImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockObjectStorage_GetMaintenanceReceiptImageUploadData_Call) Return(_a0 model.ImageUploadData, _a1 error) *MockObjectStorage_GetMaintenanceReceiptImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStorage_GetMaintenanceReceiptImageUploadData_Call) RunAndReturn(run func(context.Context) (model.ImageUploadData, error)) *MockObjectStorage_GetMaintenanceReceiptImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedURL provides a mock function with given fields: ctx, key
func (_m *MockObjectStorage) GetPresignedURL(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStorage_GetPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedURL'
type MockObjectStorage_GetPresignedURL_Call struct {
	*mock.Call
}

// GetPresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStorage_Expecter) GetPresignedURL(ctx interface{}, key interface{}) *MockObjectStorage_GetPresignedURL_Call {
	return &MockObjectStorage_GetPresignedURL_Call{Call: _e.mock.On("GetPresignedURL", ctx, key)}
}

func (_c *MockObjectStorage_GetPresignedURL_Call) Run(run func(ctx context.Context, key string)) *MockObjectStorage_GetPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockObjectStorage_GetPresignedURL_Call) Return(_a0 string, _a1 error) *MockObjectStorage_GetPresignedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStorage_GetPresignedURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockObjectStorage_GetPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStorage creates a new instance of MockObjectStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStorage {
	mock := &MockObjectStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
