// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishCarStatusUpdated provides a mock function with given fields: ctx, carID, fromStatus, toStatus
func (_m *MockEventPublisher) PublishCarStatusUpdated(ctx context.Context, carID string, fromStatus string, toStatus string) error {
	ret := _m.Called(ctx, carID, fromStatus, toStatus)

	if len(ret) == 0 {
		panic("no return value specified for PublishCarStatusUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, carID, fromStatus, toStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishCarStatusUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCarStatusUpdated'
type MockEventPublisher_PublishCarStatusUpdated_Call struct {
	*mock.Call
}

// PublishCarStatusUpdated is a helper method to define mock.On call
//   - ctx context.Context
//   - carID string
//   - fromStatus string
//   - toStatus string
func (_e *MockEventPublisher_Expecter) PublishCarStatusUpdated(ctx interface{}, carID interface{}, fromStatus interface{}, toStatus interface{}) *MockEventPublisher_PublishCarStatusUpdated_Call {
	return &MockEventPublisher_PublishCarStatusUpdated_Call{Call: _e.mock.On("PublishCarStatusUpdated", ctx, carID, fromStatus, toStatus)}
}

func (_c *MockEventPublisher_PublishCarStatusUpdated_Call) Run(run func(ctx context.Context, carID string, fromStatus string, toStatus string)) *MockEventPublisher_PublishCarStatusUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockEventPublisher_PublishCarStatusUpdated_Call) Return(_a0 error) *MockEventPublisher_PublishCarStatusUpdated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishCarStatusUpdated_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockEventPublisher_PublishCarStatusUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
