// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/car-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCarMaintenanceRecordRepository is an autogenerated mock type for the CarMaintenanceRecordRepository type
type MockCarMaintenanceRecordRepository struct {
	mock.Mock
}

type MockCarMaintenanceRecordRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarMaintenanceRecordRepository) EXPECT() *MockCarMaintenanceRecordRepository_Expecter {
	return &MockCarMaintenanceRecordRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockCarMaintenanceRecordRepository) Find(ctx context.Context, filter model.CarMaintenanceRecordFilter) ([]model.CarMaintenanceRecord, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.CarMaintenanceRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceRecordFilter) ([]model.CarMaintenanceRecord, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceRecordFilter) []model.CarMaintenanceRecord); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarMaintenanceRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarMaintenanceRecordFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceRecordRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCarMaintenanceRecordRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.CarMaintenanceRecordFilter
func (_e *MockCarMaintenanceRecordRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockCarMaintenanceRecordRepository_Find_Call {
	return &MockCarMaintenanceRecordRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockCarMaintenanceRecordRepository_Find_Call) Run(run func(ctx context.Context, filter model.CarMaintenanceRecordFilter)) *MockCarMaintenanceRecordRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarMaintenanceRecordFilter))
	})
	return _c
}

func (_c *MockCarMaintenanceRecordRepository_Find_Call) Return(_a0 []model.CarMaintenanceRecord, _a1 error) *MockCarMaintenanceRecordRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceRecordRepository_Find_Call) RunAndReturn(run func(context.Context, model.CarMaintenanceRecordFilter) ([]model.CarMaintenanceRecord, error)) *MockCarMaintenanceRecordRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCarMaintenanceRecordRepository) FindByID(ctx context.Context, id string) (model.CarMaintenanceRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.CarMaintenanceRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CarMaintenanceRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CarMaintenanceRecord); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.CarMaintenanceRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceRecordRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCarMaintenanceRecordRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarMaintenanceRecordRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCarMaintenanceRecordRepository_FindByID_Call {
	return &MockCarMaintenanceRecordRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCarMaintenanceRecordRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockCarMaintenanceRecordRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarMaintenanceRecordRepository_FindByID_Call) Return(_a0 model.CarMaintenanceRecord, _a1 error) *MockCarMaintenanceRecordRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceRecordRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (model.CarMaintenanceRecord, error)) *MockCarMaintenanceRecordRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, record
func (_m *MockCarMaintenanceRecordRepository) Insert(ctx context.Context, record model.CarMaintenanceRecord) (string, error) {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceRecord) (string, error)); ok {
		return rf(ctx, record)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceRecord) string); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarMaintenanceRecord) error); ok {
		r1 = rf(ctx, record)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceRecordRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCarMaintenanceRecordRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - record model.CarMaintenanceRecord
func (_e *MockCarMaintenanceRecordRepository_Expecter) Insert(ctx interface{}, record interface{}) *MockCarMaintenanceRecordRepository_Insert_Call {
	return &MockCarMaintenanceRecordRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, record)}
}

func (_c *MockCarMaintenanceRecordRepository_Insert_Call) Run(run func(ctx context.Context, record model.CarMaintenanceRecord)) *MockCarMaintenanceRecordRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarMaintenanceRecord))
	})
	return _c
}

func (_c *MockCarMaintenanceRecordRepository_Insert_Call) Return(_a0 string, _a1 error) *MockCarMaintenanceRecordRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceRecordRepository_Insert_Call) RunAndReturn(run func(context.Context, model.CarMaintenanceRecord) (string, error)) *MockCarMaintenanceRecordRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *MockCarMaintenanceRecordRepository) Update(ctx context.Context, id string, update model.CarMaintenanceRecordUpdate) error {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarMaintenanceRecordUpdate) error); ok {
		r0 = rf(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceRecordRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarMaintenanceRecordRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update model.CarMaintenanceRecordUpdate
func (_e *MockCarMaintenanceRecordRepository_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *MockCarMaintenanceRecordRepository_Update_Call {
	return &MockCarMaintenanceRecordRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockCarMaintenanceRecordRepository_Update_Call) Run(run func(ctx context.Context, id string, update model.CarMaintenanceRecordUpdate)) *MockCarMaintenanceRecordRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarMaintenanceRecordUpdate))
	})
	return _c
}

func (_c *MockCarMaintenanceRecordRepository_Update_Call) Return(_a0 error) *MockCarMaintenanceRecordRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceRecordRepository_Update_Call) RunAndReturn(run func(context.Context, string, model.CarMaintenanceRecordUpdate) error) *MockCarMaintenanceRecordRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithServiceState provides a mock function with given fields: ctx, id, update, state
func (_m *MockCarMaintenanceRecordRepository) UpdateWithServiceState(ctx context.Context, id string, update model.CarMaintenanceRecordUpdate, state model.CarServiceState) error {
	ret := _m.Called(ctx, id, update, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithServiceState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarMaintenanceRecordUpdate, model.CarServiceState) error); ok {
		r0 = rf(ctx, id, update, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceRecordRepository_UpdateWithServiceState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithServiceState'
type MockCarMaintenanceRecordRepository_UpdateWithServiceState_Call struct {
	*mock.Call
}

// UpdateWithServiceState is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update model.CarMaintenanceRecordUpdate
//   - state model.CarServiceState
func (_e *MockCarMaintenanceRecordRepository_Expecter) UpdateWithServiceState(ctx interface{}, id interface{}, update interface{}, state interface{}) *MockCarMaintenanceRecordRepository_UpdateWithServiceState_Call {
	return &MockCarMaintenanceRecordRepository_UpdateWithServiceState_Call{Call: _e.mock.On("UpdateWithServiceState", ctx, id, update, state)}
}

func (_c *MockCarMaintenanceRecordRepository_UpdateWithServiceState_Call) Run(run func(ctx context.Context, id string, update model.CarMaintenanceRecordUpdate, state model.CarServiceState)) *MockCarMaintenanceRecordRepository_UpdateWithServiceState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarMaintenanceRecordUpdate), args[3].(model.CarServiceState))
	})
	return _c
}

func (_c *MockCarMaintenanceRecordRepository_UpdateWithServiceState_Call) Return(_a0 error) *MockCarMaintenanceRecordRepository_UpdateWithServiceState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceRecordRepository_UpdateWithServiceState_Call) RunAndReturn(run func(context.Context, string, model.CarMaintenanceRecordUpdate, model.CarServiceState) error) *MockCarMaintenanceRecordRepository_UpdateWithServiceState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarMaintenanceRecordRepository creates a new instance of MockCarMaintenanceRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarMaintenanceRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarMaintenanceRecordRepository {
	mock := &MockCarMaintenanceRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
