// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sorawaslocked/car-rental-car-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCarServiceStateRepository is an autogenerated mock type for the CarServiceStateRepository type
type MockCarServiceStateRepository struct {
	mock.Mock
}

type MockCarServiceStateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarServiceStateRepository) EXPECT() *MockCarServiceStateRepository_Expecter {
	return &MockCarServiceStateRepository_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function with given fields: ctx, filter
func (_m *MockCarServiceStateRepository) FindAll(ctx context.Context, filter model.CarServiceStateFilter) ([]model.CarServiceState, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.CarServiceState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarServiceStateFilter) ([]model.CarServiceState, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarServiceStateFilter) []model.CarServiceState); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarServiceState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarServiceStateFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarServiceStateRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockCarServiceStateRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.CarServiceStateFilter
func (_e *MockCarServiceStateRepository_Expecter) FindAll(ctx interface{}, filter interface{}) *MockCarServiceStateRepository_FindAll_Call {
	return &MockCarServiceStateRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter)}
}

func (_c *MockCarServiceStateRepository_FindAll_Call) Run(run func(ctx context.Context, filter model.CarServiceStateFilter)) *MockCarServiceStateRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarServiceStateFilter))
	})
	return _c
}

func (_c *MockCarServiceStateRepository_FindAll_Call) Return(_a0 []model.CarServiceState, _a1 error) *MockCarServiceStateRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarServiceStateRepository_FindAll_Call) RunAndReturn(run func(context.Context, model.CarServiceStateFilter) ([]model.CarServiceState, error)) *MockCarServiceStateRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, state
func (_m *MockCarServiceStateRepository) Upsert(ctx context.Context, state model.CarServiceState) error {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarServiceState) error); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarServiceStateRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockCarServiceStateRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - state model.CarServiceState
func (_e *MockCarServiceStateRepository_Expecter) Upsert(ctx interface{}, state interface{}) *MockCarServiceStateRepository_Upsert_Call {
	return &MockCarServiceStateRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, state)}
}

func (_c *MockCarServiceStateRepository_Upsert_Call) Run(run func(ctx context.Context, state model.CarServiceState)) *MockCarServiceStateRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarServiceState))
	})
	return _c
}

func (_c *MockCarServiceStateRepository_Upsert_Call) Return(_a0 error) *MockCarServiceStateRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarServiceStateRepository_Upsert_Call) RunAndReturn(run func(context.Context, model.CarServiceState) error) *MockCarServiceStateRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarServiceStateRepository creates a new instance of MockCarServiceStateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarServiceStateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarServiceStateRepository {
	mock := &MockCarServiceStateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
