// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/car-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTelemetryReadingRepository is an autogenerated mock type for the TelemetryReadingRepository type
type MockTelemetryReadingRepository struct {
	mock.Mock
}

type MockTelemetryReadingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelemetryReadingRepository) EXPECT() *MockTelemetryReadingRepository_Expecter {
	return &MockTelemetryReadingRepository_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function with given fields: ctx, reading
func (_m *MockTelemetryReadingRepository) Insert(ctx context.Context, reading model.TelemetryReading) error {
	ret := _m.Called(ctx, reading)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TelemetryReading) error); ok {
		r0 = rf(ctx, reading)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTelemetryReadingRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockTelemetryReadingRepository_Insert_Call struct {
	*mock.Call
}

func (_e *MockTelemetryReadingRepository_Expecter) Insert(ctx interface{}, reading interface{}) *MockTelemetryReadingRepository_Insert_Call {
	return &MockTelemetryReadingRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, reading)}
}

func (_c *MockTelemetryReadingRepository_Insert_Call) Run(run func(ctx context.Context, reading model.TelemetryReading)) *MockTelemetryReadingRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TelemetryReading))
	})
	return _c
}

func (_c *MockTelemetryReadingRepository_Insert_Call) Return(_a0 error) *MockTelemetryReadingRepository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTelemetryReadingRepository_Insert_Call) RunAndReturn(run func(context.Context, model.TelemetryReading) error) *MockTelemetryReadingRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockTelemetryReadingRepository) Find(ctx context.Context, filter model.TelemetryReadingFilter) ([]model.TelemetryReading, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.TelemetryReading
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TelemetryReadingFilter) ([]model.TelemetryReading, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TelemetryReadingFilter) []model.TelemetryReading); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TelemetryReading)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TelemetryReadingFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTelemetryReadingRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockTelemetryReadingRepository_Find_Call struct {
	*mock.Call
}

func (_e *MockTelemetryReadingRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockTelemetryReadingRepository_Find_Call {
	return &MockTelemetryReadingRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockTelemetryReadingRepository_Find_Call) Run(run func(ctx context.Context, filter model.TelemetryReadingFilter)) *MockTelemetryReadingRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TelemetryReadingFilter))
	})
	return _c
}

func (_c *MockTelemetryReadingRepository_Find_Call) Return(_a0 []model.TelemetryReading, _a1 error) *MockTelemetryReadingRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTelemetryReadingRepository_Find_Call) RunAndReturn(run func(context.Context, model.TelemetryReadingFilter) ([]model.TelemetryReading, error)) *MockTelemetryReadingRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTelemetryReadingRepository creates a new instance of MockTelemetryReadingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelemetryReadingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelemetryReadingRepository {
	mock := &MockTelemetryReadingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
