// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/car-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockZoneRepository is an autogenerated mock type for the ZoneRepository type
type MockZoneRepository struct {
	mock.Mock
}

type MockZoneRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockZoneRepository) EXPECT() *MockZoneRepository_Expecter {
	return &MockZoneRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockZoneRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockZoneRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockZoneRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockZoneRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockZoneRepository_Delete_Call {
	return &MockZoneRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockZoneRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockZoneRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockZoneRepository_Delete_Call) Return(_a0 error) *MockZoneRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockZoneRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockZoneRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLocation provides a mock function with given fields: ctx, lat, lng
func (_m *MockZoneRepository) FindByLocation(ctx context.Context, lat float64, lng float64) (*model.Zone, error) {
	ret := _m.Called(ctx, lat, lng)

	if len(ret) == 0 {
		panic("no return value specified for FindByLocation")
	}

	var r0 *model.Zone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (*model.Zone, error)); ok {
		return rf(ctx, lat, lng)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) *model.Zone); ok {
		r0 = rf(ctx, lat, lng)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Zone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lat, lng)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZoneRepository_FindByLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLocation'
type MockZoneRepository_FindByLocation_Call struct {
	*mock.Call
}

// FindByLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - lat float64
//   - lng float64
func (_e *MockZoneRepository_Expecter) FindByLocation(ctx interface{}, lat interface{}, lng interface{}) *MockZoneRepository_FindByLocation_Call {
	return &MockZoneRepository_FindByLocation_Call{Call: _e.mock.On("FindByLocation", ctx, lat, lng)}
}

func (_c *MockZoneRepository_FindByLocation_Call) Run(run func(ctx context.Context, lat float64, lng float64)) *MockZoneRepository_FindByLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockZoneRepository_FindByLocation_Call) Return(_a0 *model.Zone, _a1 error) *MockZoneRepository_FindByLocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZoneRepository_FindByLocation_Call) RunAndReturn(run func(context.Context, float64, float64) (*model.Zone, error)) *MockZoneRepository_FindByLocation_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockZoneRepository) Find(ctx context.Context, filter model.ZoneFilter) ([]model.Zone, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.Zone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ZoneFilter) ([]model.Zone, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ZoneFilter) []model.Zone); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Zone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ZoneFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZoneRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockZoneRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.ZoneFilter
func (_e *MockZoneRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockZoneRepository_Find_Call {
	return &MockZoneRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockZoneRepository_Find_Call) Run(run func(ctx context.Context, filter model.ZoneFilter)) *MockZoneRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ZoneFilter))
	})
	return _c
}

func (_c *MockZoneRepository_Find_Call) Return(_a0 []model.Zone, _a1 error) *MockZoneRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZoneRepository_Find_Call) RunAndReturn(run func(context.Context, model.ZoneFilter) ([]model.Zone, error)) *MockZoneRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockZoneRepository) FindByID(ctx context.Context, id string) (model.Zone, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.Zone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Zone, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Zone); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Zone)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZoneRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockZoneRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockZoneRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockZoneRepository_FindByID_Call {
	return &MockZoneRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockZoneRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockZoneRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockZoneRepository_FindByID_Call) Return(_a0 model.Zone, _a1 error) *MockZoneRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZoneRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (model.Zone, error)) *MockZoneRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, zone
func (_m *MockZoneRepository) Insert(ctx context.Context, zone model.Zone) (string, error) {
	ret := _m.Called(ctx, zone)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Zone) (string, error)); ok {
		return rf(ctx, zone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Zone) string); ok {
		r0 = rf(ctx, zone)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Zone) error); ok {
		r1 = rf(ctx, zone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZoneRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockZoneRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - zone model.Zone
func (_e *MockZoneRepository_Expecter) Insert(ctx interface{}, zone interface{}) *MockZoneRepository_Insert_Call {
	return &MockZoneRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, zone)}
}

func (_c *MockZoneRepository_Insert_Call) Run(run func(ctx context.Context, zone model.Zone)) *MockZoneRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Zone))
	})
	return _c
}

func (_c *MockZoneRepository_Insert_Call) Return(_a0 string, _a1 error) *MockZoneRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZoneRepository_Insert_Call) RunAndReturn(run func(context.Context, model.Zone) (string, error)) *MockZoneRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *MockZoneRepository) Update(ctx context.Context, id string, update model.ZoneUpdate) error {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.ZoneUpdate) error); ok {
		r0 = rf(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockZoneRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockZoneRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update model.ZoneUpdate
func (_e *MockZoneRepository_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *MockZoneRepository_Update_Call {
	return &MockZoneRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockZoneRepository_Update_Call) Run(run func(ctx context.Context, id string, update model.ZoneUpdate)) *MockZoneRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.ZoneUpdate))
	})
	return _c
}

func (_c *MockZoneRepository_Update_Call) Return(_a0 error) *MockZoneRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockZoneRepository_Update_Call) RunAndReturn(run func(context.Context, string, model.ZoneUpdate) error) *MockZoneRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockZoneRepository creates a new instance of MockZoneRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockZoneRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockZoneRepository {
	mock := &MockZoneRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
