// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/car-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCarRepository is an autogenerated mock type for the CarRepository type
type MockCarRepository struct {
	mock.Mock
}

type MockCarRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarRepository) EXPECT() *MockCarRepository_Expecter {
	return &MockCarRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCarRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCarRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCarRepository_Delete_Call {
	return &MockCarRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCarRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCarRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarRepository_Delete_Call) Return(_a0 error) *MockCarRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCarRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockCarRepository) Find(ctx context.Context, filter model.CarFilter) ([]model.Car, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.Car
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarFilter) ([]model.Car, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarFilter) []model.Car); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Car)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCarRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.CarFilter
func (_e *MockCarRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockCarRepository_Find_Call {
	return &MockCarRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockCarRepository_Find_Call) Run(run func(ctx context.Context, filter model.CarFilter)) *MockCarRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarFilter))
	})
	return _c
}

func (_c *MockCarRepository_Find_Call) Return(_a0 []model.Car, _a1 error) *MockCarRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarRepository_Find_Call) RunAndReturn(run func(context.Context, model.CarFilter) ([]model.Car, error)) *MockCarRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCarRepository) FindByID(ctx context.Context, id string) (model.Car, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.Car
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Car, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Car); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Car)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCarRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCarRepository_FindByID_Call {
	return &MockCarRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCarRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockCarRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarRepository_FindByID_Call) Return(_a0 model.Car, _a1 error) *MockCarRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (model.Car, error)) *MockCarRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, car
func (_m *MockCarRepository) Insert(ctx context.Context, car model.Car) (string, error) {
	ret := _m.Called(ctx, car)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Car) (string, error)); ok {
		return rf(ctx, car)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Car) string); ok {
		r0 = rf(ctx, car)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Car) error); ok {
		r1 = rf(ctx, car)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCarRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - car model.Car
func (_e *MockCarRepository_Expecter) Insert(ctx interface{}, car interface{}) *MockCarRepository_Insert_Call {
	return &MockCarRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, car)}
}

func (_c *MockCarRepository_Insert_Call) Run(run func(ctx context.Context, car model.Car)) *MockCarRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Car))
	})
	return _c
}

func (_c *MockCarRepository_Insert_Call) Return(_a0 string, _a1 error) *MockCarRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarRepository_Insert_Call) RunAndReturn(run func(context.Context, model.Car) (string, error)) *MockCarRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *MockCarRepository) Update(ctx context.Context, id string, update model.CarUpdate) error {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarUpdate) error); ok {
		r0 = rf(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update model.CarUpdate
func (_e *MockCarRepository_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *MockCarRepository_Update_Call {
	return &MockCarRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockCarRepository_Update_Call) Run(run func(ctx context.Context, id string, update model.CarUpdate)) *MockCarRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarUpdate))
	})
	return _c
}

func (_c *MockCarRepository_Update_Call) Return(_a0 error) *MockCarRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarRepository_Update_Call) RunAndReturn(run func(context.Context, string, model.CarUpdate) error) *MockCarRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarRepository creates a new instance of MockCarRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarRepository {
	mock := &MockCarRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
