// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/car-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCarStatusReadingRepository is an autogenerated mock type for the CarStatusReadingRepository type
type MockCarStatusReadingRepository struct {
	mock.Mock
}

type MockCarStatusReadingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarStatusReadingRepository) EXPECT() *MockCarStatusReadingRepository_Expecter {
	return &MockCarStatusReadingRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockCarStatusReadingRepository) Find(ctx context.Context, filter model.CarStatusReadingFilter) ([]model.CarStatusReading, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.CarStatusReading
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarStatusReadingFilter) ([]model.CarStatusReading, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarStatusReadingFilter) []model.CarStatusReading); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarStatusReading)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarStatusReadingFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarStatusReadingRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCarStatusReadingRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.CarStatusReadingFilter
func (_e *MockCarStatusReadingRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockCarStatusReadingRepository_Find_Call {
	return &MockCarStatusReadingRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockCarStatusReadingRepository_Find_Call) Run(run func(ctx context.Context, filter model.CarStatusReadingFilter)) *MockCarStatusReadingRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarStatusReadingFilter))
	})
	return _c
}

func (_c *MockCarStatusReadingRepository_Find_Call) Return(_a0 []model.CarStatusReading, _a1 error) *MockCarStatusReadingRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarStatusReadingRepository_Find_Call) RunAndReturn(run func(context.Context, model.CarStatusReadingFilter) ([]model.CarStatusReading, error)) *MockCarStatusReadingRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, entry
func (_m *MockCarStatusReadingRepository) Insert(ctx context.Context, entry model.CarStatusReading) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarStatusReading) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarStatusReadingRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCarStatusReadingRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - entry model.CarStatusReading
func (_e *MockCarStatusReadingRepository_Expecter) Insert(ctx interface{}, entry interface{}) *MockCarStatusReadingRepository_Insert_Call {
	return &MockCarStatusReadingRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, entry)}
}

func (_c *MockCarStatusReadingRepository_Insert_Call) Run(run func(ctx context.Context, entry model.CarStatusReading)) *MockCarStatusReadingRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarStatusReading))
	})
	return _c
}

func (_c *MockCarStatusReadingRepository_Insert_Call) Return(_a0 error) *MockCarStatusReadingRepository_Insert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarStatusReadingRepository_Insert_Call) RunAndReturn(run func(context.Context, model.CarStatusReading) error) *MockCarStatusReadingRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarStatusReadingRepository creates a new instance of MockCarStatusReadingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarStatusReadingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarStatusReadingRepository {
	mock := &MockCarStatusReadingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
