// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/sorawaslocked/car-rental-car-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCarMaintenanceTemplateRepository is an autogenerated mock type for the CarMaintenanceTemplateRepository type
type MockCarMaintenanceTemplateRepository struct {
	mock.Mock
}

type MockCarMaintenanceTemplateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarMaintenanceTemplateRepository) EXPECT() *MockCarMaintenanceTemplateRepository_Expecter {
	return &MockCarMaintenanceTemplateRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCarMaintenanceTemplateRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceTemplateRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCarMaintenanceTemplateRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarMaintenanceTemplateRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCarMaintenanceTemplateRepository_Delete_Call {
	return &MockCarMaintenanceTemplateRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCarMaintenanceTemplateRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCarMaintenanceTemplateRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarMaintenanceTemplateRepository_Delete_Call) Return(_a0 error) *MockCarMaintenanceTemplateRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceTemplateRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCarMaintenanceTemplateRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockCarMaintenanceTemplateRepository) Find(ctx context.Context, filter model.CarMaintenanceTemplateFilter) ([]model.CarMaintenanceTemplate, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.CarMaintenanceTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceTemplateFilter) ([]model.CarMaintenanceTemplate, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceTemplateFilter) []model.CarMaintenanceTemplate); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarMaintenanceTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarMaintenanceTemplateFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceTemplateRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCarMaintenanceTemplateRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.CarMaintenanceTemplateFilter
func (_e *MockCarMaintenanceTemplateRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockCarMaintenanceTemplateRepository_Find_Call {
	return &MockCarMaintenanceTemplateRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockCarMaintenanceTemplateRepository_Find_Call) Run(run func(ctx context.Context, filter model.CarMaintenanceTemplateFilter)) *MockCarMaintenanceTemplateRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarMaintenanceTemplateFilter))
	})
	return _c
}

func (_c *MockCarMaintenanceTemplateRepository_Find_Call) Return(_a0 []model.CarMaintenanceTemplate, _a1 error) *MockCarMaintenanceTemplateRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceTemplateRepository_Find_Call) RunAndReturn(run func(context.Context, model.CarMaintenanceTemplateFilter) ([]model.CarMaintenanceTemplate, error)) *MockCarMaintenanceTemplateRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCarMaintenanceTemplateRepository) FindByID(ctx context.Context, id string) (model.CarMaintenanceTemplate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.CarMaintenanceTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CarMaintenanceTemplate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CarMaintenanceTemplate); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.CarMaintenanceTemplate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceTemplateRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCarMaintenanceTemplateRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarMaintenanceTemplateRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockCarMaintenanceTemplateRepository_FindByID_Call {
	return &MockCarMaintenanceTemplateRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCarMaintenanceTemplateRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockCarMaintenanceTemplateRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarMaintenanceTemplateRepository_FindByID_Call) Return(_a0 model.CarMaintenanceTemplate, _a1 error) *MockCarMaintenanceTemplateRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceTemplateRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (model.CarMaintenanceTemplate, error)) *MockCarMaintenanceTemplateRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, template
func (_m *MockCarMaintenanceTemplateRepository) Insert(ctx context.Context, template model.CarMaintenanceTemplate) (string, error) {
	ret := _m.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceTemplate) (string, error)); ok {
		return rf(ctx, template)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceTemplate) string); ok {
		r0 = rf(ctx, template)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarMaintenanceTemplate) error); ok {
		r1 = rf(ctx, template)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceTemplateRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCarMaintenanceTemplateRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - template model.CarMaintenanceTemplate
func (_e *MockCarMaintenanceTemplateRepository_Expecter) Insert(ctx interface{}, template interface{}) *MockCarMaintenanceTemplateRepository_Insert_Call {
	return &MockCarMaintenanceTemplateRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, template)}
}

func (_c *MockCarMaintenanceTemplateRepository_Insert_Call) Run(run func(ctx context.Context, template model.CarMaintenanceTemplate)) *MockCarMaintenanceTemplateRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarMaintenanceTemplate))
	})
	return _c
}

func (_c *MockCarMaintenanceTemplateRepository_Insert_Call) Return(_a0 string, _a1 error) *MockCarMaintenanceTemplateRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceTemplateRepository_Insert_Call) RunAndReturn(run func(context.Context, model.CarMaintenanceTemplate) (string, error)) *MockCarMaintenanceTemplateRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *MockCarMaintenanceTemplateRepository) Update(ctx context.Context, id string, update model.CarMaintenanceTemplateUpdate) error {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarMaintenanceTemplateUpdate) error); ok {
		r0 = rf(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceTemplateRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarMaintenanceTemplateRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update model.CarMaintenanceTemplateUpdate
func (_e *MockCarMaintenanceTemplateRepository_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *MockCarMaintenanceTemplateRepository_Update_Call {
	return &MockCarMaintenanceTemplateRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockCarMaintenanceTemplateRepository_Update_Call) Run(run func(ctx context.Context, id string, update model.CarMaintenanceTemplateUpdate)) *MockCarMaintenanceTemplateRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarMaintenanceTemplateUpdate))
	})
	return _c
}

func (_c *MockCarMaintenanceTemplateRepository_Update_Call) Return(_a0 error) *MockCarMaintenanceTemplateRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceTemplateRepository_Update_Call) RunAndReturn(run func(context.Context, string, model.CarMaintenanceTemplateUpdate) error) *MockCarMaintenanceTemplateRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarMaintenanceTemplateRepository creates a new instance of MockCarMaintenanceTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarMaintenanceTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarMaintenanceTemplateRepository {
	mock := &MockCarMaintenanceTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
