# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base/common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'base/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62\x61se/common.proto\x12\x04\x62\x61se\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n\tTimeRange\x12-\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12+\n\x02to\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x42\x07\n\x05_fromB\x05\n\x03_to\"!\n\x05Image\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"@\n\x0fImageUploadData\x12\x19\n\x11presigned_put_url\x18\x01 \x01(\t\x12\x12\n\nobject_key\x18\x02 \x01(\t\"+\n\nPagination\x12\r\n\x05limit\x18\x01 \x01(\x03\x12\x0e\n\x06offset\x18\x02 \x01(\x03\"/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"\xa7\x02\n\x0fPricingSnapshot\x12\x12\n\nrate_tenge\x18\x01 \x01(\x05\x12\x1e\n\x11rate_per_km_tenge\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x19\n\x0c\x66ree_minutes\x18\x03 \x01(\x05H\x01\x88\x01\x01\x12\x1d\n\x10min_charge_tenge\x18\x04 \x01(\x05H\x02\x88\x01\x01\x12\x1c\n\x0fovertime_policy\x18\x05 \x01(\tH\x03\x88\x01\x01\x12 \n\x13overtime_rate_tenge\x18\x06 \x01(\x05H\x04\x88\x01\x01\x42\x14\n\x12_rate_per_km_tengeB\x0f\n\r_free_minutesB\x13\n\x11_min_charge_tengeB\x12\n\x10_overtime_policyB\x16\n\x14_overtime_rate_tengeB\x1cZ\x1a\x63\x61rsharing/protos/gen/baseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032carsharing/protos/gen/base'
  _globals['_TIMERANGE']._serialized_start=60
  _globals['_TIMERANGE']._serialized_end=179
  _globals['_IMAGE']._serialized_start=181
  _globals['_IMAGE']._serialized_end=214
  _globals['_IMAGEUPLOADDATA']._serialized_start=216
  _globals['_IMAGEUPLOADDATA']._serialized_end=280
  _globals['_PAGINATION']._serialized_start=282
  _globals['_PAGINATION']._serialized_end=325
  _globals['_LOCATION']._serialized_start=327
  _globals['_LOCATION']._serialized_end=374
  _globals['_PRICINGSNAPSHOT']._serialized_start=377
  _globals['_PRICINGSNAPSHOT']._serialized_end=672
# @@protoc_insertion_point(module_scope)
