// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDocumentAnalyzer is an autogenerated mock type for the DocumentAnalyzer type
type MockDocumentAnalyzer struct {
	mock.Mock
}

type MockDocumentAnalyzer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentAnalyzer) EXPECT() *MockDocumentAnalyzer_Expecter {
	return &MockDocumentAnalyzer_Expecter{mock: &_m.Mock}
}

// Analyze provides a mock function with given fields: ctx, documentID, objectKey
func (_m *MockDocumentAnalyzer) Analyze(ctx context.Context, documentID string, objectKey string) {
	_m.Called(ctx, documentID, objectKey)
}

// MockDocumentAnalyzer_Analyze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analyze'
type MockDocumentAnalyzer_Analyze_Call struct {
	*mock.Call
}

// Analyze is a helper method to define mock.On call
//   - ctx context.Context
//   - documentID string
//   - objectKey string
func (_e *MockDocumentAnalyzer_Expecter) Analyze(ctx interface{}, documentID interface{}, objectKey interface{}) *MockDocumentAnalyzer_Analyze_Call {
	return &MockDocumentAnalyzer_Analyze_Call{Call: _e.mock.On("Analyze", ctx, documentID, objectKey)}
}

func (_c *MockDocumentAnalyzer_Analyze_Call) Run(run func(ctx context.Context, documentID string, objectKey string)) *MockDocumentAnalyzer_Analyze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDocumentAnalyzer_Analyze_Call) Return() *MockDocumentAnalyzer_Analyze_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDocumentAnalyzer_Analyze_Call) RunAndReturn(run func(context.Context, string, string)) *MockDocumentAnalyzer_Analyze_Call {
	_c.Run(run)
	return _c
}

// NewMockDocumentAnalyzer creates a new instance of MockDocumentAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentAnalyzer {
	mock := &MockDocumentAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
