// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMailer is an autogenerated mock type for the Mailtrap type
type MockMailer struct {
	mock.Mock
}

type MockMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailer) EXPECT() *MockMailer_Expecter {
	return &MockMailer_Expecter{mock: &_m.Mock}
}

// SendActivationCode provides a mock function with given fields: ctx, receiver, code
func (_m *MockMailer) SendActivationCode(ctx context.Context, receiver string, code string) error {
	ret := _m.Called(ctx, receiver, code)

	if len(ret) == 0 {
		panic("no return value specified for SendActivationCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, receiver, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailer_SendActivationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendActivationCode'
type MockMailer_SendActivationCode_Call struct {
	*mock.Call
}

// SendActivationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - receiver string
//   - code string
func (_e *MockMailer_Expecter) SendActivationCode(ctx interface{}, receiver interface{}, code interface{}) *MockMailer_SendActivationCode_Call {
	return &MockMailer_SendActivationCode_Call{Call: _e.mock.On("SendActivationCode", ctx, receiver, code)}
}

func (_c *MockMailer_SendActivationCode_Call) Run(run func(ctx context.Context, receiver string, code string)) *MockMailer_SendActivationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMailer_SendActivationCode_Call) Return(_a0 error) *MockMailer_SendActivationCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailer_SendActivationCode_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMailer_SendActivationCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailer {
	mock := &MockMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
