// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserPublisher is an autogenerated mock type for the UserPublisher type
type MockUserPublisher struct {
	mock.Mock
}

type MockUserPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserPublisher) EXPECT() *MockUserPublisher_Expecter {
	return &MockUserPublisher_Expecter{mock: &_m.Mock}
}

// PublishUserCreated provides a mock function with given fields: ctx, id
func (_m *MockUserPublisher) PublishUserCreated(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserPublisher_PublishUserCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserCreated'
type MockUserPublisher_PublishUserCreated_Call struct {
	*mock.Call
}

// PublishUserCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserPublisher_Expecter) PublishUserCreated(ctx interface{}, id interface{}) *MockUserPublisher_PublishUserCreated_Call {
	return &MockUserPublisher_PublishUserCreated_Call{Call: _e.mock.On("PublishUserCreated", ctx, id)}
}

func (_c *MockUserPublisher_PublishUserCreated_Call) Run(run func(ctx context.Context, id string)) *MockUserPublisher_PublishUserCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserPublisher_PublishUserCreated_Call) Return(_a0 error) *MockUserPublisher_PublishUserCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserPublisher_PublishUserCreated_Call) RunAndReturn(run func(context.Context, string) error) *MockUserPublisher_PublishUserCreated_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserDeleted provides a mock function with given fields: ctx, id
func (_m *MockUserPublisher) PublishUserDeleted(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserDeleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserPublisher_PublishUserDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserDeleted'
type MockUserPublisher_PublishUserDeleted_Call struct {
	*mock.Call
}

// PublishUserDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserPublisher_Expecter) PublishUserDeleted(ctx interface{}, id interface{}) *MockUserPublisher_PublishUserDeleted_Call {
	return &MockUserPublisher_PublishUserDeleted_Call{Call: _e.mock.On("PublishUserDeleted", ctx, id)}
}

func (_c *MockUserPublisher_PublishUserDeleted_Call) Run(run func(ctx context.Context, id string)) *MockUserPublisher_PublishUserDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserPublisher_PublishUserDeleted_Call) Return(_a0 error) *MockUserPublisher_PublishUserDeleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserPublisher_PublishUserDeleted_Call) RunAndReturn(run func(context.Context, string) error) *MockUserPublisher_PublishUserDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserUpdated provides a mock function with given fields: ctx, id, isSecurityUpdate
func (_m *MockUserPublisher) PublishUserUpdated(ctx context.Context, id string, isSecurityUpdate bool) error {
	ret := _m.Called(ctx, id, isSecurityUpdate)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserUpdated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, id, isSecurityUpdate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserPublisher_PublishUserUpdated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserUpdated'
type MockUserPublisher_PublishUserUpdated_Call struct {
	*mock.Call
}

// PublishUserUpdated is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - isSecurityUpdate bool
func (_e *MockUserPublisher_Expecter) PublishUserUpdated(ctx interface{}, id interface{}, isSecurityUpdate interface{}) *MockUserPublisher_PublishUserUpdated_Call {
	return &MockUserPublisher_PublishUserUpdated_Call{Call: _e.mock.On("PublishUserUpdated", ctx, id, isSecurityUpdate)}
}

func (_c *MockUserPublisher_PublishUserUpdated_Call) Run(run func(ctx context.Context, id string, isSecurityUpdate bool)) *MockUserPublisher_PublishUserUpdated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockUserPublisher_PublishUserUpdated_Call) Return(_a0 error) *MockUserPublisher_PublishUserUpdated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserPublisher_PublishUserUpdated_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockUserPublisher_PublishUserUpdated_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserPublisher creates a new instance of MockUserPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserPublisher {
	mock := &MockUserPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
