// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockActivationCodeStorage is an autogenerated mock type for the ActivationCodeStorage type
type MockActivationCodeStorage struct {
	mock.Mock
}

type MockActivationCodeStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivationCodeStorage) EXPECT() *MockActivationCodeStorage_Expecter {
	return &MockActivationCodeStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, userID
func (_m *MockActivationCodeStorage) Get(ctx context.Context, userID string) ([]byte, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivationCodeStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockActivationCodeStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockActivationCodeStorage_Expecter) Get(ctx interface{}, userID interface{}) *MockActivationCodeStorage_Get_Call {
	return &MockActivationCodeStorage_Get_Call{Call: _e.mock.On("Get", ctx, userID)}
}

func (_c *MockActivationCodeStorage_Get_Call) Run(run func(ctx context.Context, userID string)) *MockActivationCodeStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockActivationCodeStorage_Get_Call) Return(_a0 []byte, _a1 error) *MockActivationCodeStorage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivationCodeStorage_Get_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockActivationCodeStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, userID
func (_m *MockActivationCodeStorage) Save(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivationCodeStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockActivationCodeStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockActivationCodeStorage_Expecter) Save(ctx interface{}, userID interface{}) *MockActivationCodeStorage_Save_Call {
	return &MockActivationCodeStorage_Save_Call{Call: _e.mock.On("Save", ctx, userID)}
}

func (_c *MockActivationCodeStorage_Save_Call) Run(run func(ctx context.Context, userID string)) *MockActivationCodeStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockActivationCodeStorage_Save_Call) Return(_a0 string, _a1 error) *MockActivationCodeStorage_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivationCodeStorage_Save_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockActivationCodeStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActivationCodeStorage creates a new instance of MockActivationCodeStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivationCodeStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivationCodeStorage {
	mock := &MockActivationCodeStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
