// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/user-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockDocumentRepository is an autogenerated mock type for the DocumentRepository type
type MockDocumentRepository struct {
	mock.Mock
}

type MockDocumentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentRepository) EXPECT() *MockDocumentRepository_Expecter {
	return &MockDocumentRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, filter
func (_m *MockDocumentRepository) Find(ctx context.Context, filter model.DocumentFilter) ([]model.Document, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.DocumentFilter) ([]model.Document, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.DocumentFilter) []model.Document); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.DocumentFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockDocumentRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.DocumentFilter
func (_e *MockDocumentRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockDocumentRepository_Find_Call {
	return &MockDocumentRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockDocumentRepository_Find_Call) Run(run func(ctx context.Context, filter model.DocumentFilter)) *MockDocumentRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.DocumentFilter))
	})
	return _c
}

func (_c *MockDocumentRepository_Find_Call) Return(_a0 []model.Document, _a1 error) *MockDocumentRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_Find_Call) RunAndReturn(run func(context.Context, model.DocumentFilter) ([]model.Document, error)) *MockDocumentRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockDocumentRepository) FindByID(ctx context.Context, id string) (model.Document, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Document, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Document); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockDocumentRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDocumentRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockDocumentRepository_FindByID_Call {
	return &MockDocumentRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockDocumentRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockDocumentRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDocumentRepository_FindByID_Call) Return(_a0 model.Document, _a1 error) *MockDocumentRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (model.Document, error)) *MockDocumentRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function with given fields: ctx, doc
func (_m *MockDocumentRepository) Insert(ctx context.Context, doc model.Document) (string, error) {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Document) (string, error)); ok {
		return rf(ctx, doc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Document) string); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Document) error); ok {
		r1 = rf(ctx, doc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockDocumentRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - doc model.Document
func (_e *MockDocumentRepository_Expecter) Insert(ctx interface{}, doc interface{}) *MockDocumentRepository_Insert_Call {
	return &MockDocumentRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, doc)}
}

func (_c *MockDocumentRepository_Insert_Call) Run(run func(ctx context.Context, doc model.Document)) *MockDocumentRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Document))
	})
	return _c
}

func (_c *MockDocumentRepository_Insert_Call) Return(_a0 string, _a1 error) *MockDocumentRepository_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_Insert_Call) RunAndReturn(run func(context.Context, model.Document) (string, error)) *MockDocumentRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *MockDocumentRepository) Update(ctx context.Context, id string, update model.DocumentUpdate) error {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.DocumentUpdate) error); ok {
		r0 = rf(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDocumentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update model.DocumentUpdate
func (_e *MockDocumentRepository_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *MockDocumentRepository_Update_Call {
	return &MockDocumentRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockDocumentRepository_Update_Call) Run(run func(ctx context.Context, id string, update model.DocumentUpdate)) *MockDocumentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.DocumentUpdate))
	})
	return _c
}

func (_c *MockDocumentRepository_Update_Call) Return(_a0 error) *MockDocumentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepository_Update_Call) RunAndReturn(run func(context.Context, string, model.DocumentUpdate) error) *MockDocumentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDocumentRepository creates a new instance of MockDocumentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentRepository {
	mock := &MockDocumentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
