env: "dev"

grpc_server:
  host: "0.0.0.0"
  port: 9996

postgres:
  host: "postgres"
  port: 5432
  user: "car_rental"
  password: "car_rental"
  database: "car_rental"
  ssl_mode: "disable"

nats:
  urls:
    - "nats://nats:4222"
  name: "trip-service"
  username: ""
  password: ""

car_service:
  host: "car-service"
  port: 9998

car_stream_service:
  host: "car-service"
  port: 9998

booking_service:
  host: "booking-service"
  port: 9997
