services:
  document-analyzer:
    image: ghcr.io/sorawaslocked/carsharing/document-analyzer:latest
    container_name: document-analyzer
    build: .
    networks:
      - car-rental-net

networks:
  car-rental-net:
    external: true
