services:
  document-analyzer:
    image: ghcr.io/sorawaslocked/carsharing/document-analyzer:latest
    container_name: carsharing-document-analyzer
    build: .
    networks:
      - carsharing-net

networks:
  carsharing-net:
    external: true
