# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event/user/document.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'event/user/document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from base.user import user_pb2 as base_dot_user_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65vent/user/document.proto\x12\nevent.user\x1a\x14\x62\x61se/user/user.proto\"q\n\x15\x44ocumentAnalyzedEvent\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0e\n\x06passed\x18\x02 \x01(\x08\x12\"\n\x07\x64\x65\x66\x65\x63ts\x18\x03 \x03(\x0b\x32\x11.base.user.Defect\x12\x0f\n\x07user_id\x18\x04 \x01(\tB\"Z carsharing/protos/gen/event/userb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event.user.document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z carsharing/protos/gen/event/user'
  _globals['_DOCUMENTANALYZEDEVENT']._serialized_start=63
  _globals['_DOCUMENTANALYZEDEVENT']._serialized_end=176
# @@protoc_insertion_point(module_scope)
