env: "dev"

grpc_server:
  host: "0.0.0.0"
  port: 9997

postgres:
  host: "postgres"
  port: 5432
  user: "carsharing"
  password: "carsharing"
  database: "carsharing"
  ssl_mode: "disable"

nats_publisher:
  urls:
    - "nats://nats:4222"
  name: "booking-service-publisher"
  username: ""
  password: ""

nats_subscriber:
  urls:
    - "nats://nats:4222"
  name: "booking-service-subscriber"
  username: ""
  password: ""

car_service:
  host: "carsharing-car-service"
  port: 9998
