env: "dev"

grpc_server:
  addr: "0.0.0.0:9997"

postgres:
  host: "postgres"
  port: 5432
  user: "car_rental"
  password: "car_rental"
  database: "car_rental"
  ssl_mode: "disable"
  max_open_connections: 25
  max_idle_connections: 25
  max_idle_time: "15m"

nats:
  url: "nats://nats:4222"
