services:
  migrate:
    container_name: trip-service-migrate
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://carsharing:${POSTGRES_PASSWORD}@postgres:5432/carsharing?sslmode=disable&x-migrations-table=trip_service_migrations"
      - "up"
    networks:
      - car-rental-net

  trip-service:
    image: ghcr.io/sorawaslocked/carsharing/trip-service:latest
    container_name: trip-service
    build:
      context: ..
      dockerfile: trip-service/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NATS_PUBLISHER_USERNAME: ""
      NATS_PUBLISHER_PASSWORD: ""
    networks:
      - car-rental-net
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: on-failure

networks:
  car-rental-net:
    external: true
