FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /trip-service ./cmd/trip-service/main.go

FROM alpine:3.21

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /trip-service .
COPY --from=builder /app/config ./config

EXPOSE 9996

ENTRYPOINT ["./trip-service", "-config", "./config/docker.yml"]
