services:
  redis:
    image: redis:7-alpine
    container_name: user-service-redis
    command: redis-server --requirepass secret
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a secret ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - car-rental-net

  migrate:
    container_name: user-service-migrate
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://car_rental:car_rental@car-service-postgres:5432/car_rental?sslmode=disable&x-migrations-table=user_service_migrations"
      - "up"
    networks:
      - car-rental-net

  user-service:
    build: .
    ports:
      - "9999:9999"
    environment:
      POSTGRES_PASSWORD: car_rental
      REDIS_PASSWORD: secret
      MINIO_ACCESS_KEY_ID: minioadmin
      MINIO_SECRET_ACCESS_KEY: minioadmin
      MAILTRAP_TOKEN: ${MAILTRAP_TOKEN}
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    restart: on-failure
    networks:
      - car-rental-net

networks:
  car-rental-net:
    external: true
