services:
  redis:
    image: redis:7-alpine
    container_name: carsharing-user-service-redis
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $REDIS_PASSWORD ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - carsharing-net

  migrate:
    container_name: carsharing-user-service-migrate
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://carsharing:${POSTGRES_PASSWORD}@postgres:5432/carsharing?sslmode=disable&x-migrations-table=user_service_migrations"
      - "up"
    networks:
      - carsharing-net

  user-service:
    image: ghcr.io/sorawaslocked/carsharing/user-service:latest
    container_name: carsharing-user-service
    build:
      context: ..
      dockerfile: user-service/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      NATS_PUBLISHER_USERNAME: ""
      NATS_PUBLISHER_PASSWORD: ""
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_FROM: ${BREVO_FROM}
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    restart: on-failure
    networks:
      - carsharing-net

networks:
  carsharing-net:
    external: true
