with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  carsharing/car-service/internal/service:
    config:
      dir: "internal/service/mocks"
      outpkg: "mocks"
    interfaces:
      CarRepository:
      CarStatusReadingRepository:
      CarModelRepository:
      ZoneRepository:
      CarInsuranceRepository:
      CarMaintenanceTemplateRepository:
      CarMaintenanceRecordRepository:
      CarServiceStateRepository:
      TelemetryReadingRepository:
      TelemetryStreamClient:
      ObjectStorage:
      EventPublisher:
  carsharing/car-service/internal/adapter/grpc/handler:
    config:
      dir: "internal/adapter/grpc/handler/mocks"
      outpkg: "mocks"
    interfaces:
      CarModelService:
      CarService:
      CarInsuranceService:
      CarMaintenanceService:
      ZoneService:
      Pinger:
      TelemetrySubscriber:
      StatusSubscriber:
