services:
  migrate:
    container_name: car-service-migrate
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://car_rental:${POSTGRES_PASSWORD}@postgres:5432/car_rental?sslmode=disable"
      - "up"
    networks:
      - car-rental-net

  car-service:
    container_name: car-service
    build:
      context: ..
      dockerfile: car-service/Dockerfile
    ports:
      - "9998:9998"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      NATS_PUBLISHER_USERNAME: ""
      NATS_PUBLISHER_PASSWORD: ""
      NATS_SUBSCRIBER_USERNAME: ""
      NATS_SUBSCRIBER_PASSWORD: ""
    networks:
      - car-rental-net
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: on-failure

networks:
  car-rental-net:
    external: true
