services:
  migrate:
    container_name: carsharing-car-service-migrate
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://carsharing:${POSTGRES_PASSWORD}@postgres:5432/carsharing?sslmode=disable"
      - "up"
    networks:
      - carsharing-net

  car-service:
    image: ghcr.io/sorawaslocked/carsharing/car-service:latest
    container_name: carsharing-car-service
    build:
      context: ..
      dockerfile: car-service/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      MINIO_PUBLIC_ENDPOINT: ${MINIO_PUBLIC_ENDPOINT}
      NATS_PUBLISHER_USERNAME: ""
      NATS_PUBLISHER_PASSWORD: ""
      NATS_SUBSCRIBER_USERNAME: ""
      NATS_SUBSCRIBER_PASSWORD: ""
    networks:
      - carsharing-net
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: on-failure

networks:
  carsharing-net:
    external: true
