services:
  telematics:
    image: ghcr.io/sorawaslocked/carsharing/telematics-service:latest
    container_name: telematics
    build: .
    environment:
      DB_URL: "postgres://carsharing:carsharing@car-service-postgres:5432/carsharing?sslmode=disable"
      NATS_URL: "nats://nats:4222"
    networks:
      - car-rental-net

networks:
  car-rental-net:
    external: true
