with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  carsharing/booking-service/internal/service:
    interfaces:
      BookingRepository:
      PricingRuleRepository:
      EventPublisher:
      CarChecker:
      CarModelChecker:
    config:
      dir: internal/service/mocks
      outpkg: mocks
  carsharing/booking-service/internal/adapter/grpc/handler:
    interfaces:
      BookingService:
      PricingRuleService:
    config:
      dir: internal/adapter/grpc/handler/mocks
      outpkg: mocks
