services:
  migrate:
    container_name: carsharing-booking-service-migrate
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://carsharing:${POSTGRES_PASSWORD}@postgres:5432/carsharing?sslmode=disable&x-migrations-table=booking_service_migrations"
      - "up"
    networks:
      - carsharing-net

  booking-service:
    image: ghcr.io/sorawaslocked/carsharing/booking-service:latest
    container_name: carsharing-booking-service
    build:
      context: ..
      dockerfile: booking-service/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NATS_PUBLISHER_USERNAME: ""
      NATS_PUBLISHER_PASSWORD: ""
      NATS_SUBSCRIBER_USERNAME: ""
      NATS_SUBSCRIBER_PASSWORD: ""
    networks:
      - carsharing-net
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: on-failure

networks:
  carsharing-net:
    external: true
