// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/booking-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCarChecker is an autogenerated mock type for the CarChecker type
type MockCarChecker struct {
	mock.Mock
}

type MockCarChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarChecker) EXPECT() *MockCarChecker_Expecter {
	return &MockCarChecker_Expecter{mock: &_m.Mock}
}

// GetStatus provides a mock function with given fields: ctx, carID
func (_m *MockCarChecker) GetStatus(ctx context.Context, carID string) (model.CarStatus, error) {
	ret := _m.Called(ctx, carID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 model.CarStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CarStatus, error)); ok {
		return rf(ctx, carID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CarStatus); ok {
		r0 = rf(ctx, carID)
	} else {
		r0 = ret.Get(0).(model.CarStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, carID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarChecker_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockCarChecker_GetStatus_Call struct {
	*mock.Call
}

func (_e *MockCarChecker_Expecter) GetStatus(ctx interface{}, carID interface{}) *MockCarChecker_GetStatus_Call {
	return &MockCarChecker_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, carID)}
}

func (_c *MockCarChecker_GetStatus_Call) Run(run func(ctx context.Context, carID string)) *MockCarChecker_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarChecker_GetStatus_Call) Return(_a0 model.CarStatus, _a1 error) *MockCarChecker_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarChecker_GetStatus_Call) RunAndReturn(run func(context.Context, string) (model.CarStatus, error)) *MockCarChecker_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarChecker creates a new instance of MockCarChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarChecker {
	mock := &MockCarChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
