// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCarModelChecker is an autogenerated mock type for the CarModelChecker type
type MockCarModelChecker struct {
	mock.Mock
}

type MockCarModelChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarModelChecker) EXPECT() *MockCarModelChecker_Expecter {
	return &MockCarModelChecker_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: ctx, modelID
func (_m *MockCarModelChecker) Exists(ctx context.Context, modelID string) (bool, error) {
	ret := _m.Called(ctx, modelID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, modelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, modelID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, modelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarModelChecker_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockCarModelChecker_Exists_Call struct {
	*mock.Call
}

func (_e *MockCarModelChecker_Expecter) Exists(ctx interface{}, modelID interface{}) *MockCarModelChecker_Exists_Call {
	return &MockCarModelChecker_Exists_Call{Call: _e.mock.On("Exists", ctx, modelID)}
}

func (_c *MockCarModelChecker_Exists_Call) Run(run func(ctx context.Context, modelID string)) *MockCarModelChecker_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarModelChecker_Exists_Call) Return(_a0 bool, _a1 error) *MockCarModelChecker_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarModelChecker_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockCarModelChecker_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarModelChecker creates a new instance of MockCarModelChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarModelChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarModelChecker {
	mock := &MockCarModelChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
