// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/booking-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishBookingCancelled provides a mock function with given fields: ctx, booking, reason
func (_m *MockEventPublisher) PublishBookingCancelled(ctx context.Context, booking model.Booking, reason string) error {
	ret := _m.Called(ctx, booking, reason)

	if len(ret) == 0 {
		panic("no return value specified for PublishBookingCancelled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Booking, string) error); ok {
		r0 = rf(ctx, booking, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishBookingCancelled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishBookingCancelled'
type MockEventPublisher_PublishBookingCancelled_Call struct {
	*mock.Call
}

// PublishBookingCancelled is a helper method to define mock.On call
//   - ctx context.Context
//   - booking model.Booking
//   - reason string
func (_e *MockEventPublisher_Expecter) PublishBookingCancelled(ctx interface{}, booking interface{}, reason interface{}) *MockEventPublisher_PublishBookingCancelled_Call {
	return &MockEventPublisher_PublishBookingCancelled_Call{Call: _e.mock.On("PublishBookingCancelled", ctx, booking, reason)}
}

func (_c *MockEventPublisher_PublishBookingCancelled_Call) Run(run func(ctx context.Context, booking model.Booking, reason string)) *MockEventPublisher_PublishBookingCancelled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Booking), args[2].(string))
	})
	return _c
}

func (_c *MockEventPublisher_PublishBookingCancelled_Call) Return(_a0 error) *MockEventPublisher_PublishBookingCancelled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishBookingCancelled_Call) RunAndReturn(run func(context.Context, model.Booking, string) error) *MockEventPublisher_PublishBookingCancelled_Call {
	_c.Call.Return(run)
	return _c
}

// PublishBookingCompleted provides a mock function with given fields: ctx, booking
func (_m *MockEventPublisher) PublishBookingCompleted(ctx context.Context, booking model.Booking) error {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for PublishBookingCompleted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Booking) error); ok {
		r0 = rf(ctx, booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishBookingCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishBookingCompleted'
type MockEventPublisher_PublishBookingCompleted_Call struct {
	*mock.Call
}

// PublishBookingCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - booking model.Booking
func (_e *MockEventPublisher_Expecter) PublishBookingCompleted(ctx interface{}, booking interface{}) *MockEventPublisher_PublishBookingCompleted_Call {
	return &MockEventPublisher_PublishBookingCompleted_Call{Call: _e.mock.On("PublishBookingCompleted", ctx, booking)}
}

func (_c *MockEventPublisher_PublishBookingCompleted_Call) Run(run func(ctx context.Context, booking model.Booking)) *MockEventPublisher_PublishBookingCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Booking))
	})
	return _c
}

func (_c *MockEventPublisher_PublishBookingCompleted_Call) Return(_a0 error) *MockEventPublisher_PublishBookingCompleted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishBookingCompleted_Call) RunAndReturn(run func(context.Context, model.Booking) error) *MockEventPublisher_PublishBookingCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// PublishBookingCreated provides a mock function with given fields: ctx, booking
func (_m *MockEventPublisher) PublishBookingCreated(ctx context.Context, booking model.Booking) error {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for PublishBookingCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Booking) error); ok {
		r0 = rf(ctx, booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishBookingCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishBookingCreated'
type MockEventPublisher_PublishBookingCreated_Call struct {
	*mock.Call
}

// PublishBookingCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - booking model.Booking
func (_e *MockEventPublisher_Expecter) PublishBookingCreated(ctx interface{}, booking interface{}) *MockEventPublisher_PublishBookingCreated_Call {
	return &MockEventPublisher_PublishBookingCreated_Call{Call: _e.mock.On("PublishBookingCreated", ctx, booking)}
}

func (_c *MockEventPublisher_PublishBookingCreated_Call) Run(run func(ctx context.Context, booking model.Booking)) *MockEventPublisher_PublishBookingCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Booking))
	})
	return _c
}

func (_c *MockEventPublisher_PublishBookingCreated_Call) Return(_a0 error) *MockEventPublisher_PublishBookingCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishBookingCreated_Call) RunAndReturn(run func(context.Context, model.Booking) error) *MockEventPublisher_PublishBookingCreated_Call {
	_c.Call.Return(run)
	return _c
}

// PublishBookingExpired provides a mock function with given fields: ctx, booking
func (_m *MockEventPublisher) PublishBookingExpired(ctx context.Context, booking model.Booking) error {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for PublishBookingExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Booking) error); ok {
		r0 = rf(ctx, booking)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishBookingExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishBookingExpired'
type MockEventPublisher_PublishBookingExpired_Call struct {
	*mock.Call
}

// PublishBookingExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - booking model.Booking
func (_e *MockEventPublisher_Expecter) PublishBookingExpired(ctx interface{}, booking interface{}) *MockEventPublisher_PublishBookingExpired_Call {
	return &MockEventPublisher_PublishBookingExpired_Call{Call: _e.mock.On("PublishBookingExpired", ctx, booking)}
}

func (_c *MockEventPublisher_PublishBookingExpired_Call) Run(run func(ctx context.Context, booking model.Booking)) *MockEventPublisher_PublishBookingExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Booking))
	})
	return _c
}

func (_c *MockEventPublisher_PublishBookingExpired_Call) Return(_a0 error) *MockEventPublisher_PublishBookingExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishBookingExpired_Call) RunAndReturn(run func(context.Context, model.Booking) error) *MockEventPublisher_PublishBookingExpired_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
