// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockZoneChecker is an autogenerated mock type for the ZoneChecker type
type MockZoneChecker struct {
	mock.Mock
}

type MockZoneChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockZoneChecker) EXPECT() *MockZoneChecker_Expecter {
	return &MockZoneChecker_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: ctx, zoneID
func (_m *MockZoneChecker) Exists(ctx context.Context, zoneID string) (bool, error) {
	ret := _m.Called(ctx, zoneID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, zoneID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, zoneID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, zoneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZoneChecker_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockZoneChecker_Exists_Call struct {
	*mock.Call
}

func (_e *MockZoneChecker_Expecter) Exists(ctx interface{}, zoneID interface{}) *MockZoneChecker_Exists_Call {
	return &MockZoneChecker_Exists_Call{Call: _e.mock.On("Exists", ctx, zoneID)}
}

func (_c *MockZoneChecker_Exists_Call) Run(run func(ctx context.Context, zoneID string)) *MockZoneChecker_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockZoneChecker_Exists_Call) Return(_a0 bool, _a1 error) *MockZoneChecker_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZoneChecker_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockZoneChecker_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockZoneChecker creates a new instance of MockZoneChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockZoneChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockZoneChecker {
	mock := &MockZoneChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
