// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "carsharing/booking-service/internal/model"
	sharedmodel "carsharing/shared/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockBookingRepository is an autogenerated mock type for the BookingRepository type
type MockBookingRepository struct {
	mock.Mock
}

type MockBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepository) EXPECT() *MockBookingRepository_Expecter {
	return &MockBookingRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data, expiresAt
func (_m *MockBookingRepository) Create(ctx context.Context, data model.BookingCreate, expiresAt time.Time) (string, error) {
	ret := _m.Called(ctx, data, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BookingCreate, time.Time) (string, error)); ok {
		return rf(ctx, data, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.BookingCreate, time.Time) string); ok {
		r0 = rf(ctx, data, expiresAt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.BookingCreate, time.Time) error); ok {
		r1 = rf(ctx, data, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data model.BookingCreate
//   - expiresAt time.Time
func (_e *MockBookingRepository_Expecter) Create(ctx interface{}, data interface{}, expiresAt interface{}) *MockBookingRepository_Create_Call {
	return &MockBookingRepository_Create_Call{Call: _e.mock.On("Create", ctx, data, expiresAt)}
}

func (_c *MockBookingRepository_Create_Call) Run(run func(ctx context.Context, data model.BookingCreate, expiresAt time.Time)) *MockBookingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.BookingCreate), args[2].(time.Time))
	})
	return _c
}

func (_c *MockBookingRepository_Create_Call) Return(_a0 string, _a1 error) *MockBookingRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_Create_Call) RunAndReturn(run func(context.Context, model.BookingCreate, time.Time) (string, error)) *MockBookingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockBookingRepository) GetByID(ctx context.Context, id string) (model.Booking, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Booking, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Booking); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Booking)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBookingRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockBookingRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockBookingRepository_GetByID_Call {
	return &MockBookingRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBookingRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockBookingRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBookingRepository_GetByID_Call) Return(_a0 model.Booking, _a1 error) *MockBookingRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (model.Booking, error)) *MockBookingRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusHistory provides a mock function with given fields: ctx, filter
func (_m *MockBookingRepository) GetStatusHistory(ctx context.Context, filter model.BookingStatusHistoryFilter) ([]model.BookingStatusReading, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusHistory")
	}

	var r0 []model.BookingStatusReading
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BookingStatusHistoryFilter) ([]model.BookingStatusReading, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.BookingStatusHistoryFilter) []model.BookingStatusReading); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BookingStatusReading)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.BookingStatusHistoryFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_GetStatusHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusHistory'
type MockBookingRepository_GetStatusHistory_Call struct {
	*mock.Call
}

// GetStatusHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.BookingStatusHistoryFilter
func (_e *MockBookingRepository_Expecter) GetStatusHistory(ctx interface{}, filter interface{}) *MockBookingRepository_GetStatusHistory_Call {
	return &MockBookingRepository_GetStatusHistory_Call{Call: _e.mock.On("GetStatusHistory", ctx, filter)}
}

func (_c *MockBookingRepository_GetStatusHistory_Call) Run(run func(ctx context.Context, filter model.BookingStatusHistoryFilter)) *MockBookingRepository_GetStatusHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.BookingStatusHistoryFilter))
	})
	return _c
}

func (_c *MockBookingRepository_GetStatusHistory_Call) Return(_a0 []model.BookingStatusReading, _a1 error) *MockBookingRepository_GetStatusHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_GetStatusHistory_Call) RunAndReturn(run func(context.Context, model.BookingStatusHistoryFilter) ([]model.BookingStatusReading, error)) *MockBookingRepository_GetStatusHistory_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockBookingRepository) List(ctx context.Context, filter model.BookingListFilter) ([]model.Booking, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BookingListFilter) ([]model.Booking, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.BookingListFilter) []model.Booking); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.BookingListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBookingRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.BookingListFilter
func (_e *MockBookingRepository_Expecter) List(ctx interface{}, filter interface{}) *MockBookingRepository_List_Call {
	return &MockBookingRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockBookingRepository_List_Call) Run(run func(ctx context.Context, filter model.BookingListFilter)) *MockBookingRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.BookingListFilter))
	})
	return _c
}

func (_c *MockBookingRepository_List_Call) Return(_a0 []model.Booking, _a1 error) *MockBookingRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_List_Call) RunAndReturn(run func(context.Context, model.BookingListFilter) ([]model.Booking, error)) *MockBookingRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListCreatedExpired provides a mock function with given fields: ctx, now
func (_m *MockBookingRepository) ListCreatedExpired(ctx context.Context, now time.Time) ([]model.Booking, error) {
	ret := _m.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for ListCreatedExpired")
	}

	var r0 []model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]model.Booking, error)); ok {
		return rf(ctx, now)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []model.Booking); ok {
		r0 = rf(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, now)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingRepository_ListCreatedExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCreatedExpired'
type MockBookingRepository_ListCreatedExpired_Call struct {
	*mock.Call
}

// ListCreatedExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *MockBookingRepository_Expecter) ListCreatedExpired(ctx interface{}, now interface{}) *MockBookingRepository_ListCreatedExpired_Call {
	return &MockBookingRepository_ListCreatedExpired_Call{Call: _e.mock.On("ListCreatedExpired", ctx, now)}
}

func (_c *MockBookingRepository_ListCreatedExpired_Call) Run(run func(ctx context.Context, now time.Time)) *MockBookingRepository_ListCreatedExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockBookingRepository_ListCreatedExpired_Call) Return(_a0 []model.Booking, _a1 error) *MockBookingRepository_ListCreatedExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingRepository_ListCreatedExpired_Call) RunAndReturn(run func(context.Context, time.Time) ([]model.Booking, error)) *MockBookingRepository_ListCreatedExpired_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, actorType, actorID, reason
func (_m *MockBookingRepository) UpdateStatus(ctx context.Context, id string, status model.BookingStatus, actorType sharedmodel.ActorType, actorID *string, reason *string) error {
	ret := _m.Called(ctx, id, status, actorType, actorID, reason)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.BookingStatus, sharedmodel.ActorType, *string, *string) error); ok {
		r0 = rf(ctx, id, status, actorType, actorID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBookingRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockBookingRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status model.BookingStatus
//   - actorType sharedmodel.ActorType
//   - actorID *string
//   - reason *string
func (_e *MockBookingRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, actorType interface{}, actorID interface{}, reason interface{}) *MockBookingRepository_UpdateStatus_Call {
	return &MockBookingRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, actorType, actorID, reason)}
}

func (_c *MockBookingRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status model.BookingStatus, actorType sharedmodel.ActorType, actorID *string, reason *string)) *MockBookingRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.BookingStatus), args[3].(sharedmodel.ActorType), args[4].(*string), args[5].(*string))
	})
	return _c
}

func (_c *MockBookingRepository_UpdateStatus_Call) Return(_a0 error) *MockBookingRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBookingRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, model.BookingStatus, sharedmodel.ActorType, *string, *string) error) *MockBookingRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingRepository creates a new instance of MockBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepository {
	mock := &MockBookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
