// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "carsharing/car-service/internal/model"
	validation "carsharing/car-service/internal/validation"
	sharedmodel "carsharing/shared/model"
)

// MockCarModelService is an autogenerated mock type for the CarModelService type
type MockCarModelService struct {
	mock.Mock
}

type MockCarModelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarModelService) EXPECT() *MockCarModelService_Expecter {
	return &MockCarModelService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, createInput
func (_m *MockCarModelService) Create(ctx context.Context, createInput validation.CarModelCreate) (string, error) {
	ret := _m.Called(ctx, createInput)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarModelCreate) (string, error)); ok {
		return rf(ctx, createInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarModelCreate) string); ok {
		r0 = rf(ctx, createInput)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.CarModelCreate) error); ok {
		r1 = rf(ctx, createInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarModelService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCarModelService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - createInput validation.CarModelCreate
func (_e *MockCarModelService_Expecter) Create(ctx interface{}, createInput interface{}) *MockCarModelService_Create_Call {
	return &MockCarModelService_Create_Call{Call: _e.mock.On("Create", ctx, createInput)}
}

func (_c *MockCarModelService_Create_Call) Run(run func(ctx context.Context, createInput validation.CarModelCreate)) *MockCarModelService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarModelCreate))
	})
	return _c
}

func (_c *MockCarModelService_Create_Call) Return(_a0 string, _a1 error) *MockCarModelService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarModelService_Create_Call) RunAndReturn(run func(context.Context, validation.CarModelCreate) (string, error)) *MockCarModelService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCarModelService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarModelService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCarModelService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarModelService_Expecter) Delete(ctx interface{}, id interface{}) *MockCarModelService_Delete_Call {
	return &MockCarModelService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCarModelService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCarModelService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarModelService_Delete_Call) Return(_a0 error) *MockCarModelService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarModelService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCarModelService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockCarModelService) Get(ctx context.Context, id string) (model.CarModel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.CarModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CarModel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CarModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.CarModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarModelService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCarModelService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarModelService_Expecter) Get(ctx interface{}, id interface{}) *MockCarModelService_Get_Call {
	return &MockCarModelService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockCarModelService_Get_Call) Run(run func(ctx context.Context, id string)) *MockCarModelService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarModelService_Get_Call) Return(_a0 model.CarModel, _a1 error) *MockCarModelService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarModelService_Get_Call) RunAndReturn(run func(context.Context, string) (model.CarModel, error)) *MockCarModelService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, filterInput
func (_m *MockCarModelService) GetAll(ctx context.Context, filterInput validation.CarModelFilter) ([]model.CarModel, error) {
	ret := _m.Called(ctx, filterInput)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.CarModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarModelFilter) ([]model.CarModel, error)); ok {
		return rf(ctx, filterInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarModelFilter) []model.CarModel); ok {
		r0 = rf(ctx, filterInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.CarModelFilter) error); ok {
		r1 = rf(ctx, filterInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarModelService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockCarModelService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filterInput validation.CarModelFilter
func (_e *MockCarModelService_Expecter) GetAll(ctx interface{}, filterInput interface{}) *MockCarModelService_GetAll_Call {
	return &MockCarModelService_GetAll_Call{Call: _e.mock.On("GetAll", ctx, filterInput)}
}

func (_c *MockCarModelService_GetAll_Call) Run(run func(ctx context.Context, filterInput validation.CarModelFilter)) *MockCarModelService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarModelFilter))
	})
	return _c
}

func (_c *MockCarModelService_GetAll_Call) Return(_a0 []model.CarModel, _a1 error) *MockCarModelService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarModelService_GetAll_Call) RunAndReturn(run func(context.Context, validation.CarModelFilter) ([]model.CarModel, error)) *MockCarModelService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageUploadData provides a mock function with given fields: ctx
func (_m *MockCarModelService) GetImageUploadData(ctx context.Context) (sharedmodel.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImageUploadData")
	}

	var r0 sharedmodel.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (sharedmodel.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) sharedmodel.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(sharedmodel.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarModelService_GetImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageUploadData'
type MockCarModelService_GetImageUploadData_Call struct {
	*mock.Call
}

// GetImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCarModelService_Expecter) GetImageUploadData(ctx interface{}) *MockCarModelService_GetImageUploadData_Call {
	return &MockCarModelService_GetImageUploadData_Call{Call: _e.mock.On("GetImageUploadData", ctx)}
}

func (_c *MockCarModelService_GetImageUploadData_Call) Run(run func(ctx context.Context)) *MockCarModelService_GetImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCarModelService_GetImageUploadData_Call) Return(_a0 sharedmodel.ImageUploadData, _a1 error) *MockCarModelService_GetImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarModelService_GetImageUploadData_Call) RunAndReturn(run func(context.Context) (sharedmodel.ImageUploadData, error)) *MockCarModelService_GetImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updateInput
func (_m *MockCarModelService) Update(ctx context.Context, id string, updateInput validation.CarModelUpdate) error {
	ret := _m.Called(ctx, id, updateInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, validation.CarModelUpdate) error); ok {
		r0 = rf(ctx, id, updateInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarModelService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarModelService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - updateInput validation.CarModelUpdate
func (_e *MockCarModelService_Expecter) Update(ctx interface{}, id interface{}, updateInput interface{}) *MockCarModelService_Update_Call {
	return &MockCarModelService_Update_Call{Call: _e.mock.On("Update", ctx, id, updateInput)}
}

func (_c *MockCarModelService_Update_Call) Run(run func(ctx context.Context, id string, updateInput validation.CarModelUpdate)) *MockCarModelService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(validation.CarModelUpdate))
	})
	return _c
}

func (_c *MockCarModelService_Update_Call) Return(_a0 error) *MockCarModelService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarModelService_Update_Call) RunAndReturn(run func(context.Context, string, validation.CarModelUpdate) error) *MockCarModelService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarModelService creates a new instance of MockCarModelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarModelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarModelService {
	mock := &MockCarModelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
