// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "carsharing/car-service/internal/model"
	validation "carsharing/car-service/internal/validation"
	sharedmodel "carsharing/shared/model"
)

// MockCarService is an autogenerated mock type for the CarService type
type MockCarService struct {
	mock.Mock
}

type MockCarService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarService) EXPECT() *MockCarService_Expecter {
	return &MockCarService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, createInput
func (_m *MockCarService) Create(ctx context.Context, createInput validation.CarCreate) (string, error) {
	ret := _m.Called(ctx, createInput)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarCreate) (string, error)); ok {
		return rf(ctx, createInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarCreate) string); ok {
		r0 = rf(ctx, createInput)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.CarCreate) error); ok {
		r1 = rf(ctx, createInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCarService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - createInput validation.CarCreate
func (_e *MockCarService_Expecter) Create(ctx interface{}, createInput interface{}) *MockCarService_Create_Call {
	return &MockCarService_Create_Call{Call: _e.mock.On("Create", ctx, createInput)}
}

func (_c *MockCarService_Create_Call) Run(run func(ctx context.Context, createInput validation.CarCreate)) *MockCarService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarCreate))
	})
	return _c
}

func (_c *MockCarService_Create_Call) Return(_a0 string, _a1 error) *MockCarService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_Create_Call) RunAndReturn(run func(context.Context, validation.CarCreate) (string, error)) *MockCarService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCarService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCarService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarService_Expecter) Delete(ctx interface{}, id interface{}) *MockCarService_Delete_Call {
	return &MockCarService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCarService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCarService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarService_Delete_Call) Return(_a0 error) *MockCarService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCarService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockCarService) Get(ctx context.Context, id string) (model.Car, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Car
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Car, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Car); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Car)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCarService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarService_Expecter) Get(ctx interface{}, id interface{}) *MockCarService_Get_Call {
	return &MockCarService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockCarService_Get_Call) Run(run func(ctx context.Context, id string)) *MockCarService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarService_Get_Call) Return(_a0 model.Car, _a1 error) *MockCarService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_Get_Call) RunAndReturn(run func(context.Context, string) (model.Car, error)) *MockCarService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filterInput
func (_m *MockCarService) List(ctx context.Context, filterInput validation.CarFilter) ([]model.Car, error) {
	ret := _m.Called(ctx, filterInput)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Car
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarFilter) ([]model.Car, error)); ok {
		return rf(ctx, filterInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarFilter) []model.Car); ok {
		r0 = rf(ctx, filterInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Car)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.CarFilter) error); ok {
		r1 = rf(ctx, filterInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCarService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filterInput validation.CarFilter
func (_e *MockCarService_Expecter) List(ctx interface{}, filterInput interface{}) *MockCarService_List_Call {
	return &MockCarService_List_Call{Call: _e.mock.On("List", ctx, filterInput)}
}

func (_c *MockCarService_List_Call) Run(run func(ctx context.Context, filterInput validation.CarFilter)) *MockCarService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarFilter))
	})
	return _c
}

func (_c *MockCarService_List_Call) Return(_a0 []model.Car, _a1 error) *MockCarService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_List_Call) RunAndReturn(run func(context.Context, validation.CarFilter) ([]model.Car, error)) *MockCarService_List_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageUploadData provides a mock function with given fields: ctx
func (_m *MockCarService) GetImageUploadData(ctx context.Context) (sharedmodel.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImageUploadData")
	}

	var r0 sharedmodel.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (sharedmodel.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) sharedmodel.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(sharedmodel.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_GetImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageUploadData'
type MockCarService_GetImageUploadData_Call struct {
	*mock.Call
}

// GetImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCarService_Expecter) GetImageUploadData(ctx interface{}) *MockCarService_GetImageUploadData_Call {
	return &MockCarService_GetImageUploadData_Call{Call: _e.mock.On("GetImageUploadData", ctx)}
}

func (_c *MockCarService_GetImageUploadData_Call) Run(run func(ctx context.Context)) *MockCarService_GetImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCarService_GetImageUploadData_Call) Return(_a0 sharedmodel.ImageUploadData, _a1 error) *MockCarService_GetImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_GetImageUploadData_Call) RunAndReturn(run func(context.Context) (sharedmodel.ImageUploadData, error)) *MockCarService_GetImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updateInput
func (_m *MockCarService) Update(ctx context.Context, id string, updateInput validation.CarUpdate) error {
	ret := _m.Called(ctx, id, updateInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, validation.CarUpdate) error); ok {
		r0 = rf(ctx, id, updateInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - updateInput validation.CarUpdate
func (_e *MockCarService_Expecter) Update(ctx interface{}, id interface{}, updateInput interface{}) *MockCarService_Update_Call {
	return &MockCarService_Update_Call{Call: _e.mock.On("Update", ctx, id, updateInput)}
}

func (_c *MockCarService_Update_Call) Run(run func(ctx context.Context, id string, updateInput validation.CarUpdate)) *MockCarService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(validation.CarUpdate))
	})
	return _c
}

func (_c *MockCarService_Update_Call) Return(_a0 error) *MockCarService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarService_Update_Call) RunAndReturn(run func(context.Context, string, validation.CarUpdate) error) *MockCarService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCarStatus provides a mock function with given fields: ctx, id, statusInput
func (_m *MockCarService) UpdateCarStatus(ctx context.Context, id string, statusInput validation.CarStatusUpdate) error {
	ret := _m.Called(ctx, id, statusInput)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCarStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, validation.CarStatusUpdate) error); ok {
		r0 = rf(ctx, id, statusInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarService_UpdateCarStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCarStatus'
type MockCarService_UpdateCarStatus_Call struct {
	*mock.Call
}

// UpdateCarStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - statusInput validation.CarStatusUpdate
func (_e *MockCarService_Expecter) UpdateCarStatus(ctx interface{}, id interface{}, statusInput interface{}) *MockCarService_UpdateCarStatus_Call {
	return &MockCarService_UpdateCarStatus_Call{Call: _e.mock.On("UpdateCarStatus", ctx, id, statusInput)}
}

func (_c *MockCarService_UpdateCarStatus_Call) Run(run func(ctx context.Context, id string, statusInput validation.CarStatusUpdate)) *MockCarService_UpdateCarStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(validation.CarStatusUpdate))
	})
	return _c
}

func (_c *MockCarService_UpdateCarStatus_Call) Return(_a0 error) *MockCarService_UpdateCarStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarService_UpdateCarStatus_Call) RunAndReturn(run func(context.Context, string, validation.CarStatusUpdate) error) *MockCarService_UpdateCarStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCarTelemetry provides a mock function with given fields: ctx, id, data
func (_m *MockCarService) UpdateCarTelemetry(ctx context.Context, id string, data validation.CarTelemetryUpdate) error {
	ret := _m.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCarTelemetry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, validation.CarTelemetryUpdate) error); ok {
		r0 = rf(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarService_UpdateCarTelemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCarTelemetry'
type MockCarService_UpdateCarTelemetry_Call struct {
	*mock.Call
}

// UpdateCarTelemetry is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data validation.CarTelemetryUpdate
func (_e *MockCarService_Expecter) UpdateCarTelemetry(ctx interface{}, id interface{}, data interface{}) *MockCarService_UpdateCarTelemetry_Call {
	return &MockCarService_UpdateCarTelemetry_Call{Call: _e.mock.On("UpdateCarTelemetry", ctx, id, data)}
}

func (_c *MockCarService_UpdateCarTelemetry_Call) Run(run func(ctx context.Context, id string, data validation.CarTelemetryUpdate)) *MockCarService_UpdateCarTelemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(validation.CarTelemetryUpdate))
	})
	return _c
}

func (_c *MockCarService_UpdateCarTelemetry_Call) Return(_a0 error) *MockCarService_UpdateCarTelemetry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarService_UpdateCarTelemetry_Call) RunAndReturn(run func(context.Context, string, validation.CarTelemetryUpdate) error) *MockCarService_UpdateCarTelemetry_Call {
	_c.Call.Return(run)
	return _c
}

// ListCarStatusHistory provides a mock function with given fields: ctx, filter
func (_m *MockCarService) ListCarStatusHistory(ctx context.Context, filter validation.CarStatusReadingFilter) ([]model.CarStatusReading, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListCarStatusHistory")
	}

	var r0 []model.CarStatusReading
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarStatusReadingFilter) ([]model.CarStatusReading, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarStatusReadingFilter) []model.CarStatusReading); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarStatusReading)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.CarStatusReadingFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_ListCarStatusHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCarStatusHistory'
type MockCarService_ListCarStatusHistory_Call struct {
	*mock.Call
}

// ListCarStatusHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter validation.CarStatusReadingFilter
func (_e *MockCarService_Expecter) ListCarStatusHistory(ctx interface{}, filter interface{}) *MockCarService_ListCarStatusHistory_Call {
	return &MockCarService_ListCarStatusHistory_Call{Call: _e.mock.On("ListCarStatusHistory", ctx, filter)}
}

func (_c *MockCarService_ListCarStatusHistory_Call) Run(run func(ctx context.Context, filter validation.CarStatusReadingFilter)) *MockCarService_ListCarStatusHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarStatusReadingFilter))
	})
	return _c
}

func (_c *MockCarService_ListCarStatusHistory_Call) Return(_a0 []model.CarStatusReading, _a1 error) *MockCarService_ListCarStatusHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_ListCarStatusHistory_Call) RunAndReturn(run func(context.Context, validation.CarStatusReadingFilter) ([]model.CarStatusReading, error)) *MockCarService_ListCarStatusHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListCarTelemetryHistory provides a mock function with given fields: ctx, filter
func (_m *MockCarService) ListCarTelemetryHistory(ctx context.Context, filter validation.TelemetryReadingFilter) ([]model.TelemetryReading, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListCarTelemetryHistory")
	}

	var r0 []model.TelemetryReading
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.TelemetryReadingFilter) ([]model.TelemetryReading, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.TelemetryReadingFilter) []model.TelemetryReading); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TelemetryReading)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.TelemetryReadingFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_ListCarTelemetryHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCarTelemetryHistory'
type MockCarService_ListCarTelemetryHistory_Call struct {
	*mock.Call
}

// ListCarTelemetryHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter validation.TelemetryReadingFilter
func (_e *MockCarService_Expecter) ListCarTelemetryHistory(ctx interface{}, filter interface{}) *MockCarService_ListCarTelemetryHistory_Call {
	return &MockCarService_ListCarTelemetryHistory_Call{Call: _e.mock.On("ListCarTelemetryHistory", ctx, filter)}
}

func (_c *MockCarService_ListCarTelemetryHistory_Call) Run(run func(ctx context.Context, filter validation.TelemetryReadingFilter)) *MockCarService_ListCarTelemetryHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.TelemetryReadingFilter))
	})
	return _c
}

func (_c *MockCarService_ListCarTelemetryHistory_Call) Return(_a0 []model.TelemetryReading, _a1 error) *MockCarService_ListCarTelemetryHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_ListCarTelemetryHistory_Call) RunAndReturn(run func(context.Context, validation.TelemetryReadingFilter) ([]model.TelemetryReading, error)) *MockCarService_ListCarTelemetryHistory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarService creates a new instance of MockCarService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarService {
	mock := &MockCarService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
