// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "carsharing/car-service/internal/model"
	validation "carsharing/car-service/internal/validation"
	sharedmodel "carsharing/shared/model"
)

// MockCarMaintenanceService is an autogenerated mock type for the CarMaintenanceService type
type MockCarMaintenanceService struct {
	mock.Mock
}

type MockCarMaintenanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarMaintenanceService) EXPECT() *MockCarMaintenanceService_Expecter {
	return &MockCarMaintenanceService_Expecter{mock: &_m.Mock}
}

// CompleteRecord provides a mock function with given fields: ctx, id, completeInput
func (_m *MockCarMaintenanceService) CompleteRecord(ctx context.Context, id string, completeInput validation.CarMaintenanceRecordComplete) error {
	ret := _m.Called(ctx, id, completeInput)

	if len(ret) == 0 {
		panic("no return value specified for CompleteRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, validation.CarMaintenanceRecordComplete) error); ok {
		r0 = rf(ctx, id, completeInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceService_CompleteRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteRecord'
type MockCarMaintenanceService_CompleteRecord_Call struct {
	*mock.Call
}

// CompleteRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - completeInput validation.CarMaintenanceRecordComplete
func (_e *MockCarMaintenanceService_Expecter) CompleteRecord(ctx interface{}, id interface{}, completeInput interface{}) *MockCarMaintenanceService_CompleteRecord_Call {
	return &MockCarMaintenanceService_CompleteRecord_Call{Call: _e.mock.On("CompleteRecord", ctx, id, completeInput)}
}

func (_c *MockCarMaintenanceService_CompleteRecord_Call) Run(run func(ctx context.Context, id string, completeInput validation.CarMaintenanceRecordComplete)) *MockCarMaintenanceService_CompleteRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(validation.CarMaintenanceRecordComplete))
	})
	return _c
}

func (_c *MockCarMaintenanceService_CompleteRecord_Call) Return(_a0 error) *MockCarMaintenanceService_CompleteRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceService_CompleteRecord_Call) RunAndReturn(run func(context.Context, string, validation.CarMaintenanceRecordComplete) error) *MockCarMaintenanceService_CompleteRecord_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTemplate provides a mock function with given fields: ctx, createInput
func (_m *MockCarMaintenanceService) CreateTemplate(ctx context.Context, createInput validation.CarMaintenanceTemplateCreate) (string, error) {
	ret := _m.Called(ctx, createInput)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarMaintenanceTemplateCreate) (string, error)); ok {
		return rf(ctx, createInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarMaintenanceTemplateCreate) string); ok {
		r0 = rf(ctx, createInput)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.CarMaintenanceTemplateCreate) error); ok {
		r1 = rf(ctx, createInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceService_CreateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTemplate'
type MockCarMaintenanceService_CreateTemplate_Call struct {
	*mock.Call
}

// CreateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - createInput validation.CarMaintenanceTemplateCreate
func (_e *MockCarMaintenanceService_Expecter) CreateTemplate(ctx interface{}, createInput interface{}) *MockCarMaintenanceService_CreateTemplate_Call {
	return &MockCarMaintenanceService_CreateTemplate_Call{Call: _e.mock.On("CreateTemplate", ctx, createInput)}
}

func (_c *MockCarMaintenanceService_CreateTemplate_Call) Run(run func(ctx context.Context, createInput validation.CarMaintenanceTemplateCreate)) *MockCarMaintenanceService_CreateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarMaintenanceTemplateCreate))
	})
	return _c
}

func (_c *MockCarMaintenanceService_CreateTemplate_Call) Return(_a0 string, _a1 error) *MockCarMaintenanceService_CreateTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceService_CreateTemplate_Call) RunAndReturn(run func(context.Context, validation.CarMaintenanceTemplateCreate) (string, error)) *MockCarMaintenanceService_CreateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTemplate provides a mock function with given fields: ctx, id
func (_m *MockCarMaintenanceService) DeleteTemplate(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceService_DeleteTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTemplate'
type MockCarMaintenanceService_DeleteTemplate_Call struct {
	*mock.Call
}

// DeleteTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarMaintenanceService_Expecter) DeleteTemplate(ctx interface{}, id interface{}) *MockCarMaintenanceService_DeleteTemplate_Call {
	return &MockCarMaintenanceService_DeleteTemplate_Call{Call: _e.mock.On("DeleteTemplate", ctx, id)}
}

func (_c *MockCarMaintenanceService_DeleteTemplate_Call) Run(run func(ctx context.Context, id string)) *MockCarMaintenanceService_DeleteTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarMaintenanceService_DeleteTemplate_Call) Return(_a0 error) *MockCarMaintenanceService_DeleteTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceService_DeleteTemplate_Call) RunAndReturn(run func(context.Context, string) error) *MockCarMaintenanceService_DeleteTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ListTemplates provides a mock function with given fields: ctx, filterInput
func (_m *MockCarMaintenanceService) ListTemplates(ctx context.Context, filterInput validation.CarMaintenanceTemplateFilter) ([]model.CarMaintenanceTemplate, error) {
	ret := _m.Called(ctx, filterInput)

	if len(ret) == 0 {
		panic("no return value specified for ListTemplates")
	}

	var r0 []model.CarMaintenanceTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarMaintenanceTemplateFilter) ([]model.CarMaintenanceTemplate, error)); ok {
		return rf(ctx, filterInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarMaintenanceTemplateFilter) []model.CarMaintenanceTemplate); ok {
		r0 = rf(ctx, filterInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarMaintenanceTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.CarMaintenanceTemplateFilter) error); ok {
		r1 = rf(ctx, filterInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceService_ListTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTemplates'
type MockCarMaintenanceService_ListTemplates_Call struct {
	*mock.Call
}

// ListTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - filterInput validation.CarMaintenanceTemplateFilter
func (_e *MockCarMaintenanceService_Expecter) ListTemplates(ctx interface{}, filterInput interface{}) *MockCarMaintenanceService_ListTemplates_Call {
	return &MockCarMaintenanceService_ListTemplates_Call{Call: _e.mock.On("ListTemplates", ctx, filterInput)}
}

func (_c *MockCarMaintenanceService_ListTemplates_Call) Run(run func(ctx context.Context, filterInput validation.CarMaintenanceTemplateFilter)) *MockCarMaintenanceService_ListTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarMaintenanceTemplateFilter))
	})
	return _c
}

func (_c *MockCarMaintenanceService_ListTemplates_Call) Return(_a0 []model.CarMaintenanceTemplate, _a1 error) *MockCarMaintenanceService_ListTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceService_ListTemplates_Call) RunAndReturn(run func(context.Context, validation.CarMaintenanceTemplateFilter) ([]model.CarMaintenanceTemplate, error)) *MockCarMaintenanceService_ListTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// GetReceiptImageUploadData provides a mock function with given fields: ctx
func (_m *MockCarMaintenanceService) GetReceiptImageUploadData(ctx context.Context) (sharedmodel.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReceiptImageUploadData")
	}

	var r0 sharedmodel.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (sharedmodel.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) sharedmodel.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(sharedmodel.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceService_GetReceiptImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReceiptImageUploadData'
type MockCarMaintenanceService_GetReceiptImageUploadData_Call struct {
	*mock.Call
}

// GetReceiptImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCarMaintenanceService_Expecter) GetReceiptImageUploadData(ctx interface{}) *MockCarMaintenanceService_GetReceiptImageUploadData_Call {
	return &MockCarMaintenanceService_GetReceiptImageUploadData_Call{Call: _e.mock.On("GetReceiptImageUploadData", ctx)}
}

func (_c *MockCarMaintenanceService_GetReceiptImageUploadData_Call) Run(run func(ctx context.Context)) *MockCarMaintenanceService_GetReceiptImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCarMaintenanceService_GetReceiptImageUploadData_Call) Return(_a0 sharedmodel.ImageUploadData, _a1 error) *MockCarMaintenanceService_GetReceiptImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceService_GetReceiptImageUploadData_Call) RunAndReturn(run func(context.Context) (sharedmodel.ImageUploadData, error)) *MockCarMaintenanceService_GetReceiptImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecords provides a mock function with given fields: ctx, filterInput
func (_m *MockCarMaintenanceService) ListRecords(ctx context.Context, filterInput validation.CarMaintenanceRecordFilter) ([]model.CarMaintenanceRecord, error) {
	ret := _m.Called(ctx, filterInput)

	if len(ret) == 0 {
		panic("no return value specified for ListRecords")
	}

	var r0 []model.CarMaintenanceRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarMaintenanceRecordFilter) ([]model.CarMaintenanceRecord, error)); ok {
		return rf(ctx, filterInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarMaintenanceRecordFilter) []model.CarMaintenanceRecord); ok {
		r0 = rf(ctx, filterInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarMaintenanceRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.CarMaintenanceRecordFilter) error); ok {
		r1 = rf(ctx, filterInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceService_ListRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecords'
type MockCarMaintenanceService_ListRecords_Call struct {
	*mock.Call
}

// ListRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - filterInput validation.CarMaintenanceRecordFilter
func (_e *MockCarMaintenanceService_Expecter) ListRecords(ctx interface{}, filterInput interface{}) *MockCarMaintenanceService_ListRecords_Call {
	return &MockCarMaintenanceService_ListRecords_Call{Call: _e.mock.On("ListRecords", ctx, filterInput)}
}

func (_c *MockCarMaintenanceService_ListRecords_Call) Run(run func(ctx context.Context, filterInput validation.CarMaintenanceRecordFilter)) *MockCarMaintenanceService_ListRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarMaintenanceRecordFilter))
	})
	return _c
}

func (_c *MockCarMaintenanceService_ListRecords_Call) Return(_a0 []model.CarMaintenanceRecord, _a1 error) *MockCarMaintenanceService_ListRecords_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceService_ListRecords_Call) RunAndReturn(run func(context.Context, validation.CarMaintenanceRecordFilter) ([]model.CarMaintenanceRecord, error)) *MockCarMaintenanceService_ListRecords_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function with given fields: ctx, id
func (_m *MockCarMaintenanceService) GetTemplate(ctx context.Context, id string) (model.CarMaintenanceTemplate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 model.CarMaintenanceTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CarMaintenanceTemplate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CarMaintenanceTemplate); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.CarMaintenanceTemplate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceService_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type MockCarMaintenanceService_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarMaintenanceService_Expecter) GetTemplate(ctx interface{}, id interface{}) *MockCarMaintenanceService_GetTemplate_Call {
	return &MockCarMaintenanceService_GetTemplate_Call{Call: _e.mock.On("GetTemplate", ctx, id)}
}

func (_c *MockCarMaintenanceService_GetTemplate_Call) Run(run func(ctx context.Context, id string)) *MockCarMaintenanceService_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarMaintenanceService_GetTemplate_Call) Return(_a0 model.CarMaintenanceTemplate, _a1 error) *MockCarMaintenanceService_GetTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceService_GetTemplate_Call) RunAndReturn(run func(context.Context, string) (model.CarMaintenanceTemplate, error)) *MockCarMaintenanceService_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTemplate provides a mock function with given fields: ctx, id, updateInput
func (_m *MockCarMaintenanceService) UpdateTemplate(ctx context.Context, id string, updateInput validation.CarMaintenanceTemplateUpdate) error {
	ret := _m.Called(ctx, id, updateInput)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, validation.CarMaintenanceTemplateUpdate) error); ok {
		r0 = rf(ctx, id, updateInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceService_UpdateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTemplate'
type MockCarMaintenanceService_UpdateTemplate_Call struct {
	*mock.Call
}

// UpdateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - updateInput validation.CarMaintenanceTemplateUpdate
func (_e *MockCarMaintenanceService_Expecter) UpdateTemplate(ctx interface{}, id interface{}, updateInput interface{}) *MockCarMaintenanceService_UpdateTemplate_Call {
	return &MockCarMaintenanceService_UpdateTemplate_Call{Call: _e.mock.On("UpdateTemplate", ctx, id, updateInput)}
}

func (_c *MockCarMaintenanceService_UpdateTemplate_Call) Run(run func(ctx context.Context, id string, updateInput validation.CarMaintenanceTemplateUpdate)) *MockCarMaintenanceService_UpdateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(validation.CarMaintenanceTemplateUpdate))
	})
	return _c
}

func (_c *MockCarMaintenanceService_UpdateTemplate_Call) Return(_a0 error) *MockCarMaintenanceService_UpdateTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceService_UpdateTemplate_Call) RunAndReturn(run func(context.Context, string, validation.CarMaintenanceTemplateUpdate) error) *MockCarMaintenanceService_UpdateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// AssignCarTemplate provides a mock function with given fields: ctx, data
func (_m *MockCarMaintenanceService) AssignCarTemplate(ctx context.Context, data validation.CarTemplateAssign) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AssignCarTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarTemplateAssign) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceService_AssignCarTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignCarTemplate'
type MockCarMaintenanceService_AssignCarTemplate_Call struct {
	*mock.Call
}

// AssignCarTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - data validation.CarTemplateAssign
func (_e *MockCarMaintenanceService_Expecter) AssignCarTemplate(ctx interface{}, data interface{}) *MockCarMaintenanceService_AssignCarTemplate_Call {
	return &MockCarMaintenanceService_AssignCarTemplate_Call{Call: _e.mock.On("AssignCarTemplate", ctx, data)}
}

func (_c *MockCarMaintenanceService_AssignCarTemplate_Call) Run(run func(ctx context.Context, data validation.CarTemplateAssign)) *MockCarMaintenanceService_AssignCarTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarTemplateAssign))
	})
	return _c
}

func (_c *MockCarMaintenanceService_AssignCarTemplate_Call) Return(_a0 error) *MockCarMaintenanceService_AssignCarTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceService_AssignCarTemplate_Call) RunAndReturn(run func(context.Context, validation.CarTemplateAssign) error) *MockCarMaintenanceService_AssignCarTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarMaintenanceService creates a new instance of MockCarMaintenanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarMaintenanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarMaintenanceService {
	mock := &MockCarMaintenanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
