// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/sorawaslocked/car-rental-car-service/internal/model"
)

// MockCarMaintenanceService is an autogenerated mock type for the CarMaintenanceService type
type MockCarMaintenanceService struct {
	mock.Mock
}

type MockCarMaintenanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarMaintenanceService) EXPECT() *MockCarMaintenanceService_Expecter {
	return &MockCarMaintenanceService_Expecter{mock: &_m.Mock}
}

// CompleteRecord provides a mock function with given fields: ctx, id, completeInput
func (_m *MockCarMaintenanceService) CompleteRecord(ctx context.Context, id string, completeInput model.CarMaintenanceRecordCompleteInput) error {
	ret := _m.Called(ctx, id, completeInput)

	if len(ret) == 0 {
		panic("no return value specified for CompleteRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarMaintenanceRecordCompleteInput) error); ok {
		r0 = rf(ctx, id, completeInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceService_CompleteRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteRecord'
type MockCarMaintenanceService_CompleteRecord_Call struct {
	*mock.Call
}

// CompleteRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - completeInput model.CarMaintenanceRecordCompleteInput
func (_e *MockCarMaintenanceService_Expecter) CompleteRecord(ctx interface{}, id interface{}, completeInput interface{}) *MockCarMaintenanceService_CompleteRecord_Call {
	return &MockCarMaintenanceService_CompleteRecord_Call{Call: _e.mock.On("CompleteRecord", ctx, id, completeInput)}
}

func (_c *MockCarMaintenanceService_CompleteRecord_Call) Run(run func(ctx context.Context, id string, completeInput model.CarMaintenanceRecordCompleteInput)) *MockCarMaintenanceService_CompleteRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarMaintenanceRecordCompleteInput))
	})
	return _c
}

func (_c *MockCarMaintenanceService_CompleteRecord_Call) Return(_a0 error) *MockCarMaintenanceService_CompleteRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceService_CompleteRecord_Call) RunAndReturn(run func(context.Context, string, model.CarMaintenanceRecordCompleteInput) error) *MockCarMaintenanceService_CompleteRecord_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTemplate provides a mock function with given fields: ctx, createInput
func (_m *MockCarMaintenanceService) CreateTemplate(ctx context.Context, createInput model.CarMaintenanceTemplateCreateInput) (string, error) {
	ret := _m.Called(ctx, createInput)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceTemplateCreateInput) (string, error)); ok {
		return rf(ctx, createInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceTemplateCreateInput) string); ok {
		r0 = rf(ctx, createInput)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarMaintenanceTemplateCreateInput) error); ok {
		r1 = rf(ctx, createInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceService_CreateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTemplate'
type MockCarMaintenanceService_CreateTemplate_Call struct {
	*mock.Call
}

// CreateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - createInput model.CarMaintenanceTemplateCreateInput
func (_e *MockCarMaintenanceService_Expecter) CreateTemplate(ctx interface{}, createInput interface{}) *MockCarMaintenanceService_CreateTemplate_Call {
	return &MockCarMaintenanceService_CreateTemplate_Call{Call: _e.mock.On("CreateTemplate", ctx, createInput)}
}

func (_c *MockCarMaintenanceService_CreateTemplate_Call) Run(run func(ctx context.Context, createInput model.CarMaintenanceTemplateCreateInput)) *MockCarMaintenanceService_CreateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarMaintenanceTemplateCreateInput))
	})
	return _c
}

func (_c *MockCarMaintenanceService_CreateTemplate_Call) Return(_a0 string, _a1 error) *MockCarMaintenanceService_CreateTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceService_CreateTemplate_Call) RunAndReturn(run func(context.Context, model.CarMaintenanceTemplateCreateInput) (string, error)) *MockCarMaintenanceService_CreateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTemplate provides a mock function with given fields: ctx, id
func (_m *MockCarMaintenanceService) DeleteTemplate(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceService_DeleteTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTemplate'
type MockCarMaintenanceService_DeleteTemplate_Call struct {
	*mock.Call
}

// DeleteTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarMaintenanceService_Expecter) DeleteTemplate(ctx interface{}, id interface{}) *MockCarMaintenanceService_DeleteTemplate_Call {
	return &MockCarMaintenanceService_DeleteTemplate_Call{Call: _e.mock.On("DeleteTemplate", ctx, id)}
}

func (_c *MockCarMaintenanceService_DeleteTemplate_Call) Run(run func(ctx context.Context, id string)) *MockCarMaintenanceService_DeleteTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarMaintenanceService_DeleteTemplate_Call) Return(_a0 error) *MockCarMaintenanceService_DeleteTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceService_DeleteTemplate_Call) RunAndReturn(run func(context.Context, string) error) *MockCarMaintenanceService_DeleteTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTemplates provides a mock function with given fields: ctx, filterInput
func (_m *MockCarMaintenanceService) GetAllTemplates(ctx context.Context, filterInput model.CarMaintenanceTemplateFilterInput) ([]model.CarMaintenanceTemplate, error) {
	ret := _m.Called(ctx, filterInput)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTemplates")
	}

	var r0 []model.CarMaintenanceTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceTemplateFilterInput) ([]model.CarMaintenanceTemplate, error)); ok {
		return rf(ctx, filterInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceTemplateFilterInput) []model.CarMaintenanceTemplate); ok {
		r0 = rf(ctx, filterInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarMaintenanceTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarMaintenanceTemplateFilterInput) error); ok {
		r1 = rf(ctx, filterInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceService_GetAllTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTemplates'
type MockCarMaintenanceService_GetAllTemplates_Call struct {
	*mock.Call
}

// GetAllTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - filterInput model.CarMaintenanceTemplateFilterInput
func (_e *MockCarMaintenanceService_Expecter) GetAllTemplates(ctx interface{}, filterInput interface{}) *MockCarMaintenanceService_GetAllTemplates_Call {
	return &MockCarMaintenanceService_GetAllTemplates_Call{Call: _e.mock.On("GetAllTemplates", ctx, filterInput)}
}

func (_c *MockCarMaintenanceService_GetAllTemplates_Call) Run(run func(ctx context.Context, filterInput model.CarMaintenanceTemplateFilterInput)) *MockCarMaintenanceService_GetAllTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarMaintenanceTemplateFilterInput))
	})
	return _c
}

func (_c *MockCarMaintenanceService_GetAllTemplates_Call) Return(_a0 []model.CarMaintenanceTemplate, _a1 error) *MockCarMaintenanceService_GetAllTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceService_GetAllTemplates_Call) RunAndReturn(run func(context.Context, model.CarMaintenanceTemplateFilterInput) ([]model.CarMaintenanceTemplate, error)) *MockCarMaintenanceService_GetAllTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// GetReceiptImageUploadData provides a mock function with given fields: ctx
func (_m *MockCarMaintenanceService) GetReceiptImageUploadData(ctx context.Context) (model.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReceiptImageUploadData")
	}

	var r0 model.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceService_GetReceiptImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReceiptImageUploadData'
type MockCarMaintenanceService_GetReceiptImageUploadData_Call struct {
	*mock.Call
}

// GetReceiptImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCarMaintenanceService_Expecter) GetReceiptImageUploadData(ctx interface{}) *MockCarMaintenanceService_GetReceiptImageUploadData_Call {
	return &MockCarMaintenanceService_GetReceiptImageUploadData_Call{Call: _e.mock.On("GetReceiptImageUploadData", ctx)}
}

func (_c *MockCarMaintenanceService_GetReceiptImageUploadData_Call) Run(run func(ctx context.Context)) *MockCarMaintenanceService_GetReceiptImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCarMaintenanceService_GetReceiptImageUploadData_Call) Return(_a0 model.ImageUploadData, _a1 error) *MockCarMaintenanceService_GetReceiptImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceService_GetReceiptImageUploadData_Call) RunAndReturn(run func(context.Context) (model.ImageUploadData, error)) *MockCarMaintenanceService_GetReceiptImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecords provides a mock function with given fields: ctx, filterInput
func (_m *MockCarMaintenanceService) GetRecords(ctx context.Context, filterInput model.CarMaintenanceRecordFilterInput) ([]model.CarMaintenanceRecord, error) {
	ret := _m.Called(ctx, filterInput)

	if len(ret) == 0 {
		panic("no return value specified for GetRecords")
	}

	var r0 []model.CarMaintenanceRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceRecordFilterInput) ([]model.CarMaintenanceRecord, error)); ok {
		return rf(ctx, filterInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarMaintenanceRecordFilterInput) []model.CarMaintenanceRecord); ok {
		r0 = rf(ctx, filterInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarMaintenanceRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarMaintenanceRecordFilterInput) error); ok {
		r1 = rf(ctx, filterInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceService_GetRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecords'
type MockCarMaintenanceService_GetRecords_Call struct {
	*mock.Call
}

// GetRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - filterInput model.CarMaintenanceRecordFilterInput
func (_e *MockCarMaintenanceService_Expecter) GetRecords(ctx interface{}, filterInput interface{}) *MockCarMaintenanceService_GetRecords_Call {
	return &MockCarMaintenanceService_GetRecords_Call{Call: _e.mock.On("GetRecords", ctx, filterInput)}
}

func (_c *MockCarMaintenanceService_GetRecords_Call) Run(run func(ctx context.Context, filterInput model.CarMaintenanceRecordFilterInput)) *MockCarMaintenanceService_GetRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarMaintenanceRecordFilterInput))
	})
	return _c
}

func (_c *MockCarMaintenanceService_GetRecords_Call) Return(_a0 []model.CarMaintenanceRecord, _a1 error) *MockCarMaintenanceService_GetRecords_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceService_GetRecords_Call) RunAndReturn(run func(context.Context, model.CarMaintenanceRecordFilterInput) ([]model.CarMaintenanceRecord, error)) *MockCarMaintenanceService_GetRecords_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplate provides a mock function with given fields: ctx, id
func (_m *MockCarMaintenanceService) GetTemplate(ctx context.Context, id string) (model.CarMaintenanceTemplate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplate")
	}

	var r0 model.CarMaintenanceTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CarMaintenanceTemplate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CarMaintenanceTemplate); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.CarMaintenanceTemplate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarMaintenanceService_GetTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplate'
type MockCarMaintenanceService_GetTemplate_Call struct {
	*mock.Call
}

// GetTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarMaintenanceService_Expecter) GetTemplate(ctx interface{}, id interface{}) *MockCarMaintenanceService_GetTemplate_Call {
	return &MockCarMaintenanceService_GetTemplate_Call{Call: _e.mock.On("GetTemplate", ctx, id)}
}

func (_c *MockCarMaintenanceService_GetTemplate_Call) Run(run func(ctx context.Context, id string)) *MockCarMaintenanceService_GetTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarMaintenanceService_GetTemplate_Call) Return(_a0 model.CarMaintenanceTemplate, _a1 error) *MockCarMaintenanceService_GetTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarMaintenanceService_GetTemplate_Call) RunAndReturn(run func(context.Context, string) (model.CarMaintenanceTemplate, error)) *MockCarMaintenanceService_GetTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTemplate provides a mock function with given fields: ctx, id, updateInput
func (_m *MockCarMaintenanceService) UpdateTemplate(ctx context.Context, id string, updateInput model.CarMaintenanceTemplateUpdateInput) error {
	ret := _m.Called(ctx, id, updateInput)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarMaintenanceTemplateUpdateInput) error); ok {
		r0 = rf(ctx, id, updateInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarMaintenanceService_UpdateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTemplate'
type MockCarMaintenanceService_UpdateTemplate_Call struct {
	*mock.Call
}

// UpdateTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - updateInput model.CarMaintenanceTemplateUpdateInput
func (_e *MockCarMaintenanceService_Expecter) UpdateTemplate(ctx interface{}, id interface{}, updateInput interface{}) *MockCarMaintenanceService_UpdateTemplate_Call {
	return &MockCarMaintenanceService_UpdateTemplate_Call{Call: _e.mock.On("UpdateTemplate", ctx, id, updateInput)}
}

func (_c *MockCarMaintenanceService_UpdateTemplate_Call) Run(run func(ctx context.Context, id string, updateInput model.CarMaintenanceTemplateUpdateInput)) *MockCarMaintenanceService_UpdateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarMaintenanceTemplateUpdateInput))
	})
	return _c
}

func (_c *MockCarMaintenanceService_UpdateTemplate_Call) Return(_a0 error) *MockCarMaintenanceService_UpdateTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarMaintenanceService_UpdateTemplate_Call) RunAndReturn(run func(context.Context, string, model.CarMaintenanceTemplateUpdateInput) error) *MockCarMaintenanceService_UpdateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarMaintenanceService creates a new instance of MockCarMaintenanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarMaintenanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarMaintenanceService {
	mock := &MockCarMaintenanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
