// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "carsharing/car-service/internal/model"
	validation "carsharing/car-service/internal/validation"
)

// MockZoneService is an autogenerated mock type for the ZoneService type
type MockZoneService struct {
	mock.Mock
}

type MockZoneService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockZoneService) EXPECT() *MockZoneService_Expecter {
	return &MockZoneService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, createInput
func (_m *MockZoneService) Create(ctx context.Context, createInput validation.ZoneCreate) (string, error) {
	ret := _m.Called(ctx, createInput)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.ZoneCreate) (string, error)); ok {
		return rf(ctx, createInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.ZoneCreate) string); ok {
		r0 = rf(ctx, createInput)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.ZoneCreate) error); ok {
		r1 = rf(ctx, createInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZoneService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockZoneService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - createInput validation.ZoneCreate
func (_e *MockZoneService_Expecter) Create(ctx interface{}, createInput interface{}) *MockZoneService_Create_Call {
	return &MockZoneService_Create_Call{Call: _e.mock.On("Create", ctx, createInput)}
}

func (_c *MockZoneService_Create_Call) Run(run func(ctx context.Context, createInput validation.ZoneCreate)) *MockZoneService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.ZoneCreate))
	})
	return _c
}

func (_c *MockZoneService_Create_Call) Return(_a0 string, _a1 error) *MockZoneService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZoneService_Create_Call) RunAndReturn(run func(context.Context, validation.ZoneCreate) (string, error)) *MockZoneService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockZoneService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockZoneService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockZoneService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockZoneService_Expecter) Delete(ctx interface{}, id interface{}) *MockZoneService_Delete_Call {
	return &MockZoneService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockZoneService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockZoneService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockZoneService_Delete_Call) Return(_a0 error) *MockZoneService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockZoneService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockZoneService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockZoneService) Get(ctx context.Context, id string) (model.Zone, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Zone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Zone, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Zone); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Zone)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZoneService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockZoneService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockZoneService_Expecter) Get(ctx interface{}, id interface{}) *MockZoneService_Get_Call {
	return &MockZoneService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockZoneService_Get_Call) Run(run func(ctx context.Context, id string)) *MockZoneService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockZoneService_Get_Call) Return(_a0 model.Zone, _a1 error) *MockZoneService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZoneService_Get_Call) RunAndReturn(run func(context.Context, string) (model.Zone, error)) *MockZoneService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, filterInput
func (_m *MockZoneService) GetAll(ctx context.Context, filterInput validation.ZoneFilter) ([]model.Zone, error) {
	ret := _m.Called(ctx, filterInput)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Zone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.ZoneFilter) ([]model.Zone, error)); ok {
		return rf(ctx, filterInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.ZoneFilter) []model.Zone); ok {
		r0 = rf(ctx, filterInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Zone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.ZoneFilter) error); ok {
		r1 = rf(ctx, filterInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockZoneService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockZoneService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filterInput validation.ZoneFilter
func (_e *MockZoneService_Expecter) GetAll(ctx interface{}, filterInput interface{}) *MockZoneService_GetAll_Call {
	return &MockZoneService_GetAll_Call{Call: _e.mock.On("GetAll", ctx, filterInput)}
}

func (_c *MockZoneService_GetAll_Call) Run(run func(ctx context.Context, filterInput validation.ZoneFilter)) *MockZoneService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.ZoneFilter))
	})
	return _c
}

func (_c *MockZoneService_GetAll_Call) Return(_a0 []model.Zone, _a1 error) *MockZoneService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockZoneService_GetAll_Call) RunAndReturn(run func(context.Context, validation.ZoneFilter) ([]model.Zone, error)) *MockZoneService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updateInput
func (_m *MockZoneService) Update(ctx context.Context, id string, updateInput validation.ZoneUpdate) error {
	ret := _m.Called(ctx, id, updateInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, validation.ZoneUpdate) error); ok {
		r0 = rf(ctx, id, updateInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockZoneService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockZoneService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - updateInput validation.ZoneUpdate
func (_e *MockZoneService_Expecter) Update(ctx interface{}, id interface{}, updateInput interface{}) *MockZoneService_Update_Call {
	return &MockZoneService_Update_Call{Call: _e.mock.On("Update", ctx, id, updateInput)}
}

func (_c *MockZoneService_Update_Call) Run(run func(ctx context.Context, id string, updateInput validation.ZoneUpdate)) *MockZoneService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(validation.ZoneUpdate))
	})
	return _c
}

func (_c *MockZoneService_Update_Call) Return(_a0 error) *MockZoneService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockZoneService_Update_Call) RunAndReturn(run func(context.Context, string, validation.ZoneUpdate) error) *MockZoneService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockZoneService creates a new instance of MockZoneService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockZoneService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockZoneService {
	mock := &MockZoneService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
