// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/sorawaslocked/car-rental-car-service/internal/model"
)

// MockTelematicsSubscriber is an autogenerated mock type for the TelematicsSubscriber type
type MockTelematicsSubscriber struct {
	mock.Mock
}

type MockTelematicsSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelematicsSubscriber) EXPECT() *MockTelematicsSubscriber_Expecter {
	return &MockTelematicsSubscriber_Expecter{mock: &_m.Mock}
}

// SubscribeCarStream provides a mock function with given fields: ctx, carID
func (_m *MockTelematicsSubscriber) SubscribeCarStream(ctx context.Context, carID string) (<-chan model.TelematicsUpdate, error) {
	ret := _m.Called(ctx, carID)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeCarStream")
	}

	var r0 <-chan model.TelematicsUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (<-chan model.TelematicsUpdate, error)); ok {
		return rf(ctx, carID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan model.TelematicsUpdate); ok {
		r0 = rf(ctx, carID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.TelematicsUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, carID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTelematicsSubscriber_SubscribeCarStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeCarStream'
type MockTelematicsSubscriber_SubscribeCarStream_Call struct {
	*mock.Call
}

// SubscribeCarStream is a helper method to define mock.On call
//   - ctx context.Context
//   - carID string
func (_e *MockTelematicsSubscriber_Expecter) SubscribeCarStream(ctx interface{}, carID interface{}) *MockTelematicsSubscriber_SubscribeCarStream_Call {
	return &MockTelematicsSubscriber_SubscribeCarStream_Call{Call: _e.mock.On("SubscribeCarStream", ctx, carID)}
}

func (_c *MockTelematicsSubscriber_SubscribeCarStream_Call) Run(run func(ctx context.Context, carID string)) *MockTelematicsSubscriber_SubscribeCarStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTelematicsSubscriber_SubscribeCarStream_Call) Return(_a0 <-chan model.TelematicsUpdate, _a1 error) *MockTelematicsSubscriber_SubscribeCarStream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTelematicsSubscriber_SubscribeCarStream_Call) RunAndReturn(run func(context.Context, string) (<-chan model.TelematicsUpdate, error)) *MockTelematicsSubscriber_SubscribeCarStream_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTelematicsSubscriber creates a new instance of MockTelematicsSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelematicsSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelematicsSubscriber {
	mock := &MockTelematicsSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
