// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDBPinger is an autogenerated mock type for the DBPinger type
type MockDBPinger struct {
	mock.Mock
}

type MockDBPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBPinger) EXPECT() *MockDBPinger_Expecter {
	return &MockDBPinger_Expecter{mock: &_m.Mock}
}

// PingContext provides a mock function with given fields: ctx
func (_m *MockDBPinger) PingContext(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PingContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDBPinger_PingContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingContext'
type MockDBPinger_PingContext_Call struct {
	*mock.Call
}

// PingContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDBPinger_Expecter) PingContext(ctx interface{}) *MockDBPinger_PingContext_Call {
	return &MockDBPinger_PingContext_Call{Call: _e.mock.On("PingContext", ctx)}
}

func (_c *MockDBPinger_PingContext_Call) Run(run func(ctx context.Context)) *MockDBPinger_PingContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDBPinger_PingContext_Call) Return(_a0 error) *MockDBPinger_PingContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBPinger_PingContext_Call) RunAndReturn(run func(context.Context) error) *MockDBPinger_PingContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBPinger creates a new instance of MockDBPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBPinger {
	mock := &MockDBPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
