// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "carsharing/car-service/internal/model"
)

// MockTelemetrySubscriber is an autogenerated mock type for the TelemetrySubscriber type
type MockTelemetrySubscriber struct {
	mock.Mock
}

type MockTelemetrySubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelemetrySubscriber) EXPECT() *MockTelemetrySubscriber_Expecter {
	return &MockTelemetrySubscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: ctx, car
func (_m *MockTelemetrySubscriber) Subscribe(ctx context.Context, car model.Car) (<-chan model.TelemetryUpdate, error) {
	ret := _m.Called(ctx, car)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan model.TelemetryUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Car) (<-chan model.TelemetryUpdate, error)); ok {
		return rf(ctx, car)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Car) <-chan model.TelemetryUpdate); ok {
		r0 = rf(ctx, car)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.TelemetryUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Car) error); ok {
		r1 = rf(ctx, car)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTelemetrySubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockTelemetrySubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - car model.Car
func (_e *MockTelemetrySubscriber_Expecter) Subscribe(ctx interface{}, car interface{}) *MockTelemetrySubscriber_Subscribe_Call {
	return &MockTelemetrySubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, car)}
}

func (_c *MockTelemetrySubscriber_Subscribe_Call) Run(run func(ctx context.Context, car model.Car)) *MockTelemetrySubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Car))
	})
	return _c
}

func (_c *MockTelemetrySubscriber_Subscribe_Call) Return(_a0 <-chan model.TelemetryUpdate, _a1 error) *MockTelemetrySubscriber_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTelemetrySubscriber_Subscribe_Call) RunAndReturn(run func(context.Context, model.Car) (<-chan model.TelemetryUpdate, error)) *MockTelemetrySubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTelemetrySubscriber creates a new instance of MockTelemetrySubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelemetrySubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelemetrySubscriber {
	mock := &MockTelemetrySubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
