// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "carsharing/car-service/internal/model"
)

// MockCarService is an autogenerated mock type for the CarService type
type MockCarService struct {
	mock.Mock
}

type MockCarService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarService) EXPECT() *MockCarService_Expecter {
	return &MockCarService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, createInput
func (_m *MockCarService) Create(ctx context.Context, createInput model.CarCreateInput) (string, error) {
	ret := _m.Called(ctx, createInput)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarCreateInput) (string, error)); ok {
		return rf(ctx, createInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarCreateInput) string); ok {
		r0 = rf(ctx, createInput)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarCreateInput) error); ok {
		r1 = rf(ctx, createInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCarService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - createInput model.CarCreateInput
func (_e *MockCarService_Expecter) Create(ctx interface{}, createInput interface{}) *MockCarService_Create_Call {
	return &MockCarService_Create_Call{Call: _e.mock.On("Create", ctx, createInput)}
}

func (_c *MockCarService_Create_Call) Run(run func(ctx context.Context, createInput model.CarCreateInput)) *MockCarService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarCreateInput))
	})
	return _c
}

func (_c *MockCarService_Create_Call) Return(_a0 string, _a1 error) *MockCarService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_Create_Call) RunAndReturn(run func(context.Context, model.CarCreateInput) (string, error)) *MockCarService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCarService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCarService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarService_Expecter) Delete(ctx interface{}, id interface{}) *MockCarService_Delete_Call {
	return &MockCarService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCarService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCarService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarService_Delete_Call) Return(_a0 error) *MockCarService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCarService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockCarService) Get(ctx context.Context, id string) (model.Car, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Car
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Car, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Car); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Car)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCarService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarService_Expecter) Get(ctx interface{}, id interface{}) *MockCarService_Get_Call {
	return &MockCarService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockCarService_Get_Call) Run(run func(ctx context.Context, id string)) *MockCarService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarService_Get_Call) Return(_a0 model.Car, _a1 error) *MockCarService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_Get_Call) RunAndReturn(run func(context.Context, string) (model.Car, error)) *MockCarService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, filterInput
func (_m *MockCarService) GetAll(ctx context.Context, filterInput model.CarFilterInput) ([]model.Car, error) {
	ret := _m.Called(ctx, filterInput)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Car
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarFilterInput) ([]model.Car, error)); ok {
		return rf(ctx, filterInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarFilterInput) []model.Car); ok {
		r0 = rf(ctx, filterInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Car)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarFilterInput) error); ok {
		r1 = rf(ctx, filterInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockCarService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filterInput model.CarFilterInput
func (_e *MockCarService_Expecter) GetAll(ctx interface{}, filterInput interface{}) *MockCarService_GetAll_Call {
	return &MockCarService_GetAll_Call{Call: _e.mock.On("GetAll", ctx, filterInput)}
}

func (_c *MockCarService_GetAll_Call) Run(run func(ctx context.Context, filterInput model.CarFilterInput)) *MockCarService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarFilterInput))
	})
	return _c
}

func (_c *MockCarService_GetAll_Call) Return(_a0 []model.Car, _a1 error) *MockCarService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_GetAll_Call) RunAndReturn(run func(context.Context, model.CarFilterInput) ([]model.Car, error)) *MockCarService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetCarBatteryHistory provides a mock function with given fields: ctx, filter
func (_m *MockCarService) GetCarBatteryHistory(ctx context.Context, filter model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCarBatteryHistory")
	}

	var r0 []model.CarTelematicsEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TelematicsEventFilter) []model.CarTelematicsEvent); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarTelematicsEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TelematicsEventFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_GetCarBatteryHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCarBatteryHistory'
type MockCarService_GetCarBatteryHistory_Call struct {
	*mock.Call
}

// GetCarBatteryHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.TelematicsEventFilter
func (_e *MockCarService_Expecter) GetCarBatteryHistory(ctx interface{}, filter interface{}) *MockCarService_GetCarBatteryHistory_Call {
	return &MockCarService_GetCarBatteryHistory_Call{Call: _e.mock.On("GetCarBatteryHistory", ctx, filter)}
}

func (_c *MockCarService_GetCarBatteryHistory_Call) Run(run func(ctx context.Context, filter model.TelematicsEventFilter)) *MockCarService_GetCarBatteryHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TelematicsEventFilter))
	})
	return _c
}

func (_c *MockCarService_GetCarBatteryHistory_Call) Return(_a0 []model.CarTelematicsEvent, _a1 error) *MockCarService_GetCarBatteryHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_GetCarBatteryHistory_Call) RunAndReturn(run func(context.Context, model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error)) *MockCarService_GetCarBatteryHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetCarFuelHistory provides a mock function with given fields: ctx, filter
func (_m *MockCarService) GetCarFuelHistory(ctx context.Context, filter model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCarFuelHistory")
	}

	var r0 []model.CarTelematicsEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TelematicsEventFilter) []model.CarTelematicsEvent); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarTelematicsEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TelematicsEventFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_GetCarFuelHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCarFuelHistory'
type MockCarService_GetCarFuelHistory_Call struct {
	*mock.Call
}

// GetCarFuelHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.TelematicsEventFilter
func (_e *MockCarService_Expecter) GetCarFuelHistory(ctx interface{}, filter interface{}) *MockCarService_GetCarFuelHistory_Call {
	return &MockCarService_GetCarFuelHistory_Call{Call: _e.mock.On("GetCarFuelHistory", ctx, filter)}
}

func (_c *MockCarService_GetCarFuelHistory_Call) Run(run func(ctx context.Context, filter model.TelematicsEventFilter)) *MockCarService_GetCarFuelHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TelematicsEventFilter))
	})
	return _c
}

func (_c *MockCarService_GetCarFuelHistory_Call) Return(_a0 []model.CarTelematicsEvent, _a1 error) *MockCarService_GetCarFuelHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_GetCarFuelHistory_Call) RunAndReturn(run func(context.Context, model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error)) *MockCarService_GetCarFuelHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetCarLocationHistory provides a mock function with given fields: ctx, filter
func (_m *MockCarService) GetCarLocationHistory(ctx context.Context, filter model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCarLocationHistory")
	}

	var r0 []model.CarTelematicsEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TelematicsEventFilter) []model.CarTelematicsEvent); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarTelematicsEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TelematicsEventFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_GetCarLocationHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCarLocationHistory'
type MockCarService_GetCarLocationHistory_Call struct {
	*mock.Call
}

// GetCarLocationHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.TelematicsEventFilter
func (_e *MockCarService_Expecter) GetCarLocationHistory(ctx interface{}, filter interface{}) *MockCarService_GetCarLocationHistory_Call {
	return &MockCarService_GetCarLocationHistory_Call{Call: _e.mock.On("GetCarLocationHistory", ctx, filter)}
}

func (_c *MockCarService_GetCarLocationHistory_Call) Run(run func(ctx context.Context, filter model.TelematicsEventFilter)) *MockCarService_GetCarLocationHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TelematicsEventFilter))
	})
	return _c
}

func (_c *MockCarService_GetCarLocationHistory_Call) Return(_a0 []model.CarTelematicsEvent, _a1 error) *MockCarService_GetCarLocationHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_GetCarLocationHistory_Call) RunAndReturn(run func(context.Context, model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error)) *MockCarService_GetCarLocationHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetCarMileageHistory provides a mock function with given fields: ctx, filter
func (_m *MockCarService) GetCarMileageHistory(ctx context.Context, filter model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCarMileageHistory")
	}

	var r0 []model.CarTelematicsEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TelematicsEventFilter) []model.CarTelematicsEvent); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarTelematicsEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TelematicsEventFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_GetCarMileageHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCarMileageHistory'
type MockCarService_GetCarMileageHistory_Call struct {
	*mock.Call
}

// GetCarMileageHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.TelematicsEventFilter
func (_e *MockCarService_Expecter) GetCarMileageHistory(ctx interface{}, filter interface{}) *MockCarService_GetCarMileageHistory_Call {
	return &MockCarService_GetCarMileageHistory_Call{Call: _e.mock.On("GetCarMileageHistory", ctx, filter)}
}

func (_c *MockCarService_GetCarMileageHistory_Call) Run(run func(ctx context.Context, filter model.TelematicsEventFilter)) *MockCarService_GetCarMileageHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TelematicsEventFilter))
	})
	return _c
}

func (_c *MockCarService_GetCarMileageHistory_Call) Return(_a0 []model.CarTelematicsEvent, _a1 error) *MockCarService_GetCarMileageHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_GetCarMileageHistory_Call) RunAndReturn(run func(context.Context, model.TelematicsEventFilter) ([]model.CarTelematicsEvent, error)) *MockCarService_GetCarMileageHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetCarStatusHistory provides a mock function with given fields: ctx, filter
func (_m *MockCarService) GetCarStatusHistory(ctx context.Context, filter model.CarStatusLogFilter) ([]model.CarStatusLogEntry, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCarStatusHistory")
	}

	var r0 []model.CarStatusLogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CarStatusLogFilter) ([]model.CarStatusLogEntry, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CarStatusLogFilter) []model.CarStatusLogEntry); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarStatusLogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CarStatusLogFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_GetCarStatusHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCarStatusHistory'
type MockCarService_GetCarStatusHistory_Call struct {
	*mock.Call
}

// GetCarStatusHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.CarStatusLogFilter
func (_e *MockCarService_Expecter) GetCarStatusHistory(ctx interface{}, filter interface{}) *MockCarService_GetCarStatusHistory_Call {
	return &MockCarService_GetCarStatusHistory_Call{Call: _e.mock.On("GetCarStatusHistory", ctx, filter)}
}

func (_c *MockCarService_GetCarStatusHistory_Call) Run(run func(ctx context.Context, filter model.CarStatusLogFilter)) *MockCarService_GetCarStatusHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CarStatusLogFilter))
	})
	return _c
}

func (_c *MockCarService_GetCarStatusHistory_Call) Return(_a0 []model.CarStatusLogEntry, _a1 error) *MockCarService_GetCarStatusHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_GetCarStatusHistory_Call) RunAndReturn(run func(context.Context, model.CarStatusLogFilter) ([]model.CarStatusLogEntry, error)) *MockCarService_GetCarStatusHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageUploadData provides a mock function with given fields: ctx
func (_m *MockCarService) GetImageUploadData(ctx context.Context) (model.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImageUploadData")
	}

	var r0 model.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarService_GetImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageUploadData'
type MockCarService_GetImageUploadData_Call struct {
	*mock.Call
}

// GetImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCarService_Expecter) GetImageUploadData(ctx interface{}) *MockCarService_GetImageUploadData_Call {
	return &MockCarService_GetImageUploadData_Call{Call: _e.mock.On("GetImageUploadData", ctx)}
}

func (_c *MockCarService_GetImageUploadData_Call) Run(run func(ctx context.Context)) *MockCarService_GetImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCarService_GetImageUploadData_Call) Return(_a0 model.ImageUploadData, _a1 error) *MockCarService_GetImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarService_GetImageUploadData_Call) RunAndReturn(run func(context.Context) (model.ImageUploadData, error)) *MockCarService_GetImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updateInput
func (_m *MockCarService) Update(ctx context.Context, id string, updateInput model.CarUpdateInput) error {
	ret := _m.Called(ctx, id, updateInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarUpdateInput) error); ok {
		r0 = rf(ctx, id, updateInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - updateInput model.CarUpdateInput
func (_e *MockCarService_Expecter) Update(ctx interface{}, id interface{}, updateInput interface{}) *MockCarService_Update_Call {
	return &MockCarService_Update_Call{Call: _e.mock.On("Update", ctx, id, updateInput)}
}

func (_c *MockCarService_Update_Call) Run(run func(ctx context.Context, id string, updateInput model.CarUpdateInput)) *MockCarService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarUpdateInput))
	})
	return _c
}

func (_c *MockCarService_Update_Call) Return(_a0 error) *MockCarService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarService_Update_Call) RunAndReturn(run func(context.Context, string, model.CarUpdateInput) error) *MockCarService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCarStatus provides a mock function with given fields: ctx, id, statusInput
func (_m *MockCarService) UpdateCarStatus(ctx context.Context, id string, statusInput model.CarStatusUpdateInput) error {
	ret := _m.Called(ctx, id, statusInput)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCarStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarStatusUpdateInput) error); ok {
		r0 = rf(ctx, id, statusInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarService_UpdateCarStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCarStatus'
type MockCarService_UpdateCarStatus_Call struct {
	*mock.Call
}

// UpdateCarStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - statusInput model.CarStatusUpdateInput
func (_e *MockCarService_Expecter) UpdateCarStatus(ctx interface{}, id interface{}, statusInput interface{}) *MockCarService_UpdateCarStatus_Call {
	return &MockCarService_UpdateCarStatus_Call{Call: _e.mock.On("UpdateCarStatus", ctx, id, statusInput)}
}

func (_c *MockCarService_UpdateCarStatus_Call) Run(run func(ctx context.Context, id string, statusInput model.CarStatusUpdateInput)) *MockCarService_UpdateCarStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarStatusUpdateInput))
	})
	return _c
}

func (_c *MockCarService_UpdateCarStatus_Call) Return(_a0 error) *MockCarService_UpdateCarStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarService_UpdateCarStatus_Call) RunAndReturn(run func(context.Context, string, model.CarStatusUpdateInput) error) *MockCarService_UpdateCarStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCarTelemetry provides a mock function with given fields: ctx, id, input
func (_m *MockCarService) UpdateCarTelemetry(ctx context.Context, id string, input model.CarTelematicsUpdateInput) error {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCarTelemetry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.CarTelematicsUpdateInput) error); ok {
		r0 = rf(ctx, id, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarService_UpdateCarTelemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCarTelemetry'
type MockCarService_UpdateCarTelemetry_Call struct {
	*mock.Call
}

// UpdateCarTelemetry is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - input model.CarTelematicsUpdateInput
func (_e *MockCarService_Expecter) UpdateCarTelemetry(ctx interface{}, id interface{}, input interface{}) *MockCarService_UpdateCarTelemetry_Call {
	return &MockCarService_UpdateCarTelemetry_Call{Call: _e.mock.On("UpdateCarTelemetry", ctx, id, input)}
}

func (_c *MockCarService_UpdateCarTelemetry_Call) Run(run func(ctx context.Context, id string, input model.CarTelematicsUpdateInput)) *MockCarService_UpdateCarTelemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.CarTelematicsUpdateInput))
	})
	return _c
}

func (_c *MockCarService_UpdateCarTelemetry_Call) Return(_a0 error) *MockCarService_UpdateCarTelemetry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarService_UpdateCarTelemetry_Call) RunAndReturn(run func(context.Context, string, model.CarTelematicsUpdateInput) error) *MockCarService_UpdateCarTelemetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarService creates a new instance of MockCarService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarService {
	mock := &MockCarService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
