// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPinger is an autogenerated mock type for the Pinger type
type MockPinger struct {
	mock.Mock
}

type MockPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPinger) EXPECT() *MockPinger_Expecter {
	return &MockPinger_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with given fields: ctx
func (_m *MockPinger) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPinger_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPinger_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPinger_Expecter) Ping(ctx interface{}) *MockPinger_Ping_Call {
	return &MockPinger_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockPinger_Ping_Call) Run(run func(ctx context.Context)) *MockPinger_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPinger_Ping_Call) Return(_a0 error) *MockPinger_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPinger_Ping_Call) RunAndReturn(run func(context.Context) error) *MockPinger_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPinger creates a new instance of MockPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPinger {
	mock := &MockPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
