// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockNATSChecker is an autogenerated mock type for the NATSChecker type
type MockNATSChecker struct {
	mock.Mock
}

type MockNATSChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNATSChecker) EXPECT() *MockNATSChecker_Expecter {
	return &MockNATSChecker_Expecter{mock: &_m.Mock}
}

// IsConnected provides a mock function with no fields
func (_m *MockNATSChecker) IsConnected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockNATSChecker_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockNATSChecker_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MockNATSChecker_Expecter) IsConnected() *MockNATSChecker_IsConnected_Call {
	return &MockNATSChecker_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MockNATSChecker_IsConnected_Call) Run(run func()) *MockNATSChecker_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNATSChecker_IsConnected_Call) Return(_a0 bool) *MockNATSChecker_IsConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNATSChecker_IsConnected_Call) RunAndReturn(run func() bool) *MockNATSChecker_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNATSChecker creates a new instance of MockNATSChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNATSChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNATSChecker {
	mock := &MockNATSChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
