// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "carsharing/car-service/internal/model"
	validation "carsharing/car-service/internal/validation"
	sharedmodel "carsharing/shared/model"
)

// MockCarInsuranceService is an autogenerated mock type for the CarInsuranceService type
type MockCarInsuranceService struct {
	mock.Mock
}

type MockCarInsuranceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCarInsuranceService) EXPECT() *MockCarInsuranceService_Expecter {
	return &MockCarInsuranceService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, createInput
func (_m *MockCarInsuranceService) Create(ctx context.Context, createInput validation.CarInsuranceCreate) (string, error) {
	ret := _m.Called(ctx, createInput)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarInsuranceCreate) (string, error)); ok {
		return rf(ctx, createInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarInsuranceCreate) string); ok {
		r0 = rf(ctx, createInput)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.CarInsuranceCreate) error); ok {
		r1 = rf(ctx, createInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarInsuranceService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCarInsuranceService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - createInput validation.CarInsuranceCreate
func (_e *MockCarInsuranceService_Expecter) Create(ctx interface{}, createInput interface{}) *MockCarInsuranceService_Create_Call {
	return &MockCarInsuranceService_Create_Call{Call: _e.mock.On("Create", ctx, createInput)}
}

func (_c *MockCarInsuranceService_Create_Call) Run(run func(ctx context.Context, createInput validation.CarInsuranceCreate)) *MockCarInsuranceService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarInsuranceCreate))
	})
	return _c
}

func (_c *MockCarInsuranceService_Create_Call) Return(_a0 string, _a1 error) *MockCarInsuranceService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarInsuranceService_Create_Call) RunAndReturn(run func(context.Context, validation.CarInsuranceCreate) (string, error)) *MockCarInsuranceService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCarInsuranceService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarInsuranceService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCarInsuranceService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarInsuranceService_Expecter) Delete(ctx interface{}, id interface{}) *MockCarInsuranceService_Delete_Call {
	return &MockCarInsuranceService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCarInsuranceService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCarInsuranceService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarInsuranceService_Delete_Call) Return(_a0 error) *MockCarInsuranceService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarInsuranceService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCarInsuranceService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockCarInsuranceService) Get(ctx context.Context, id string) (model.CarInsurance, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.CarInsurance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CarInsurance, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CarInsurance); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.CarInsurance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarInsuranceService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCarInsuranceService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCarInsuranceService_Expecter) Get(ctx interface{}, id interface{}) *MockCarInsuranceService_Get_Call {
	return &MockCarInsuranceService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockCarInsuranceService_Get_Call) Run(run func(ctx context.Context, id string)) *MockCarInsuranceService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCarInsuranceService_Get_Call) Return(_a0 model.CarInsurance, _a1 error) *MockCarInsuranceService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarInsuranceService_Get_Call) RunAndReturn(run func(context.Context, string) (model.CarInsurance, error)) *MockCarInsuranceService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filterInput
func (_m *MockCarInsuranceService) List(ctx context.Context, filterInput validation.CarInsuranceFilter) ([]model.CarInsurance, error) {
	ret := _m.Called(ctx, filterInput)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.CarInsurance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarInsuranceFilter) ([]model.CarInsurance, error)); ok {
		return rf(ctx, filterInput)
	}
	if rf, ok := ret.Get(0).(func(context.Context, validation.CarInsuranceFilter) []model.CarInsurance); ok {
		r0 = rf(ctx, filterInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CarInsurance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, validation.CarInsuranceFilter) error); ok {
		r1 = rf(ctx, filterInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarInsuranceService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCarInsuranceService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filterInput validation.CarInsuranceFilter
func (_e *MockCarInsuranceService_Expecter) List(ctx interface{}, filterInput interface{}) *MockCarInsuranceService_List_Call {
	return &MockCarInsuranceService_List_Call{Call: _e.mock.On("List", ctx, filterInput)}
}

func (_c *MockCarInsuranceService_List_Call) Run(run func(ctx context.Context, filterInput validation.CarInsuranceFilter)) *MockCarInsuranceService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(validation.CarInsuranceFilter))
	})
	return _c
}

func (_c *MockCarInsuranceService_List_Call) Return(_a0 []model.CarInsurance, _a1 error) *MockCarInsuranceService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarInsuranceService_List_Call) RunAndReturn(run func(context.Context, validation.CarInsuranceFilter) ([]model.CarInsurance, error)) *MockCarInsuranceService_List_Call {
	_c.Call.Return(run)
	return _c
}

// GetImageUploadData provides a mock function with given fields: ctx
func (_m *MockCarInsuranceService) GetImageUploadData(ctx context.Context) (sharedmodel.ImageUploadData, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetImageUploadData")
	}

	var r0 sharedmodel.ImageUploadData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (sharedmodel.ImageUploadData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) sharedmodel.ImageUploadData); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(sharedmodel.ImageUploadData)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCarInsuranceService_GetImageUploadData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImageUploadData'
type MockCarInsuranceService_GetImageUploadData_Call struct {
	*mock.Call
}

// GetImageUploadData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCarInsuranceService_Expecter) GetImageUploadData(ctx interface{}) *MockCarInsuranceService_GetImageUploadData_Call {
	return &MockCarInsuranceService_GetImageUploadData_Call{Call: _e.mock.On("GetImageUploadData", ctx)}
}

func (_c *MockCarInsuranceService_GetImageUploadData_Call) Run(run func(ctx context.Context)) *MockCarInsuranceService_GetImageUploadData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCarInsuranceService_GetImageUploadData_Call) Return(_a0 sharedmodel.ImageUploadData, _a1 error) *MockCarInsuranceService_GetImageUploadData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCarInsuranceService_GetImageUploadData_Call) RunAndReturn(run func(context.Context) (sharedmodel.ImageUploadData, error)) *MockCarInsuranceService_GetImageUploadData_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updateInput
func (_m *MockCarInsuranceService) Update(ctx context.Context, id string, updateInput validation.CarInsuranceUpdate) error {
	ret := _m.Called(ctx, id, updateInput)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, validation.CarInsuranceUpdate) error); ok {
		r0 = rf(ctx, id, updateInput)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCarInsuranceService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCarInsuranceService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - updateInput validation.CarInsuranceUpdate
func (_e *MockCarInsuranceService_Expecter) Update(ctx interface{}, id interface{}, updateInput interface{}) *MockCarInsuranceService_Update_Call {
	return &MockCarInsuranceService_Update_Call{Call: _e.mock.On("Update", ctx, id, updateInput)}
}

func (_c *MockCarInsuranceService_Update_Call) Run(run func(ctx context.Context, id string, updateInput validation.CarInsuranceUpdate)) *MockCarInsuranceService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(validation.CarInsuranceUpdate))
	})
	return _c
}

func (_c *MockCarInsuranceService_Update_Call) Return(_a0 error) *MockCarInsuranceService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCarInsuranceService_Update_Call) RunAndReturn(run func(context.Context, string, validation.CarInsuranceUpdate) error) *MockCarInsuranceService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCarInsuranceService creates a new instance of MockCarInsuranceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCarInsuranceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCarInsuranceService {
	mock := &MockCarInsuranceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
