// Code generated by mockery. DO NOT EDIT.

package handlermocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "carsharing/trip-service/internal/model"
)

// MockTripService is an autogenerated mock type for the TripService type
type MockTripService struct {
	mock.Mock
}

type MockTripService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripService) EXPECT() *MockTripService_Expecter {
	return &MockTripService_Expecter{mock: &_m.Mock}
}

// CancelTrip provides a mock function with given fields: ctx, id, reason
func (_m *MockTripService) CancelTrip(ctx context.Context, id string, reason *string) error {
	ret := _m.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for CancelTrip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string) error); ok {
		r0 = rf(ctx, id, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripService_CancelTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTrip'
type MockTripService_CancelTrip_Call struct {
	*mock.Call
}

// CancelTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reason *string
func (_e *MockTripService_Expecter) CancelTrip(ctx interface{}, id interface{}, reason interface{}) *MockTripService_CancelTrip_Call {
	return &MockTripService_CancelTrip_Call{Call: _e.mock.On("CancelTrip", ctx, id, reason)}
}

func (_c *MockTripService_CancelTrip_Call) Run(run func(ctx context.Context, id string, reason *string)) *MockTripService_CancelTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string))
	})
	return _c
}

func (_c *MockTripService_CancelTrip_Call) Return(_a0 error) *MockTripService_CancelTrip_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripService_CancelTrip_Call) RunAndReturn(run func(context.Context, string, *string) error) *MockTripService_CancelTrip_Call {
	_c.Call.Return(run)
	return _c
}

// EndTrip provides a mock function with given fields: ctx, id
func (_m *MockTripService) EndTrip(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for EndTrip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTripService_EndTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndTrip'
type MockTripService_EndTrip_Call struct {
	*mock.Call
}

// EndTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTripService_Expecter) EndTrip(ctx interface{}, id interface{}) *MockTripService_EndTrip_Call {
	return &MockTripService_EndTrip_Call{Call: _e.mock.On("EndTrip", ctx, id)}
}

func (_c *MockTripService_EndTrip_Call) Run(run func(ctx context.Context, id string)) *MockTripService_EndTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripService_EndTrip_Call) Return(_a0 error) *MockTripService_EndTrip_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTripService_EndTrip_Call) RunAndReturn(run func(context.Context, string) error) *MockTripService_EndTrip_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrip provides a mock function with given fields: ctx, id
func (_m *MockTripService) GetTrip(ctx context.Context, id string) (model.Trip, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTrip")
	}

	var r0 model.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Trip, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Trip); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Trip)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_GetTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrip'
type MockTripService_GetTrip_Call struct {
	*mock.Call
}

// GetTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTripService_Expecter) GetTrip(ctx interface{}, id interface{}) *MockTripService_GetTrip_Call {
	return &MockTripService_GetTrip_Call{Call: _e.mock.On("GetTrip", ctx, id)}
}

func (_c *MockTripService_GetTrip_Call) Run(run func(ctx context.Context, id string)) *MockTripService_GetTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripService_GetTrip_Call) Return(_a0 model.Trip, _a1 error) *MockTripService_GetTrip_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_GetTrip_Call) RunAndReturn(run func(context.Context, string) (model.Trip, error)) *MockTripService_GetTrip_Call {
	_c.Call.Return(run)
	return _c
}

// GetTripStatusHistory provides a mock function with given fields: ctx, filter
func (_m *MockTripService) GetTripStatusHistory(ctx context.Context, filter model.TripStatusReadingFilter) ([]model.TripStatusReading, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetTripStatusHistory")
	}

	var r0 []model.TripStatusReading
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TripStatusReadingFilter) ([]model.TripStatusReading, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TripStatusReadingFilter) []model.TripStatusReading); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TripStatusReading)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TripStatusReadingFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_GetTripStatusHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTripStatusHistory'
type MockTripService_GetTripStatusHistory_Call struct {
	*mock.Call
}

// GetTripStatusHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.TripStatusReadingFilter
func (_e *MockTripService_Expecter) GetTripStatusHistory(ctx interface{}, filter interface{}) *MockTripService_GetTripStatusHistory_Call {
	return &MockTripService_GetTripStatusHistory_Call{Call: _e.mock.On("GetTripStatusHistory", ctx, filter)}
}

func (_c *MockTripService_GetTripStatusHistory_Call) Run(run func(ctx context.Context, filter model.TripStatusReadingFilter)) *MockTripService_GetTripStatusHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TripStatusReadingFilter))
	})
	return _c
}

func (_c *MockTripService_GetTripStatusHistory_Call) Return(_a0 []model.TripStatusReading, _a1 error) *MockTripService_GetTripStatusHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_GetTripStatusHistory_Call) RunAndReturn(run func(context.Context, model.TripStatusReadingFilter) ([]model.TripStatusReading, error)) *MockTripService_GetTripStatusHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetTripSummary provides a mock function with given fields: ctx, tripID
func (_m *MockTripService) GetTripSummary(ctx context.Context, tripID string) (model.TripSummary, error) {
	ret := _m.Called(ctx, tripID)

	if len(ret) == 0 {
		panic("no return value specified for GetTripSummary")
	}

	var r0 model.TripSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.TripSummary, error)); ok {
		return rf(ctx, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.TripSummary); ok {
		r0 = rf(ctx, tripID)
	} else {
		r0 = ret.Get(0).(model.TripSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_GetTripSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTripSummary'
type MockTripService_GetTripSummary_Call struct {
	*mock.Call
}

// GetTripSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
func (_e *MockTripService_Expecter) GetTripSummary(ctx interface{}, tripID interface{}) *MockTripService_GetTripSummary_Call {
	return &MockTripService_GetTripSummary_Call{Call: _e.mock.On("GetTripSummary", ctx, tripID)}
}

func (_c *MockTripService_GetTripSummary_Call) Run(run func(ctx context.Context, tripID string)) *MockTripService_GetTripSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripService_GetTripSummary_Call) Return(_a0 model.TripSummary, _a1 error) *MockTripService_GetTripSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_GetTripSummary_Call) RunAndReturn(run func(context.Context, string) (model.TripSummary, error)) *MockTripService_GetTripSummary_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrips provides a mock function with given fields: ctx, filter
func (_m *MockTripService) ListTrips(ctx context.Context, filter model.TripFilter) ([]model.Trip, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListTrips")
	}

	var r0 []model.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.TripFilter) ([]model.Trip, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.TripFilter) []model.Trip); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.TripFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_ListTrips_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrips'
type MockTripService_ListTrips_Call struct {
	*mock.Call
}

// ListTrips is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.TripFilter
func (_e *MockTripService_Expecter) ListTrips(ctx interface{}, filter interface{}) *MockTripService_ListTrips_Call {
	return &MockTripService_ListTrips_Call{Call: _e.mock.On("ListTrips", ctx, filter)}
}

func (_c *MockTripService_ListTrips_Call) Run(run func(ctx context.Context, filter model.TripFilter)) *MockTripService_ListTrips_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.TripFilter))
	})
	return _c
}

func (_c *MockTripService_ListTrips_Call) Return(_a0 []model.Trip, _a1 error) *MockTripService_ListTrips_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_ListTrips_Call) RunAndReturn(run func(context.Context, model.TripFilter) ([]model.Trip, error)) *MockTripService_ListTrips_Call {
	_c.Call.Return(run)
	return _c
}

// StartTrip provides a mock function with given fields: ctx, bookingID
func (_m *MockTripService) StartTrip(ctx context.Context, bookingID string) (string, error) {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for StartTrip")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripService_StartTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTrip'
type MockTripService_StartTrip_Call struct {
	*mock.Call
}

// StartTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockTripService_Expecter) StartTrip(ctx interface{}, bookingID interface{}) *MockTripService_StartTrip_Call {
	return &MockTripService_StartTrip_Call{Call: _e.mock.On("StartTrip", ctx, bookingID)}
}

func (_c *MockTripService_StartTrip_Call) Run(run func(ctx context.Context, bookingID string)) *MockTripService_StartTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTripService_StartTrip_Call) Return(_a0 string, _a1 error) *MockTripService_StartTrip_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripService_StartTrip_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTripService_StartTrip_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripService creates a new instance of MockTripService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripService {
	mock := &MockTripService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
